### ISSUE TITLE
Cannot access a disposed object(Socket) leads to a Timeout expired MySqlException

### ISSUE THREAD

**Issue by baidusoubudao** [mysql-net/MySqlConnector#1020]
Hi folks,

I'm trying to test a Web API project but have never been able to handle any CRUD requests. 
The problem seems to have something to do with socket or MySQL connection.

Environment: Mac, .NET Core 2.2.0, Entity Framework Core.

```
An unhandled exception occurred while processing the request.
ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)

MySqlException: Connect Timeout expired.
MySqlConnector.Core.ServerSession.OpenTcpSocketAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken)
```
# Raw exception details
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__27_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at MySqlConnector.Core.ServerSession.OpenTcpSocketAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 756
```
# MySqlException: Connect Timeout expired
```
MySqlConnector.Core.ServerSession.OpenTcpSocketAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken)
MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs
MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs
MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs
....
```
The project has been finished for a while , not sure whether I have to upgrade some packages or not?  

Thanks!
JL

**Comment by bgrainger** [comment]
This is your problem:

> MySqlException: Connect Timeout expired.

The code is unable to connect to the MySQL Server within the connect timeout period you've specified (default 15 seconds).

Check your connection string, make sure the server details (host and port) are correct, make sure there's no firewall blocking access to the MySQL server, test the connection using MySQL Workbench from that same machine, etc.
