### ISSUE TITLE
An exception "Datetime function: datetime field overflow" is thrown when inserting the 'DateTime.MaxValue' value 

### ISSUE THREAD

**Issue by xiangxiren** [mysql-net/MySqlConnector#1034]
This is my test code:
```
const string sql = "INSERT INTO test (max_value) VALUES(@MaxValue)";
using var conn = new MySqlConnection("");
if (conn.State == ConnectionState.Closed)
{
    conn.Open();
}

using var command = conn.CreateCommand();
command.CommandType = CommandType.Text;
command.CommandText = sql;
command.Parameters.Add(new MySqlParameter("@MaxValue", DateTime.MaxValue));

var count = command.ExecuteNonQuery();
```

Exception stack:
```
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at MySqlConnector.Core.ResultSet.<ReadResultSetHeaderAsync>d__2.MoveNext() in /_/src/MySqlConnector/Core/ResultSet.cs:line 49
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 137
   at MySqlConnector.MySqlDataReader.<CreateAsync>d__97.MoveNext() in /_/src/MySqlConnector/MySqlDataReader.cs:line 458
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySqlConnector.Core.CommandExecutor.<ExecuteReaderAsync>d__0.MoveNext() in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySqlConnector.MySqlCommand.<ExecuteNonQueryAsync>d__69.MoveNext() in /_/src/MySqlConnector/MySqlCommand.cs:line 263
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MySqlConnector.MySqlCommand.ExecuteNonQuery() in /_/src/MySqlConnector/MySqlCommand.cs:line 98
```

It is successful when I execute SQL directly
```
INSERT INTO test (max_value) VALUES('9999/12/31 23:59:59')
```

And `DateTime.MinValue` is OK.

**Comment by bgrainger** [comment]
`DateTime.MaxValue` is actually `9999-12-31 23:59:59.9999999`, which doesn't fit in your field.

To fix this, change the column type to `DATETIME(6)` or use `new DateTime(9999, 12, 31, 23, 59, 59)` instead of `DateTime.MaxValue`.
