### ISSUE TITLE
CatalinAdlerDF question

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#1038]
@bgrainger i am now also facing this at high rate, after disabling some health checks.
How do i diagnose this?
How do i find out what's keeping the connections alive?

_Originally posted by @CatalinAdlerDF in https://github.com/mysql-net/MySqlConnector/issues/1033#issuecomment-922528374_

**Comment by bgrainger** [comment]
@CatalinAdlerDF please add full troubleshooting details: exception, call stacks, logs, etc.

**Comment by CatalinAdlerDF** [comment]
```
MySqlConnector.MySqlException (0x80004005): Connect Timeout expired. All pooled connections are in use.
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(TaskNode asyncWaiter, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 139
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 902
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 902
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 435
```

I am up to date with, .net, the connector. I am using timeouts everywhere and (await) usings everywhere.

I am seeing `"Pool1 is empty; recovering leaked sessions"` log entries just before i get the exception.

**Comment by bgrainger** [comment]
What is the `MaxPoolSize` you're using? Are you coming close to that, based on request volume for your application?

Can you email full logs to <my-github-username>@gmail.com?

**Comment by CatalinAdlerDF** [comment]
Using 150;
`ConnectionTimeout=30;Pooling=true;AllowLoadLocalInfile=true;Allow Zero Datetime=True;MaximumPoolSize=150;Connection Idle Timeout=60;AllowUserVariables=true;`

Which of the logs would help? (ConnectionPool, ServerSession?)

**Comment by bgrainger** [comment]
What version of MySqlConnector are you running? (I wouldn't expect any problems with >= 1.3.10, or an earlier version as long as `DeferConnectionReset = True` is set.)

Last time you sent logs, there were several `UnobservedTaskException`s being thrown. You said you fixed that, but I haven't seen new logs since then. Can you send more?

`Connection Idle Timeout=60` could be a little aggressive. It shouldn't cause any problems to have it that low, but could you try with a longer idle timeout?

**Comment by bgrainger** [comment]
Closing issue without a consistent repro.
