### ISSUE TITLE
PrepareAsync Order Issue on Select Cause Overflow Exception

### ISSUE THREAD

**Issue by thomas-oliver-cko** [mysql-net/MySqlConnector#1043]
## Summary
It seems like at a high level, that preparing a certain type of MySQL select statement causes an `OverflowException` when reading from a `MySqlDataReader`

## Steps To Reproduce
Using the following code:

```csharp
using var connection = new MySqlConnection(connectionString);

using var command = connection.CreateCommand();
command.CommandText = "SELECT id,reference,version FROM task_specs WHERE reference=@reference";
command.Parameters.AddWithValue("reference", reference);

connection.Open();
command.Prepare();
using var reader = command.ExecuteReader();

while (reader.Read()) {}
```

with the following table schema (it has more columns but here are the interesting ones):
```
id BIGINT(20) UNSIGNED PRIMARY KEY AUTO INCREMENT
reference VARCHAR(255)
version BIGINT(20)
```

Causes the following exception:
```
System.OverflowException
Arithmetic operation resulted in an overflow.
   at MySqlConnector.Core.ResultSet.<ScanRowAsync>g__ScanRowAsyncRemainder|9_1(ResultSet resultSet, PayloadData payload, Row row) in /_/src/MySqlConnector/Core/ResultSet.cs:line 261
   at MySqlConnector.Core.ResultSet.ScanRowAsync(IOBehavior ioBehavior, Row row, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ResultSet.cs:line 236
   at MySqlConnector.Core.ResultSet.ReadAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ResultSet.cs:line 200
   at MySqlConnector.Core.ResultSet.Read() in /_/src/MySqlConnector/Core/ResultSet.cs:line 192
   at MySqlConnector.MySqlDataReader.Read() in /_/src/MySqlConnector/MySqlDataReader.cs:line 34
```

We have noted the following things when investigating the issue:
- It only occurs when `id` and `version` are before and after `reference` in the `SELECT` statement. For example, `SELECT id,version,reference` works, whereas `SELECT id,reference,version` throws the exception
- It only occurs when the command is prepared. If the command is not prepared, then it does not throw the exception
- It only occurs on some rows even though there is no real discernable difference in the data. Here is some row IDs it occurs on: 
  - 46078, 47102, 48126, 48786, 49406, 49662, 49918, 50174, 50221, 50430, 50686, 51198, 51248, 51418, 51454, 51710, 51966, 52002, 52030, 52222, 52363, 52478, 52734, 52757, 52857, 52990, 53005, 53246, 53559
- It occurs whether using async or sync overloads
- It occurs when doing `SELECT *`, as long as the Id, reference, and version are in that order in the database
- It only occurs when the value between the two BIGINTS (in this case reference) is used as a parameter in the query
- We have only got it to occur when reference is unique (i.e. the SELECT statement only returns 1 entry)

**Comment by bgrainger** [comment]
Thanks for the thorough bug report!

> This occurs using MySqlConnector 1.3.x only. The error does not occur in version 1.2.1.

This is quite possibly because `IgnorePrepare` was `true` in 1.2x, so `MySqlCommand.Prepare` was a no-op; it may be a longstanding bug, not necessarily something strictly new in 1.3 (cf. https://github.com/mysql-net/MySqlConnector/issues/1018#issuecomment-895463254).

**Comment by bgrainger** [comment]
Based on the somewhat variable nature of the crash, I wonder if this is actually just a duplicate of https://github.com/mysql-net/MySqlConnector/issues/1018, which requires a really specific combination of bytes to be sent over the wire to trigger it. I didn't remember (until just now) that that bug fix wasn't in 1.3.x.

Are you able to test with 1.4.0.beta-3? (Despite the "beta" label, it shouldn't be less stable than 1.3.11.) If you can confirm that it doesn't throw the exception, I could backport the fix into 1.3.13.

**Comment by bgrainger** [comment]
> It only occurs on some rows even though there is no real discernable difference in the data. Here is some row IDs it occurs on: 46078, 47102, 48126, 48786, 49406, 49662, 49918, 50174, 50221, 50430, 50686, 51198, 51248, 51418, 51454, 51710, 51966, 52002, 52030, 52222, 52363, 52478, 52734, 52757, 52857, 52990, 53005, 53246, 53559

A large proportion of those numbers are `0x__FE` in hex; in little-endian byte order, they would be written with `0xFE` first, which could be incorrectly decoded by the buggy code as being the prefix for an 8-byte integer. That's another suggestion that this is a duplicate of #1018.

**Comment by thomas-oliver-cko** [comment]
Hi @bgrainger, sorry for the late reply! I've tested with 1.4.0.beta-4 and it doesn't throw the exception! It appears it was a duplicate of #1018 then. We'll go live ignoring the prepare statement, and when 1.4.0 is released fully we will move to that. Thanks for the help 😄

**Comment by bgrainger** [comment]
Duplicate of #1018.

**Comment by bgrainger** [comment]
Duplicate of #1018
