### ISSUE TITLE
Timeouts: Operation cancelled exception

### ISSUE THREAD

**Issue by edwinloubser** [mysql-net/MySqlConnector#1084]
**Software versions**
MySqlConnector version: 2.0.0
Server type (MySQL, MariaDB, Aurora, etc.) and version: Aurora
.NET version: 6.0
(Optional) ORM NuGet packages and versions: 

**Describe the bug**
Timeouts / Operation cancelled exceptions in AwaitableSocketAsyncEventArgs

**Exception**
Operation canceled
	Exception Type: System.Net.Sockets.SocketException
	Stack trace    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at MySqlConnector.Protocol.Serialization.SocketByteHandler.DoReadBytesAsync(Memory`1 buffer) in /_/src/MySqlConnector/Protocol/Serialization/SocketByteHandler.cs:line 107

**Expected behavior**
Not to timeout

**Additional context**
This started happening after upgrading the web api to .Net 6.0.  After investigating I believe the issue is related to the setting UseCompression=True in the connectionstring.  Removing this resolves the timeout.

**Comment by edwinloubser** [comment]
Also getting the following exceptions since the upgrade.

The Command Timeout expired before the operation completed.
	Exception Type: MySqlConnector.MySqlException
	Stack trace    at MySqlConnector.Protocol.Serialization.SocketByteHandler.DoReadBytesAsync(Memory`1 buffer) in /_/src/MySqlConnector/Protocol/Serialization/SocketByteHandler.cs:line 107
   at MySqlConnector.Protocol.Serialization.BufferedByteReader.ReadBytesAsync(IByteHandler byteHandler, ArraySegment`1 buffer, Int32 totalBytesToRead, IOBehavior ioBehavior) in /_/src/MySqlConnector/Protocol/Serialization/BufferedByteReader.cs:line 34
   at MySqlConnector.Utilities.ValueTaskExtensions.ContinueWith[T,TResult](ValueTask`1 valueTask, Func`2 continuation) in /_/src/MySqlConnector/Utilities/ValueTaskExtensions.cs:line 5
   at MySqlConnector.Protocol.Serialization.BufferedByteReader.ReadBytesAsync(IByteHandler byteHandler, ArraySegment`1 buffer, Int32 totalBytesToRead, IOBehavior ioBehavior) in /_/src/MySqlConnector/Protocol/Serialization/BufferedByteReader.cs:line 34
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.<ReadPacketAfterHeader>g__AddContinuation|2_0(ValueTask`1 payloadBytesTask, Int32 payloadLength, ProtocolErrorBehavior protocolErrorBehavior, Exception packetOutOfOrderException) in /_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 434
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.<DoReadPayloadAsync>g__AddContinuation|5_0(ValueTask`1 readPacketTask, BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ArraySegmentHolder`1 previousPayloads, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in /_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 480
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 910
   at MySqlConnector.Core.ResultSet.<ScanRowAsync>g__ScanRowAsyncAwaited|9_0(ResultSet resultSet, Task`1 payloadTask, Row row, CancellationToken token) in /_/src/MySqlConnector/Core/ResultSet.cs:line 252
   at MySqlConnector.Core.ResultSet.ReadAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ResultSet.cs:line 211
   at MySqlConnector.MySqlDataReader.ReadAsync(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 35

**Comment by edwinloubser** [comment]
Not entirely convinced about the UseCompression=True.  It worked in unit testing but made no difference in the actual deployed docker container on Linux.

**Comment by bgrainger** [comment]
I'm not aware of any .NET 5 vs .NET 6 differences that affect MySqlConnector. Does it take 30 seconds (or whatever you have set `CommandTimeout` / `DefaultCommandTimeout` to be) before the exception is thrown? I.e., it acts like a timeout, not just a spurious exception?

**Comment by edwinloubser** [comment]
Yes it's a proper timeout (CommandTimeout). I deployed code to time the method and it confirmed that it timed out after 30s or so.

**Comment by bgrainger** [comment]
Any chance you could capture a Wireshark/tcpdump packet capture of success (.NET 5) and timeout (.NET 6). I'm a little curious what's happening here.

**Comment by edwinloubser** [comment]
Don't have any experience using those tools, but happy to run a trace with some guidance.

**Comment by bgrainger** [comment]
On a Windows client, Wireshark has a regular installer and you can start a capture from its main screen with the filter `tcp port 3306`.

On a Linux server, you can usually install the tcpdump package (e.g., `apt-get install -y tcpdump`) then run it with `sudo tcpdump -s 65535 -w dump.pcap`. Press Ctrl+C to stop capturing, then the results will be in `dump.pcap`.

(There are likely much more detailed HOWTO articles out there.)

**Comment by edwinloubser** [comment]
I've only been able to circle back to this yesterday. I upgraded to the latest package and used the aspnet:6.0 dockerfile to test. I can confirm all went well and whatever caused this issue has been resolved.
