### ISSUE TITLE
MySqlConnector.MySqlException (0x80004005): Table './tmp/#sql1327ce_52e7492_20' doesn't exist	

### ISSUE THREAD

**Issue by premkris1988** [mysql-net/MySqlConnector#1101]
**Software versions**
MySqlConnector version:1.3.13
Server type (MySQL, MariaDB, Aurora, etc.) and version: MySql 8.0-commercial
.NET version: .net core 3.1
(Optional) ORM NuGet packages and versions: EFCore 5.0.10

**Describe the bug**
We have enabled pooling with Max Pool Size = 200 and Min Pool Size =5. ConnectionReset is given as true. Every now and then exception is logged as Table './tmp/*********** doesn't exist

**Exception**
Full exception message and call stack (if applicable)

**Code sample**

```csharp
using (var _dbContext = _dbContextFactory.CreateDbContext())
{
return (await _dbContext.DropdownModel.FromSqlRaw($@"WITH recursive UserCTE 
AS (SELECT SRC_PERSON_ID employeeId,
FIRST_NAME firstname, LAST_NAME lastname, 0 treelevel
FROM   Employeeadditionalinformation
WHERE  SRC_PERSON_ID  = '{employeeId}' AND HR_STATUS = 'A'
UNION ALL
SELECT usr.SRC_PERSON_ID employeeId,
usr.FIRST_NAME firstname, usr.LAST_NAME lastname,treelevel + 1 treelevel
FROM   Employeeadditionalinformation AS usr
INNER JOIN UserCTE AS mgr
ON usr.SUPERVISOR_ID = mgr.employeeId and usr.AGENT_IND <> 'Y' and usr.HR_STATUS = 'A' )
SELECT CONCAT(IFNULL(firstname, ''), ' ', IFNULL(lastname, ''))  Display,
employeeId Value, '' ParentCategory, '' FullName
FROM   UserCTE AS u; ")
.ToListAsync())
.OrderBy(x => x.Display)
.ToList();
}
```

**Expected behavior**
connection pooling to work properly without any error
stacktrace

```
   at MySqlConnector.Core.ResultSet.<ScanRowAsync>g__ScanRowAsyncAwaited|9_0(ResultSet resultSet, Task`1 payloadTask, Row row, CancellationToken token) in /_/src/MySqlConnector/Core/ResultSet.cs:line 245
   at MySqlConnector.Core.ResultSet.ReadAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ResultSet.cs:line 216
   at MySqlConnector.MySqlDataReader.ReadAsync(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 43
   at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at IncidentManagementSolution.Repository.EmployeeRepository.EmployeeRepository.GetAllAgentUnderSupervisorAsync(String supervisorId, Int32 opsReviewHierarchyLimit) in /src/IncidentManagementSolution/Repository/EmployeeRepository/EmployeeRepository.cs:line 69
   at IncidentManagementSolution.Services.EmployeeService.EmployeeService.GetAllAgentUnderSupervisorAsync(String employeeId) in /src/IncidentManagementSolution/Services/EmployeeService/EmployeeService.cs:line 75
   at IncidentManagementSolution.Controllers.IncidentController.GetAllAgentUnderSupervisorAsync(String supervisorId, String loggedInEmployeeId) in /src/IncidentManagementSolution/Controllers/IncidentController.cs:line 820
```

**Comment by premkris1988** [comment]
@bgrainger could you please take a look.

**Comment by bgrainger** [comment]
Based on the information provided, it seems that MySqlConnector is correctly reporting a "table does not exist" error from the server. I recommend examining your application code, looking for where a table with that name is created or used.

To reopen, please provide evidence showing that this is a bug in MySqlConnector.

**Comment by premkris1988** [comment]
@bgrainger as you can see tables like " ./tmp/#sql1327ce_52e7492_20" are generated by mysql and lifetime is limited to a connection session. what is happening/suspected is that connection session are not getting closed properly and session variables are spilling over.

**Comment by bgrainger** [comment]
`Connection Reset = True` should prevent temporary/session data from carrying over between sessions. Do you have a repro that shows that that's not the case?

Furthermore, it seems like the error message "Table './tmp/#sql1327ce_52e7492_20' doesn't exist" might imply that temporary tables are _not_ carrying over, which is the intended behaviour for `Connection Reset = True`.
