### ISSUE TITLE
The database cannot be connected,throws "Unknown command"

### ISSUE THREAD

**Issue by tianxin8206** [mysql-net/MySqlConnector#1109]
**Software versions**
MySqlConnector version:2.1.2
Server type (MySQL, MariaDB, Aurora, etc.) and version:mysql 5.6.29_ddm_3.0.3_faf321033964b24a981dc11712b9b5da50aa72fe_20210703(This is huawei cloud RDS service)
.NET version: 6

**Describe the bug**
The database cannot be connected.

**Exception**
Full exception message and call stack (if applicable)
```
MySqlConnector.MySqlException (0x80004005): Unknown command
at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 954
at MySqlConnector.Core.ServerSession.TryResetConnectionAsync(ConnectionSettings cs, MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 645
at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 65
at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 124
at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 915
at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 406
```
![image](https://user-images.githubusercontent.com/32237514/147809547-c57b725b-680c-4769-a11d-4e532c4889c1.png)

**Code sample**

```csharp
var connstr = _configuration.GetConnectionString("Dts");
using var connection = new MySqlConnection(connstr);
await connection.OpenAsync();
using var command = new MySqlCommand("select * from ss_interface_real_transducer where cs_mine_code='006070016'", connection);
using var reader = command.ExecuteReader();
```

**Expected behavior**
The same testcase,MySqlConnector is failed, but MySql.Data works!

**Comment by bgrainger** [comment]
It appears that the version of MySQL you're connecting to doesn't support the (standard) `COM_CHANGE_USER` command.

You can work around it by adding `Connection Reset = false;` to your connection string: https://mysqlconnector.net/connection-options/#ConnectionReset. Note that this will leave temporary tables and user-defined variables in-place across pooled connections, instead of clearing them.

**Comment by bgrainger** [comment]
You could also disable pooling entirely with `Pooling = False;` although that may impact performance.
