### ISSUE TITLE
Performance: SSL Stress Test throws exceptions with large number of requests

### ISSUE THREAD

**Issue by caleblloyd** [mysql-net/MySqlConnector#116]
When performance tests are run with a large number of requests and SSL is used, most of the requests end with an exception.

Test run was `./stress.sh 500 20s` with the [SSL config.json](https://github.com/mysql-net/MySqlConnector/blob/master/tests/MySqlConnector.Performance/config.json.example.ssl)

    Status Codes  [code:count]             0:6942  500:3055  200:3

    Exception:
	fail: Microsoft.AspNetCore.Server.Kestrel[13]
	      Connection id "0HKVPV0HO2R8A": An unhandled exception was thrown by the application.
	System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
	   at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
	   at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
	   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
	   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
	   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
	   at MySql.Data.Serialization.MySqlSession.<InitSslAsync>d__31.MoveNext() in /home/caleb/Projects/caleb/MySqlConnector/src/MySqlConnector/Serialization/MySqlSession.cs:line 297
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
	   at MySql.Data.Serialization.MySqlSession.<ConnectAsync>d__22.MoveNext() in /home/caleb/Projects/caleb/MySqlConnector/src/MySqlConnector/Serialization/MySqlSession.cs:line 88
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
	   at MySql.Data.MySqlClient.ConnectionPool.<GetSessionAsync>d__0.MoveNext() in /home/caleb/Projects/caleb/MySqlConnector/src/MySqlConnector/MySqlClient/ConnectionPool.cs:line 52
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
	   at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__54.MoveNext() in /home/caleb/Projects/caleb/MySqlConnector/src/MySqlConnector/MySqlClient/MySqlConnection.cs:line 220
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
	   at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__11.MoveNext() in /home/caleb/Projects/caleb/MySqlConnector/src/MySqlConnector/MySqlClient/MySqlConnection.cs:line 110
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
	   at MySqlConnector.Performance.AppDb.<OpenAsync>d__4.MoveNext() in /home/caleb/Projects/caleb/MySqlConnector/tests/MySqlConnector.Performance/AppDb.cs:line 42
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
	   at MySqlConnector.Performance.Controllers.AsyncController.<Get>d__0.MoveNext() in /home/caleb/Projects/caleb/MySqlConnector/tests/MySqlConnector.Performance/Controllers/AsyncController.cs:line 16
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()

**Comment by caleblloyd** [comment]
Performance enhancements may come in the future from https://github.com/dotnet/corefx/pull/12935
