### ISSUE TITLE
DB Error similar to: "Error submitting 21MB packet; ensure 'max_allowed_packet' is greater than 21MB." is masked by "Connection must be Open; current state is Closed"

### ISSUE THREAD

**Issue by RemmondSoftTechInc** [mysql-net/MySqlConnector#1194]
When an insert sends more than "max_allowed_packet" size of data an error is returned from MySql (AWS Aurora 5.7), this error is masked by a "Connection must be Open; current state is Closed" exception that occurs when the connection is closed/destroyed.

**Comment by bgrainger** [comment]
Can you provide the full exception call stacks for both exceptions?

**Comment by bgrainger** [comment]
I tested with the following code (using MySQL 8.0 in Docker):

```csharp
try
{
	using var connection = new MySqlConnection("server=localhost;user id=root;password=pass;database=mysqltest");
	connection.Open();
	using var command = new MySqlCommand("insert into datatypes_blobs(`LongBlob`) values(@d)", connection);
	command.Parameters.AddWithValue("@d", new byte[10_000_000]);
	command.ExecuteNonQuery();
}
catch (Exception ex)
{
	ex.ToString().Dump();
}
```

And got this exception:

```
MySqlConnector.MySqlException (0x80004005): Error submitting 20MB packet; ensure 'max_allowed_packet' is greater than 20MB.
 ---> System.IO.IOException: Unable to write data to the transport connection: An established connection was aborted by the software in your host machine..
 ---> System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslStream.WriteSingleChunk[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.Net.Security.SslStream.WriteAsyncChunked[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.Write(ReadOnlySpan`1 buffer)
   at MySqlConnector.Utilities.Utility.Write(Stream stream, ReadOnlyMemory`1 data) in C:\Code\MySql\MySqlConnector\src\MySqlConnector\Utilities\Utility.cs:line 577
   at MySqlConnector.Protocol.Serialization.StreamByteHandler.WriteBytesAsync(ReadOnlyMemory`1 data, IOBehavior ioBehavior) in C:\Code\MySql\MySqlConnector\src\MySqlConnector\Protocol\Serialization\StreamByteHandler.cs:line 95
--- End of stack trace from previous location ---
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.<WritePacketAsync>g__WritePacketAsyncAwaited|8_0(ValueTask`1 task, Byte[] buffer) in C:\Code\MySql\MySqlConnector\src\MySqlConnector\Protocol\Serialization\ProtocolUtility.cs:line 547
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.<WritePayloadAsync>g__WritePayloadAsyncAwaited|7_0(IByteHandler byteHandler, Func`1 getNextSequenceNumber, ReadOnlyMemory`1 payload, IOBehavior ioBehavior) in C:\Code\MySql\MySqlConnector\src\MySqlConnector\Protocol\Serialization\ProtocolUtility.cs:line 524
   at MySqlConnector.Core.ServerSession.SendReplyAsyncAwaited(ValueTask`1 task) in C:\Code\MySql\MySqlConnector\src\MySqlConnector\Core\ServerSession.cs:line 987
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Code\MySql\MySqlConnector\src\MySqlConnector\Core\CommandExecutor.cs:line 55
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Code\MySql\MySqlConnector\src\MySqlConnector\Core\CommandExecutor.cs:line 68
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Code\MySql\MySqlConnector\src\MySqlConnector\MySqlCommand.cs:line 296
   at MySqlConnector.MySqlCommand.ExecuteNonQuery() in C:\Code\MySql\MySqlConnector\src\MySqlConnector\MySqlCommand.cs:line 107
   at UserQuery.Main()
```

If AWS Aurora is different, I'll need to see full call stacks and repro code from your environment.
