### ISSUE TITLE
NullReferenceException in MySqlConnection.Cancel

### ISSUE THREAD

**Issue by fish-li** [mysql-net/MySqlConnector#1213]
**Software versions**
MySqlConnector version: 2.1.9
Server type (MySQL) version: 8.0.22
.NET version: 6.0
(Optional) ORM NuGet packages and versions: NONE

**Describe the bug**
Don't know why this problem arises.

**Exception**
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at MySqlConnector.MySqlConnection.Cancel(ICancellableCommand command, Int32 commandId, Boolean isCancel) in /_/src/MySqlConnector/MySqlConnection.cs:line 786
   at MySqlConnector.MySqlCommand.CancelCommandForTimeout() in /_/src/MySqlConnector/MySqlCommand.cs:line 424
   at MySqlConnector.Utilities.TimerQueue.Callback(Object obj) in /_/src/MySqlConnector/Utilities/TimerQueue.cs:line 92
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
```

**Comment by bgrainger** [comment]
This is fixed in [2.1.11](https://github.com/mysql-net/MySqlConnector/releases/tag/2.1.11).
