### ISSUE TITLE
MySqlProtocolException: "Packet received out-of-order. Expected 1; got 2" after executing BINLOG statement

### ISSUE THREAD

**Issue by sergb213** [mysql-net/MySqlConnector#1237]
**Software versions**
MySqlConnector version: 2.1.0, 2.1.13
Server type (MySQL, MariaDB, Aurora, etc.) and version: MySQL 5.7, 8.0
.NET version: net48, net6.0
(Optional) ORM NuGet packages and versions: 

**Describe the bug**
Getting "MySqlProtocolException: Packet received out-of-order. Expected 1; got 2." after executing [BINLOG](https://dev.mysql.com/doc/refman/8.0/en/binlog.html) statement. The exception is thrown by the next query which is executed on the same connection. The error only happens if the query contains multiple statements. For example, executing `BINLOG '<base64string>'; COMMIT;` causes the exception. However, executing the `COMMIT` statement as a separate command works fine.

I believe that MySqlConnector does not read the entire response in this case. Then, when the next query gets executed, it reads the last packet from the previous response, and this causes the out-of-order exception. 

Exactly the same code work totally fine with the official MySQL client. So, this is not a MySQL issue.

**Exception**
```
System.AggregateException: One or more errors occurred. (Failed to read the result set.)
 ---> MySqlConnector.MySqlException (0x80004005): Failed to read the result set.
 ---> MySqlConnector.MySqlProtocolException: Packet received out-of-order. Expected 1; got 2.
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.<ReadPacketAsync>g__AddContinuation|1_0(ValueTask`1 headerBytes, BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in /_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 423
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.<DoReadPayloadAsync>g__AddContinuation|5_0(ValueTask`1 readPacketTask, BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ArraySegmentHolder`1 previousPayloads, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in /_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 490
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 947
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 43
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 133
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 469
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 296
   at MySqlTest.MySqlConnectionExtensions.ExecuteAsync(MySqlConnection connection, String query) in D:\tmp\MySqlTest\MySqlTest\Program.cs:line 74
   at MySqlTest.MySqlConnectionExtensions.ExecuteAsync(MySqlConnection connection, String query) in D:\tmp\MySqlTest\MySqlTest\Program.cs:line 75
   at MySqlTest.Program.Run() in D:\tmp\MySqlTest\MySqlTest\Program.cs:line 54
   at MySqlTest.Program.Run() in D:\tmp\MySqlTest\MySqlTest\Program.cs:line 62
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at MySqlTest.Program.Main(String[] args) in D:\tmp\MySqlTest\MySqlTest\Program.cs:line 15
```

**Code sample**

```csharp
using System;
using System.Data;
using System.Threading.Tasks;

// switch namespace below to test with the official MySql client.
using MySqlConnector;
// using MySql.Data.MySqlClient;

namespace MySqlTest;

public static class Program
{
    public static void Main(string[] args)
    {
        Run().Wait();
    }

    private static async Task Run()
    {
        var connectionString = new MySqlConnectionStringBuilder
        {
            Server = "localhost",
            Port = 3306,
            UserID = "root",
            Password = "wordpass"
        };

        await using var connection = new MySqlConnection(connectionString.ToString());
        await connection.OpenAsync();

        await connection.ExecuteAsync(@"
CREATE SCHEMA IF NOT EXISTS protocol_test;
DROP TABLE IF EXISTS protocol_test.table_a;
CREATE TABLE protocol_test.table_a (id INT PRIMARY KEY, info VARCHAR(80) CHARSET Latin1);
SET autocommit=0;");

        await connection.ExecuteAsync(
            $@"
BINLOG '
8LNlYw8HAAAAegAAAAAAAAAAAAQAOC4wLjI5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAEwANAAgAAAAABAAEAAAAYgAEGggAAAAICAgCAAAACgoKKioAEjQACigAAXD+Vxg=
';");

        // insert into protocol_test.table_a values(1, 'record #1');
        await connection.ExecuteAsync(
            $@"
BINLOG '
vqFpYxMHAAAARAAAALYEAAAAAGgAAAAAAAEADXByb3RvY29sX3Rlc3QAB3RhYmxlX2EAAgMPAlAAAgEBAAIBCC/6kIE=
vqFpYx4HAAAAMgAAAOgEAAAAAGgAAAAAAAEAAgAC/wABAAAACXJlY29yZCAjMSa1VdU=
'; 
COMMIT;");

        // insert into protocol_test.table_a values(2, 'record #2');
        await connection.ExecuteAsync(
            $@"
BINLOG '
vqFpYxMHAAAARAAAAO4FAAAAAGgAAAAAAAEADXByb3RvY29sX3Rlc3QAB3RhYmxlX2EAAgMPAlAAAgEBAAIBCBRmx6A=
vqFpYx4HAAAAMgAAACAGAAAAAGgAAAAAAAEAAgAC/wACAAAACXJlY29yZCAjMhRNPs0=
';
COMMIT;");

        Console.WriteLine("Done");
    }
}

public static class MySqlConnectionExtensions
{
    public static async Task ExecuteAsync(this MySqlConnection connection, string query)
    {
        await using var cmd = connection.CreateCommand();
        cmd.CommandType = CommandType.Text;
        cmd.CommandText = query;
        Console.WriteLine(query);
        await cmd.ExecuteNonQueryAsync();
        Console.WriteLine("------------------ done ----------------------");
    }
}
```

**Expected behavior**
The expected behavior would be not getting the exception. 

**Additional context**
Same code works fine with the official [MySQL.Data.MySqlClient](https://www.nuget.org/packages/MySql.Data/)

**Comment by bgrainger** [comment]
Thanks for the detailed repro!

> Same code works fine with the official [MySQL.Data.MySqlClient](https://www.nuget.org/packages/MySql.Data/)

This isn't true.

To demonstrate this, add the following code to the end of `Run`:

```csharp
await using (var cmd = connection.CreateCommand())
{
	cmd.CommandText = "SELECT 1;";
	await using var reader = await cmd.ExecuteReaderAsync();
	Console.WriteLine(reader.Read());
	Console.WriteLine(reader.GetInt32(0));
}
```

The expected output is:

```
True
1
```

However, it actually prints:

```
False
ArgumentException: You have specified an invalid column ordinal.
```

This occurs because the server is sending a second OK packet (for `COMMIT`) that MySql.Data isn't reading, but leaves on the wire. When it tries to read the result set for `SELECT 1;`, instead of reading the result, it consumes the unprocessed OK packet and interprets it as an empty result set.

MySqlConnector is correctly determining that the OK packet is unexpected and throwing an exception.

The open question is whether there is any way to know that the server is sending multiple result packets. I don't see any information in the on-the-wire data that indicates that two packets are being transmitted. https://dev.mysql.com/doc/refman/8.0/en/binlog.html says:

> `BINLOG` is an internal-use statement.

There doesn't appear to be any further documentation on expected server responses.

I think if you're using internal-use statements, you need to treat them with caution. In this specific example, it seems like it is not safe to "batch" `BINLOG` with other statements. You should change your code to execute each `BINLOG` statement as a separate `MySqlCommand`, not concatenated with other `CommandText`.

**Comment by sergb213** [comment]
Yeah, I debugged it, and it looks like if I execute a batch that contains the regular `INSERT ... ; COMMIT;` statements, the first OK packet has both SERVER_STATUS_IN_TRANS | SERVER_MORE_RESULTS_EXISTS flags in the server status byte, so the connector knows that it should read the next packet.

However, with `BINLOG ...; COMMIT;` combination the first packet only has the SERVER_STATUS_IN_TRANS flag, so there is no way to know that there is the second packet.

Thus, it is MySQL to blame, not the connector. I think this issue can be closed.

**Comment by sergb213** [comment]
Found the [SERVER_MORE_RESULTS_EXISTS is not set when response multiple BINLOG statements](https://bugs.mysql.com/bug.php?id=96650) bug at MySQL. Unfortunately, it was closed.

**Comment by bgrainger** [comment]
Thanks for the link; it makes sense that someone might already have reported it as a server-side bug.
