### ISSUE TITLE
Inconsistent ROW_COUNT() behavior when hitting replica cluster via Workbench and .NET app with MySqlConnector

### ISSUE THREAD

**Issue by eric-davis** [mysql-net/MySqlConnector#1246]
**Software versions**
MySqlConnector version: 2.2.1
Server type (MySQL, MariaDB, Aurora, etc.) and version: AWS Aurora Global Database 5.7.mysql_aurora.2.10.2
.NET version: 6.0
ORM NuGet packages and versions: Microsoft Entity Framework Core 6.0.10, Pomelo.EntityFrameworkCore.MySql 6.0.2

**Describe the bug**
I am running an AWS Aurora Global MySQL Database with a primary cluster in the US and a replica cluster in the EU. The data operation in question is being executed against the replica cluster's endpoint. Write forwarding is enabled for the replica cluster.

The big picture is I have a .NET Core 6.0 application that is using Entity Framework Core and the Pomelo EF provider. When attempting to perform an operation that deletes a number of table records via a DB context, the EF concurrency check fails and rolls back the transaction. This seems to be due to the fact that in the ORM-generated SQL `SELECT ROW_COUNT()` is being used after each `DELETE` operation to check the number of affected rows and make sure the result is 1. 

```csharp
Unhandled exception Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
```

But when I attempt to mimic the SQL that EF/Pomelo generates and execute it directly via MySQL Workbench, everything works as expected.

```sql
SET @@aurora_replica_read_consistency="SESSION";
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;
DELETE FROM ApiResources WHERE ID=1;
SELECT ROW_COUNT();
DELETE FROM ApiResources WHERE ID=2;
SELECT ROW_COUNT();
DELETE FROM ApiResources WHERE ID=3;
SELECT ROW_COUNT();
DELETE FROM ApiResources WHERE ID=4;
SELECT ROW_COUNT();
DELETE FROM ApiResources WHERE ID=5;
SELECT ROW_COUNT();
```

Each of the `ROW_COUNT()` queries here return 1.

While trying to isolate the possible root causes, I also attempted to execute the same SQL directly via MySqlConnector to remove EF and Pomelo from the equation.

```csharp
using var conn = new MySqlConnection(dbConnString);
conn.Open();

using var txn = conn.BeginTransaction(IsolationLevel.ReadCommitted);

var sql = "SET @@aurora_replica_read_consistency=\"SESSION\";";
using var cmd = conn.CreateCommand();
cmd.Transaction = txn;
cmd.CommandText = sql;
cmd.ExecuteNonQuery();

sql = "DELETE FROM ApiResources WHERE ID = 1;";
sql += "SELECT ROW_COUNT();";
sql += "DELETE FROM ApiResources WHERE ID = 2;";
sql += "SELECT ROW_COUNT();";
sql += "DELETE FROM ApiResources WHERE ID = 3;";
sql += "SELECT ROW_COUNT();";
sql += "DELETE FROM ApiResources WHERE ID = 4;";
sql += "SELECT ROW_COUNT();";
sql += "DELETE FROM ApiResources WHERE ID = 5;";
sql += "SELECT ROW_COUNT();";
cmd.CommandText = sql;

var results = new List<string>();
using var reader = cmd.ExecuteReader();
do
{
	while (reader.Read())
	{
		results.Add(reader.GetValue(0).ToString());
	}
} while (reader.NextResult());
reader.Close();

if (results.All(r => r == "1"))
{
	txn.Commit();
}
else
{
	txn.Rollback();
}
```

Executing the code above yields a `ROW_COUNT()` results collection of 0,-1,-1,-1,-1.

**Exception**
```csharp
Unhandled exception
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithoutPropagation(Int32 commandIndex, RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass31_0`2.<Execute>b__0(DbContext context, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
```

**Additional context**
In addition to having write forwarding enabled for the replica cluster, I am also setting `@@aurora_replica_read_consistency` to `SESSION` for each DB connection and have the `binlog_format` parameter set to `ROW` for both clusters; have also tried `MIXED` with same results.

I have also attached Wireshark captures for both the operations performed from both the .NET app and MySQL Workbench for comparison.
[captures.zip](https://github.com/mysql-net/MySqlConnector/files/10142265/captures.zip)

**Comment by mguinness** [comment]
I had a cursory look at the captures and I noticed that the comparison isn't quite the same - Workbench sends each statement separately whereas your example in MySqlConnector sends them as one batch.  Does Workbench allow you to send it batched?  If not, you could try try [HeidiSQL ](https://www.heidisql.com/) and change Execute SQL from "Send queries one by one" to "Send batch in one go" and see what results you get.

**Comment by mguinness** [comment]
Also wanted to mention that you're using Aurora 2, do you have the ability to test against Aurora 3 to see if the issue persists?

**Comment by bgrainger** [comment]
I see the same thing as @mguinness: Aurora is returning 0, -1, -1, -1, -1 and MySqlConnector is correctly reporting the values sent by the server.

Does Aurora return the expected output if you split the ADO.NET test code up into sending multiple statements instead of one batch?

```csharp
using var txn = conn.BeginTransaction(System.Data.IsolationLevel.ReadCommitted);

var results = new List<string>();
for (int i = 1; i <= 5; i++)
{
	using var cmd = conn.CreateCommand();
	cmd.Transaction = txn;
	cmd.CommandText = $"DELETE FROM ApiResources WHERE ID = {i};";
	cmd.ExecuteNonQuery();
	
	cmd.CommandText = "SELECT ROW_COUNT();";
	using var reader = cmd.ExecuteReader();
	while (reader.Read())
	{
		results.Add(reader.GetValue(0).ToString());
	}
}

if (results.All(r => r == "1"))
{
	txn.Commit();
}
else
{
	txn.Rollback();
}
```

**Comment by ericjpeters** [comment]
I don't know if this helps or not...   But I recently upgraded from .NET 6 to .NET 7 - including an upgrade from EF and Pomelo v6 to v7.   This process upgraded MySqlConnector to 2.2.0.   I know that is several variables I need to consider -- I'm actively trying to determine the root cause right now.

In any case, that upgrade (no applicable code or infrastructure changes) caused previously working code to raise DbUpdateConcurrencyException exactly as described in this issue.   

I'm using AWS/RDS Aurora with a MySql v5.x backend, connecting via an AWS/RDS Proxy with pooled connections.   Locally, without the proxy, hitting MySql v8.x works fine.

The only workaround I've found so far is to wrap the breaking code in a transaction with repeatable-read isolation, which seems to "fix" the issue.

I'll follow-up if I find anything else.   But I'm hoping this early information might also help others in their research.

**Comment by bgrainger** [comment]
I don't _think_ this is related, yet, but mentioning it just in case. 

There was a change in MySqlConnector 2.1.3 to change the return value from `MySqlCommand.ExecuteNonQuery` (which is the number of affected records) to fix a bug in how it was calculated: https://github.com/mysql-net/MySqlConnector/issues/1096. This caused some problems for Pomelo: https://github.com/mysql-net/MySqlConnector/issues/1136. Unfortunately (as detailed in that issue) due to the design of the MySQL protocol there is no (general) way to distinguish between sprocs that just execute a `SELECT` and sprocs that change data.

The OP is executing SQL that explicitly calls `SELECT ROW_COUNT();` so that would _not_ be affected by changes for the two bugs linked above. (There are also no sprocs in this repro.)

So far, the problem appears to be on Aurora's end: it is returning unexpected data for the results of a `SELECT` operation and MySqlConnector is reporting those values as-is.

However, it seems like there must also be a client-side change if EF6 code is working fine. Perhaps the change is in EF7 which (IIRC) now adds more batched operations? (Or maybe that requires opting in via `ExecuteDeleteAsync` so it wouldn't simply happen just by updating to EF7?)

Are you able to capture the SQL that is sent with both EF6 and EF7 to understand if the client is now sending different SQL, which might be handled differently by Aurora, or if the client is sending the same SQL but perhaps the response is being interpreted differently?

**Comment by mguinness** [comment]
@ericjpeters Thanks for the update and for mentioning that [AutoTransactionBehavior](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.databasefacade.autotransactionbehavior) replaces [AutoTransactionsEnabled](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.databasefacade.autotransactionsenabled) in EF Core 7.  Linking this issue to https://github.com/dotnet/efcore/issues/29785 for completeness.  Also are you able to reproduce the issue reported by OP using their sample ADO,NET code directly with Aurora and through the RDS proxy?  It might impact the value returned by `ROW_COUNT()`.

**Comment by bgrainger** [comment]
Is this issue essentially a duplicate of https://github.com/dotnet/efcore/issues/29785? I don't think there's any change needed in MySqlConnector to address the issue (nor can I imagine how MySqlConnector _could_ address it).

**Comment by mguinness** [comment]
> I just did their ASP.NET code against a local MySql instance, an AWS Aurora/MySql instance, and an AWS Aurora/MySql instance via an AWS RDS Proxy. All 3 tests behaved exactly as expected (returns 5 0's, no exception).

Thanks for running those tests.  Was the AWS Aurora/MySql instance 3.x?  Are you able to run the test against Aurora 2.x as well?

**Comment by ericjpeters** [comment]
> > I just did their ASP.NET code against a local MySql instance, an AWS Aurora/MySql instance, and an AWS Aurora/MySql instance via an AWS RDS Proxy. All 3 tests behaved exactly as expected (returns 5 0's, no exception).
> 
> Thanks for running those tests. Was the AWS Aurora/MySql instance 3.x? Are you able to run the test against Aurora 2.x as well?

I was 2.x - I no longer have a 3.x instance running in AWS.  Locally was against MySql 8.0.

**Comment by eric-davis** [comment]
This is looking more and more like an Aurora issue. I upgraded my DB clusters from Aurora ver. 2 to ver. 3 (8.0.mysql_aurora.3.02.0). I also took the advice from @mguinness and sent the SQL script as a batch directly from HeidiSQL and get an error: "SQL Error(63976) in statement #8: Internal write forwarding error". Obviously, that message is less than helpful...

I have an open support ticket with AWS, but they haven't exactly been helpful so far. :-(

USE mydb;
SET @@aurora_replica_read_consistency="SESSION";
START TRANSACTION;
DELETE FROM ApiResources WHERE ID=1;
SELECT ROW_COUNT();
DELETE FROM ApiResources WHERE ID=2;
SELECT ROW_COUNT();
DELETE FROM ApiResources WHERE ID=3;
SELECT ROW_COUNT();
DELETE FROM ApiResources WHERE ID=4;
SELECT ROW_COUNT();
DELETE FROM ApiResources WHERE ID=5;
SELECT ROW_COUNT();
ROLLBACK;
