### ISSUE TITLE
Throwing NullReferenceException when passing null parameter value to Query (MySqlParameter)

### ISSUE THREAD

**Issue by alanprot** [mysql-net/MySqlConnector#126]
To reproduce :

```
const string query = "select Col1 from Table1 where @parameter is null OR Col2 = @parameter";

using (var cmd = new MySqlCommand(query, con))
{
	cmd.Parameters.Add(new MySqlParameter() { ParameterName = "@parameter", Value = null });
	await cmd.ExecuteNonQueryAsync(cancellationToken);
}
```

Stack Trace:

```
at System.Object.GetType()
   at MySql.Data.MySqlClient.MySqlParameter.AppendSqlString(BinaryWriter writer, StatementPreparerOptions options)
   at MySql.Data.MySqlClient.MySqlStatementPreparer.ParameterSqlParser.DoAppendParameter(Int32 parameterIndex, Int32 textIndex, Int32 textLength)
   at MySql.Data.MySqlClient.MySqlParser.Parse(String sql)
   at MySql.Data.MySqlClient.MySqlStatementPreparer.ParseAndBindParameters()
   at MySql.Data.MySqlClient.MySqlCommand.<ExecuteReaderAsync>d__50.MoveNext()
```

**Comment by bgrainger** [comment]
Fixed in [0.6.2](https://www.nuget.org/packages/MySqlConnector/0.6.2).
