### ISSUE TITLE
ConnectionPool code contains race condition

### ISSUE THREAD

**Issue by eranikid** [mysql-net/MySqlConnector#1263]
ConnectionPool code contains race condition around the `RecoverLeakedSessionsAsync` functionality. This has two main consequences:
1. The `m_sessions` linked list might end up containing the same session twice. Which then leads to that session being contained in both `m_sessions` and `m_leasedSessions`. Which in turn leads to the `GetSessionAsync` call failing with a wierd-looking exception
2. The `m_leasedSessions` dictionary might contain more sessions than the value of `CurrentCount` property of the `m_sessionSemaphore`, thus exceeding the configured `MaximumPoolSize`

This race condition occurs if two different threads concurrently enter `RecoverLeakedSessionsAsync`.

This can be encountered, for instance, when:
1. Both threads evaluate the condition `unchecked(((uint) Environment.TickCount) - m_lastRecoveryTime) >= 1000u` as `true`, both enter the method `RecoverLeakedSessionsAsync`. First one to enter the critical section finds all the leaked sessions wihthout `OwningConnection`, and after leaving the critical section starts to recover them one-by-one. When the second thread enters the critical section, some the leaked sessions found by first thread are very likely to still be in the `m_leasedSessions`, thus they are also found by the second thread, which means that now both threads will attempt to recover the same session
2. Thread that entered `RecoverLeakedSessionsAsync` has paused (due to long GC-pause/network latency/thread-pool starvation/you name it) for more than 1 second somewhere between leaving the critical section and recovering the last leaked session. In this case, after 1 second passes, another thread will be able to also enter the `RecoverLeakedSessionsAsync` method and see some of 1st thread's leaked sessions in `m_leasedSessions`

In both cases, `ReturnAsync` is called twice for the same session. This means that:
- `m_leasedSessions.Remove(session.Id)` is invoked twice, which is fine, because the second invocation will just be a no-op
- `m_sessions.AddFirst(session)` is invoked twice, which is our first issue
- `m_sessionSemaphore.Release()` is invoked twice, which is our second issue

This might be related to https://github.com/mysql-net/MySqlConnector/issues/841. https://github.com/mysql-net/MySqlConnector/issues/305 might also be related, though I'm not sure

We encountered this in our production environment - I first thought that I was out of my mind when I saw MySqlConnector reporting 120 connections in the pool, given we use the default value of 100 for `MaximumPoolSize`, but after collecting some more diagnostics, this issue became apparent. It happens only when there is a connection leak (which we had). And though it does not lead to any significant issues, besides having a couple excess connections and some unclear exceptions every now and then, I still think that it is worth fixing.

As for the fix, I see three options. Ranged from the sipmlest to the most complex they are:

- In `ReturnAsync` we check if `m_leasedSessions.Remove(session.Id)` actually deleted something. If it didn't delete anything, we just return. The downside of this option is that `ReturnAsync` going to still be invoked twice, the second invocation being a noop. In fact, I have prepared a PR https://github.com/mysql-net/MySqlConnector/pull/1262, implementing this option
- In `RecoverLeakedSessionsAsync` we remove the leaked sessions from `m_leasedSessions` without leaving the critical section, so any successive calls to that method won't observe any of them. The downside of this option is that if anything goes wrong when disposing those connections, the dispose won't be retried, and they're gone for good
- In `RecoverLeakedSessionsAsync` method, we put leaked sessions into some separate collection, designated specifically to be holding sessions to be recovered

**Comment by bgrainger** [comment]
Thanks for the detailed write-up!

> The downside of this option is that `ReturnAsync` going to still be invoked twice, the second invocation being a noop.

I'm reluctant to implement this for essentially the reason you mentioned: it doesn't fix the race condition, and we now have more complicated code in `ReturnAsync` that assumes it's going to be called incorrectly.

I think there may be a solution that avoids all these problems:

* In `RecoverLeakedSessionsAsync`, inside the lock, set each session's `OwningConnection` to a new `MySqlConnection`, which is held in a local `List`. Now, if another thread runs concurrently, it will see that each session is owned, and ignore it.
* Outside the lock, dispose all the MySqlConnection objects. This will return the sessions to the pool.
* If something goes wrong, the temporary MySqlConnection objects will be GCed, and the process will be restarted by a different thread.

**Comment by bgrainger** [comment]
(I'll take a stab at implementing my idea.)

**Comment by bgrainger** [comment]
Exceptions that I noted when reproducing the problem (before the fix):

```
[DEBUG]  ConnectionPool  Pool1 disposing created Session1.6 due to exception: Index was outside the bounds of the array.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MySqlConnector.Protocol.PayloadData.get_HeaderByte() in C:\_\MySqlConnector\src\MySqlConnector\Protocol\PayloadData.cs:line 18
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\_\MySqlConnector\src\MySqlConnector\Core\ServerSession.cs:line 936
   at MySqlConnector.Core.ServerSession.TryResetConnectionAsync(ConnectionSettings cs, MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\_\MySqlConnector\src\MySqlConnector\Core\ServerSession.cs:line 633
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\_\MySqlConnector\src\MySqlConnector\Core\ConnectionPool.cs:line 68
```

```
[DEBUG]  ServerSession  Session1.9 setting state to Failed
System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
   at System.Net.Sockets.Socket.Receive(Span`1 buffer, SocketFlags socketFlags)
   at MySqlConnector.Protocol.Serialization.SocketByteHandler.DoReadBytesSync(Memory`1 buffer) in C:\_\MySqlConnector\src\MySqlConnector\Protocol\Serialization\SocketByteHandler.cs:line 44
--- End of stack trace from previous location ---
   at MySqlConnector.Protocol.Serialization.BufferedByteReader.ReadBytesAsync(IByteHandler byteHandler, ArraySegment`1 buffer, Int32 totalBytesToRead, IOBehavior ioBehavior) in C:\_\MySqlConnector\src\MySqlConnector\Protocol\Serialization\BufferedByteReader.cs:line 34
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.<ReadPacketAfterHeader>g__AddContinuation|2_0(ValueTask`1 payloadBytesTask, Int32 payloadLength, ProtocolErrorBehavior protocolErrorBehavior, Exception packetOutOfOrderException) in C:\_\MySqlConnector\src\MySqlConnector\Protocol\Serialization\ProtocolUtility.cs:line 448
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.<DoReadPayloadAsync>g__AddContinuation|5_0(ValueTask`1 readPacketTask, BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ArraySegmentHolder`1 previousPayloads, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in C:\_\MySqlConnector\src\MySqlConnector\Protocol\Serialization\ProtocolUtility.cs:line 494
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in C:\_\MySqlConnector\src\MySqlConnector\Core\ServerSession.cs:line 951
```

Likely the cause of https://github.com/mysql-net/MySqlConnector/issues/1245:

```
[DEBUG]  ConnectionPool  Pool1 disposing created Session1.8 due to exception: An item with the same key has already been added. Key: 1.8
System.ArgumentException: An item with the same key has already been added. Key: 1.8
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\_\MySqlConnector\src\MySqlConnector\Core\ConnectionPool.cs:line 87
```

```
[DEBUG]  ConnectionPool  Pool1 disposing created Session1.6 due to exception: Expected state to be Connected but was Closed.
System.InvalidOperationException: Expected state to be Connected but was Closed.
   at MySqlConnector.Core.ServerSession.VerifyState(State state) in C:\_\MySqlConnector\src\MySqlConnector\Core\ServerSession.cs:line 1796
   at MySqlConnector.Core.ServerSession.TryResetConnectionAsync(ConnectionSettings cs, MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\_\MySqlConnector\src\MySqlConnector\Core\ServerSession.cs:line 608
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\_\MySqlConnector\src\MySqlConnector\Core\ConnectionPool.cs:line 68
```

```
[DEBUG]  ServerSession  Session5.10 setting state to Failed
MySqlConnector.MySqlProtocolException: Packet received out-of-order. Expected 2; got 1.
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.<DoReadPayloadAsync>g__AddContinuation|5_0(ValueTask`1 readPacketTask, BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ArraySegmentHolder`1 previousPayloads, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in C:\_\MySqlConnector\src\MySqlConnector\Protocol\Serialization\ProtocolUtility.cs:line 494
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in C:\_\MySqlConnector\src\MySqlConnector\Core\ServerSession.cs:line 951
```

```
[DEBUG]  ConnectionPool  Pool5 disposing created Session5.7 due to exception: Packet received out-of-order. Expected 2; got 1.
MySqlConnector.MySqlProtocolException: Packet received out-of-order. Expected 2; got 1.
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.<DoReadPayloadAsync>g__AddContinuation|5_0(ValueTask`1 readPacketTask, BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ArraySegmentHolder`1 previousPayloads, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in C:\_\MySqlConnector\src\MySqlConnector\Protocol\Serialization\ProtocolUtility.cs:line 494
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in C:\_\MySqlConnector\src\MySqlConnector\Core\ServerSession.cs:line 951
   at MySqlConnector.Core.ServerSession.TryResetConnectionAsync(ConnectionSettings cs, MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\_\MySqlConnector\src\MySqlConnector\Core\ServerSession.cs:line 633
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\_\MySqlConnector\src\MySqlConnector\Core\ConnectionPool.cs:line 68
```

**Comment by eranikid** [comment]
I think your idea is great! Thanks a lot for the fix, and thanks a lot for maintaining this connector.

I also should've shared the exceptions we've been observing in production in the OP post, so you could have a reference while doing your own debugging. I'll share them now:

We had the diagnostics code together with the the leak in production for around 40 minutes (the time it took us to realize we have a leak and deploy a fix). During that time, 72 `Pool{0} disposing created Session{1} due to exception: {2}` events have occured.

<details><summary>Exception details</summary>

- 55 of them were 
```
System.ArgumentException: Pool1 disposing created Session1.36 due to exception: An item with the same key has already been added. Key: 1.36
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ConnectionPool.cs:line 129
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ConnectionPool.cs:line 129
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\MySqlConnection.cs:line 952
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\MySqlConnection.cs:line 456
```
- 7 of them were
```
System.NotSupportedException: Pool1 disposing created Session1.53 due to exception: The ReadAsync method cannot be called when another read operation is pending.
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at MySqlConnector.Protocol.Serialization.StreamByteHandler.<ReadBytesAsync>g__DoReadBytesAsync|6_2(Memory`1 buffer) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Protocol\Serialization\StreamByteHandler.cs:line 85
   at MySqlConnector.Protocol.Serialization.BufferedByteReader.ReadBytesAsync(IByteHandler byteHandler, ArraySegment`1 buffer, Int32 totalBytesToRead, IOBehavior ioBehavior) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Protocol\Serialization\BufferedByteReader.cs:line 53
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.<ReadPacketAsync>g__AddContinuation|1_0(ValueTask`1 headerBytes, BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Protocol\Serialization\ProtocolUtility.cs:line 423
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.<DoReadPayloadAsync>g__AddContinuation|5_0(ValueTask`1 readPacketTask, BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ArraySegmentHolder`1 previousPayloads, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Protocol\Serialization\ProtocolUtility.cs:line 498
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ServerSession.cs:line 964
   at MySqlConnector.Core.ServerSession.TryResetConnectionAsync(ConnectionSettings cs, MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ServerSession.cs:line 696
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ConnectionPool.cs:line 129
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ConnectionPool.cs:line 129
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\MySqlConnection.cs:line 952
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\MySqlConnection.cs:line 456
```
- 4 of them were
```
System.InvalidOperationException: Pool1 disposing created Session1.73 due to exception: Expected state to be Connected but was Querying.
   at MySqlConnector.Core.ServerSession.VerifyState(State state) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ServerSession.cs:line 1794
   at MySqlConnector.Core.ServerSession.TryResetConnectionAsync(ConnectionSettings cs, MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ServerSession.cs:line 696
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ConnectionPool.cs:line 129
```
- 2 of them were (these are probably unrelated to the issue and are legit timeouts)
```
MySqlConnector.MySqlException: Pool1 disposing created Session1.99 due to exception: The Command Timeout expired before the operation completed.
   at MySqlConnector.Protocol.Serialization.StreamByteHandler.<ReadBytesAsync>g__DoReadBytesAsync|6_2(Memory`1 buffer) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Protocol\Serialization\StreamByteHandler.cs:line 85
   at MySqlConnector.Protocol.Serialization.BufferedByteReader.ReadBytesAsync(IByteHandler byteHandler, ArraySegment`1 buffer, Int32 totalBytesToRead, IOBehavior ioBehavior) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Protocol\Serialization\BufferedByteReader.cs:line 53
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.<ReadPacketAsync>g__AddContinuation|1_0(ValueTask`1 headerBytes, BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Protocol\Serialization\ProtocolUtility.cs:line 423
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.<DoReadPayloadAsync>g__AddContinuation|5_0(ValueTask`1 readPacketTask, BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ArraySegmentHolder`1 previousPayloads, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Protocol\Serialization\ProtocolUtility.cs:line 498
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ServerSession.cs:line 964
   at MySqlConnector.Core.ServerSession.TryResetConnectionAsync(ConnectionSettings cs, MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ServerSession.cs:line 696
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ConnectionPool.cs:line 129
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ConnectionPool.cs:line 129
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\MySqlConnection.cs:line 952
```

- 2 of them were
```
System.NotSupportedException: Pool1 disposing created Session1.75 due to exception: The WriteAsync method cannot be called when another write operation is pending.
   at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at MySqlConnector.Protocol.Serialization.StreamByteHandler.<WriteBytesAsync>g__DoWriteBytesAsync|7_0(ReadOnlyMemory`1 data) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Protocol\Serialization\StreamByteHandler.cs:line 104
   at MySqlConnector.Core.ServerSession.TryResetConnectionAsync(ConnectionSettings cs, MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ServerSession.cs:line 696
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ConnectionPool.cs:line 129
```

- 1 was (this one is probably unrelated to the issue and is a legit timeout)
```
MySqlConnector.MySqlException: Pool1 disposing created Session1.372 due to exception: Connect Timeout expired.
   at MySqlConnector.Core.ServerSession.OpenTcpSocketAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ServerSession.cs:line 1185
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int32 startTickCount, ILoadBalancer loadBalancer, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ServerSession.cs:line 604
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ConnectionPool.cs:line 445
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ConnectionPool.cs:line 129
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ConnectionPool.cs:line 129
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\MySqlConnection.cs:line 952
```

- 1 was
```
System.InvalidOperationException: Pool1 disposing created Session1.59 due to exception: ServerSession is not connected.
   at MySqlConnector.Core.ServerSession.VerifyConnected() in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ServerSession.cs:line 1027
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ServerSession.cs:line 939
--- End of stack trace from previous location ---
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ServerSession.cs:line 964
   at MySqlConnector.Core.ServerSession.TryResetConnectionAsync(ConnectionSettings cs, MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ServerSession.cs:line 696
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ConnectionPool.cs:line 129
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\Core\ConnectionPool.cs:line 129
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\MySqlConnection.cs:line 952
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\Users\user\src\MySqlConnector\src\MySqlConnector\MySqlConnection.cs:line 456
```
</details>

**Comment by bgrainger** [comment]
Fixed in [2.2.4](https://github.com/mysql-net/MySqlConnector/releases/tag/2.2.4).

**Comment by mjanulaitis** [comment]
I just upgraded from 8.0.32 to 8.1.0 and now I am seeing this bug.  I'm rolling back to the previous version which I never experienced this bug with.  I'm now sure where you are seeing version 2.2.4.  NuGet shows the latest is 8.1.0.

**Comment by bgrainger** [comment]
@mjanulaitis This is the repo for [MySqlConnector](https://www.nuget.org/packages/MySqlConnector/), which is currently at version 2.2.7.

If you're using [MySql.Data 8.1.0](https://www.nuget.org/packages/MySql.Data/), the correct repo is https://github.com/mysql/mysql-connector-net/ and bugs should be reported at https://bugs.mysql.com/.
