### ISSUE TITLE
MySqlDataReader throwing NullReferenceException and InvalidOperationException

### ISSUE THREAD

**Issue by jeremyliuu** [mysql-net/MySqlConnector#1319]
**Software versions**
MySqlConnector version: 2.3.0 beta 2
Server type (MySQL, MariaDB, Aurora, etc.) and version: 8.0.21
.NET version: 6

**Describe the bug**
MySqlDataReader throws NullReferenceException and InvalidOperationException occasionally during high traffic time in application.

**Exception**
```
System.InvalidOperationException: Can't replace active reader.
   at MySqlConnector.MySqlConnection.SetActiveReader(MySqlDataReader dataReader) in /src/MySqlConnector/MySqlConnection.cs:line 872
   at MySqlConnector.MySqlDataReader.InitAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /src/MySqlConnector/MySqlDataReader.cs:line 482
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /src/MySqlConnector/MySqlCommand.cs:line 344
   at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /src/MySqlConnector/MySqlCommand.cs:line 336
```
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /src/MySqlConnector/MySqlDataReader.cs:line 137
   at MySqlConnector.MySqlDataReader.InitAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /src/MySqlConnector/MySqlDataReader.cs:line 487
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /src/MySqlConnector/MySqlCommand.cs:line 344
   at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /src/MySqlConnector/MySqlCommand.cs:line 336
```

**Comment by bgrainger** [comment]
Is it possible that your code is executing two commands simultaneously on the same connection? Or has a race condition that sometimes makes that possible under heavy load?

That kind of usage is not permitted by the library: https://mysqlconnector.net/troubleshooting/connection-reuse/

**Comment by jeremyliuu** [comment]
Thanks for the quick response. We don't have that kind of usage, here is the sudo-code sample from our code, it's one command per connection
```
using var conn = new MySqlConnection();
var result = await conn.QueryAsync();
```
Also we are using Dapper as our framework

**Comment by bgrainger** [comment]
Are you able to provide a complete callstack, or logging around the time of the exception (ideally at `Trace` level)?

**Comment by jeremyliuu** [comment]
Sure, here is a full trace
```
System.InvalidOperationException: Can't replace active reader.
   at MySqlConnector.MySqlConnection.SetActiveReader(MySqlDataReader dataReader) in /src/MySqlConnector/MySqlConnection.cs:line 872
   at MySqlConnector.MySqlDataReader.InitAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /src/MySqlConnector/MySqlDataReader.cs:line 482
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /src/MySqlConnector/MySqlCommand.cs:line 344
   at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /src/MySqlConnector/MySqlCommand.cs:line 336
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 418
   at Company.Lib.AspNetCore.Root.Sql.DapperMetrics.RunWithTimerAsync[T](IDbConnection cn, Func`1 func, String sqlStatement, String callerName, String callerFilePath, Int32 callerLineNo, String methodName) in /AspNetCoreRoot/Company.Lib.AspNetCore.Root/Sql/DapperMetrics.cs:line 519
   at Company.Lib.AspNetCore.Root.Sql.DapperMetrics.MQueryAsync[T](IDbConnection cn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType, String callerName, String callerFilePath, Int32 callerLineNo) in /AspNetCoreRoot/Company.Lib.AspNetCore.Root/Sql/DapperMetrics.cs:line 142
   at MyCompany.MyApp.Helper.DbConn.QueryAsync[T](String sql, Object parameters, String callerName, String callerFilePath, Int32 callerLineNo) in /app/MyCompany.MyApp/Helper/DbConn.cs:line 76
   at MyCompany.MyApp.Manager.ManagerRepo.Get(String key) in /app/MyCompany.MyApp/Manager/ManagerRepo.cs:line 337
   at MyCompany.MyApp.Manager.ManagerRepo.Get(String key) in /app/MyCompany.MyApp/Manager/ManagerRepo.cs:line 320
   at MyCompany.MyApp.Controllers.Controller.Get(String key) in /app/MyCompany.MyApp/Controllers/Controller.cs:line 75
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   ```
And besides two errors mentioned above, we noticed another one:
```
MySqlConnector.MySqlProtocolException: Packet received out-of-order. Expected 1; got 2.
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.<DoReadPayloadAsync>g__AddContinuation|5_0(ValueTask`1 readPacketTask, BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ArraySegmentHolder`1 previousPayloads, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in /src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 498
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /src/MySqlConnector/Core/ServerSession.cs:line 964
   at MySqlConnector.Core.ServerSession.TryResetConnectionAsync(ConnectionSettings cs, MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in /src/MySqlConnector/Core/ServerSession.cs:line 699
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /src/MySqlConnector/Core/ConnectionPool.cs:line 129
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /src/MySqlConnector/Core/ConnectionPool.cs:line 129
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /src/MySqlConnector/MySqlConnection.cs:line 954
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /src/MySqlConnector/MySqlConnection.cs:line 461
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 417
```

Also, some details I forgot to mentioned: we were on 1.4.0.beta.3 and there was no issue. Issue started after we upgraded to 2.3.0 beta 2. And now issue is gone after we downgraded to 2.2.5

**Comment by bgrainger** [comment]
> Issue started after we upgraded to 2.3.0 beta 2. And now issue is gone after we downgraded to 2.2.5

That's helpful information; thanks.

```
   at MyCompany.MyApp.Helper.DbConn.QueryAsync[T](String sql, Object parameters, String callerName, String callerFilePath, Int32 callerLineNo) in /app/MyCompany.MyApp/Helper/DbConn.cs:line 76
   at MyCompany.MyApp.Manager.ManagerRepo.Get(String key) in /app/MyCompany.MyApp/Manager/ManagerRepo.cs:line 337
   at MyCompany.MyApp.Manager.ManagerRepo.Get(String key) in /app/MyCompany.MyApp/Manager/ManagerRepo.cs:line 320
```

Just checking: none of this code uses `static` data (particularly a `MySqlConnection`) that might be shared across threads, correct? These are all new instances that are created per-request?

**Comment by jeremyliuu** [comment]
yes that's correct, we are not using static for those methods.

**Comment by bgrainger** [comment]
How does `Company.Lib.AspNetCore.Root.Sql.DapperMetrics.MQueryAsync` create/obtain the `MySqlConnection` that it uses?

**Comment by jeremyliuu** [comment]
MQueryAsync is just a wrapper that instruments the latency of the Dapper QueryAsync method. Doesn't do anything else.

**Comment by bgrainger** [comment]
Wrong question, perhaps. How does `MyCompany.MyApp.Helper.DbConn.QueryAsync` get/acquire the `MySqlConnection` / `DbConnection` / `IDbConnection` that `MQueryAsync` is invoked on?

**Comment by jeremyliuu** [comment]
DbConn is another wrapper around MySqlConnection, it initializes a new MySqlConnection in the constructor as an internal property `_conn`, and `DbConn.QueryAsync` wraps `MQueryAsync` in a try, and if exception is thrown, it catches and updates the `_conn.ConnectionString` with a different connection string that points to a different replica node. Could that be causing the issue somehow? With previous versions of MySqlConnector, we didn't see this issue.

**Comment by bgrainger** [comment]
While doing local development, I introduced a bug that threw an exception in `MySqlDataReader`. Continuing to use that same `MySqlConnection` object threw `InvalidOperationException: This MySqlConnection is already in use.` or `InvalidOperationException: Can't replace active reader.` from previously working code.

So one potential explanation here is that you have a `MySqlConnection` that's already experienced some sort of failure, and continuing to use it isn't possible. Do you have any code that catches and ignores an exception? Do you have a different exception that's being logged first, before these other ones start happening?
