### ISSUE TITLE
Expected to read 4 header bytes but only received 0.

### ISSUE THREAD

**Issue by pwhsoft** [mysql-net/MySqlConnector#1340]
**Software versions**
MySqlConnector version: 2.2.5
Server type (MariaDB) and version: 10.7
.NET version: net6

**Describe the bug**
From time to time this error occurs. I don’t know why and I cannot reproduce it but it is critical. I am using a galera cluster. 

**Exception**
MySqlConnector.MySqlException (0x80004005): Failed to read the result set.
 ---> System.IO.EndOfStreamException: Expected to read 4 header bytes but only received 0.
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.<DoReadPayloadAsync>g__AddContinuation|5_0(ValueTask`1 readPacketTask, BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ArraySegmentHolder`1 previousPayloads, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in /_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 498
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 964
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 43
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 137
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 468
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 345
   at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 337
   …..

**Code sample**

Irrelevant - it happens with different queries. From simple up to complex queries. 

**Expected behavior**
Retry on exception

**Additional context**

**Comment by bgrainger** [comment]
> Expected to read 4 header bytes but only received 0.

This usually means the server stopped sending data. Try checking your server logs to see if there are any errors about aborted clients.

> Expected behavior
> Retry on exception

MySqlConnector is a "low level" library and doesn't implement any retry policies. Polly is a popular way to implement retry policies (according to your app's particular needs), and works well with MySqlConnector. https://github.com/App-vNext/Polly#usage--fault-handling-reactive-policies

**Comment by jkuek** [comment]
I don't know if this is the OP's problem, but I have seen this before when connecting to AWS Aurora when the server requires SSL and I don't have it enabled in the connection string.
