### ISSUE TITLE
Fail to make query concurrently (MysqlConnector 8.1)

### ISSUE THREAD

**Issue by jsnhsu** [mysql-net/MySqlConnector#1357]
**Software versions**
MySqlConnector version: 8.1
Server type (MySQL, MariaDB, Aurora, etc.) and version: MySQL Community 8.0.28
.NET version: 7.0
(Optional) ORM NuGet packages and versions: 6.7

**Describe the bug**
I have 5 async functions that send one simple SELECT query to tables within the same database (identical connection string) like the one below. They together were working perfectly with mysql driver 8.0.32.1, 8.0.33. But today after I upgraded the driver to 8.1 without changing any code, an exception occurs like:

**Exception**
2023-08-25 15:06:59.163 [ERR] Fail to list Station Patterns
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at MySql.Data.Common.Ssl.StartSSLAsync(Stream baseStream, Encoding encoding, String connectionString, CancellationToken cancellationToken, Boolean execAsync)
   at MySql.Data.MySqlClient.NativeDriver.OpenAsync(Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.Driver.OpenAsync(Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.Driver.CreateAsync(MySqlConnectionStringBuilder settings, Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.Driver.CreateAsync(MySqlConnectionStringBuilder settings, Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnectionAsync(Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnectionAsync(Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriverAsync(Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.MySqlPool.GetConnectionAsync(Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Boolean execAsync, CancellationToken cancellationToken)
   at qt.dms.xmlchecker.Helper.QaTarConfigHelper.GetStationPatternsAsync(CancellationToken token) in D:\Projects\Personal\AutoDeploySolution\qt.dms.xmlchecker\Helper\QaTarConfigHelper.cs:line 85
2023-08-25 15:06:59.431 [ERR] Fail to list Board Patterns
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at MySql.Data.Common.Ssl.StartSSLAsync(Stream baseStream, Encoding encoding, String connectionString, CancellationToken cancellationToken, Boolean execAsync)
   at MySql.Data.MySqlClient.NativeDriver.OpenAsync(Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.Driver.OpenAsync(Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.Driver.CreateAsync(MySqlConnectionStringBuilder settings, Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.Driver.CreateAsync(MySqlConnectionStringBuilder settings, Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnectionAsync(Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnectionAsync(Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriverAsync(Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.MySqlPool.GetConnectionAsync(Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Boolean execAsync, CancellationToken cancellationToken)
   at qt.dms.xmlchecker.Helper.QaTarConfigHelper.GetBoardPatternsAsync(CancellationToken token) in D:\Projects\Personal\AutoDeploySolution\qt.dms.xmlchecker\Helper\QaTarConfigHelper.cs:line 61

**Code sample**

```csharp
public async Task<List<AA>> GetAAsync(string productName, CancellationToken token = default(CancellationToken))
{
	var result = new List<AA>();

	try
	{
		using (MySqlConnection conn = new MySqlConnection(this._option.connStr))
		{
			if (conn.State == ConnectionState.Closed)
				await conn.OpenAsync(token);

			var sql0 = $"Select * From AA;";
			
			var t0 = conn.QueryAsync<AA>(sql0);

			Task.WaitAll(t0);

			result.AddRange(t0.Result.ToList());
		}
	}
	catch (Exception exc)
	{
		this._log.Error(exc, $"Fail to list data");
	}
	return result;
}

// Main:
Task t0 = GetAAsync();
Task t1 = GetBBsync();
Task t2 = GetCCsync();
...
Task.WaitAll(t0, t1, t2, ....);

var r0 = t0.Result;
var r1 = t1.Result;
var r2 = t2.Result;
....
```

**Expected behavior**
I expected the driver supports concurrent query. It was actually.  They are simply pure select query.  Non of them will update data. Do I miss anything?

**Additional context**
If I use NuGet to downgrade the driver back to 8.0.32.1 or 8.0.33, the same code works good again.

**Comment by bgrainger** [comment]
This repository is for [MySqlConnector](https://www.nuget.org/packages/MySqlConnector/). 

The bug you've reported is in the MySql.Data package, and is already filed as [bug 111759 in their bug database](https://bugs.mysql.com/bug.php?id=111759). MySql.Data is an unreliable library, particularly in async scenarios (see also [bug 110717](https://bugs.mysql.com/bug.php?id=110717)).

I may be biased, but I would strongly recommend switching to MySqlConnector instead. See the [documentation on doing that here](https://mysqlconnector.net/tutorials/migrating-from-connector-net/).
