### ISSUE TITLE
Exception with manticore if no result

### ISSUE THREAD

**Issue by daikoz** [mysql-net/MySqlConnector#1362]
**Software versions**
MySqlConnector version: 2.2.7
.NET version: 7.0.10 linux
Manticore >=  6.2.0-230804-45680f95d 
https://manual.manticoresearch.com/Changelog#Minor-changes

**Describe the bug**
Since manticore  6.2.0-230804-45680f95d (ok on 6.0.4-230314-1a3a4ea82), an exception is launched when no result is found.

**Exception**
```
MySqlConnector.MySqlException (0x80004005): Failed to read the result set.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MySqlConnector.Protocol.Serialization.ByteArrayReader.ReadLengthEncodedInteger() in /_/src/MySqlConnector/Protocol/Serialization/ByteArrayReader.cs:line 122
   at MySqlConnector.Protocol.Payloads.OkPayload.Create(ReadOnlySpan`1 span, Boolean deprecateEof, Boolean clientSessionTrack) in /_/src/MySqlConnector/Protocol/Payloads/OkPayload.cs:line 30
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 175
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 133
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 493
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 77
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 345
```

**Comment by bgrainger** [comment]
Please provide detailed steps to reproduce the problem. I tried the following:

```
docker run -e EXTRA=1 --name manticore --rm -d -p 9306:9306 -p 9308:9308 manticoresearch/manticore:6.2.0
# wait for container to start
docker exec -it manticore mysql
mysql> source /sandbox.sql
mysql> quit
```

```csharp
using var conn = new MySqlConnection("server=localhost;port=9306;connectionreset=false");
conn.Open();
Console.WriteLine(conn.ServerVersion);

using var command = new MySqlCommand("select * from films where id = 3000;", conn);
using var reader = command.ExecuteReader();
Console.WriteLine(reader.Read());
```

Output:

```
6.2.0 45680f95d@230804 (columnar 2.2.0 dc33868@230804) (secondary 2.2.0 dc33868@230804)
False
```

No exception was thrown.

**Comment by bgrainger** [comment]
Sounds like this is a bug with manticore if other clients are also reporting malformed packets: https://github.com/manticoresoftware/manticoresearch/issues/1409

MySqlConnector could report a better internal exception, but I would consider its behaviour acceptable overall. Closing as external.
