### ISSUE TITLE
Get error "Packet received out-of-order. Expected 1; got 2." when connecting to MySQL Innodb Cluster via MySQL Router

### ISSUE THREAD

**Issue by zh0u** [mysql-net/MySqlConnector#1406]
**Software versions**
MySqlConnector version: 2.3.1
Server type (MySQL, MariaDB, Aurora, etc.) and version:  8.0.25-commercial
.NET version: 
(Optional) ORM NuGet packages and versions: .net 6

**Describe the bug**
We're connecting to a MySQL InnoDB Cluster (https://dev.mysql.com/doc/mysql-shell/8.0/en/mysql-innodb-cluster.html) via MySQL Router. It works fine for the first connection. But it would throw error "Packet received out-of-order. Expected 1; got 2."  on the second connection.

**Exception**
MySqlConnector.MySqlProtocolException: Packet received out-of-order. Expected 1; got 2.
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.ReadPayloadAsync(BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ArraySegmentHolder`1 previousPayloads, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in /_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 448
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 924
   at MySqlConnector.Core.ServerSession.TryResetConnectionAsync(ConnectionSettings cs, MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 637
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int64 startingTimestamp, Int32 timeoutMilliseconds, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 76
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int64 startingTimestamp, Int32 timeoutMilliseconds, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 146
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int64 startingTimestamp, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 919
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 419
   at System.Data.Common.DbDataSource.OpenDbConnectionAsync(CancellationToken cancellationToken) in /_/src/MySqlConnector/Shims/DbDataSource.cs:line 66
   at System.Data.Common.DbDataSource.OpenDbConnectionAsync(CancellationToken cancellationToken) in /_/src/MySqlConnector/Shims/DbDataSource.cs:line 76
   at MySqlConnector.MySqlDataSource.OpenConnectionAsync(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataSource.cs:line 99

**Code sample**

```csharp
    // Create a Microsoft.Extensions.Logging LoggerFactory, configuring it with the providers,
    // log levels and other desired configuration.
    var loggerFactory = LoggerFactory.Create(builder => builder.AddConsole().SetMinimumLevel(LogLevel.Debug));

    var dataSourceBuilder = new MySqlDataSourceBuilder("Server=xxxxxxx;Port=xxxx;Uid=xxxxx;Pwd=xxxxxx;Database=xxxx;");
    dataSourceBuilder.UseLoggerFactory(loggerFactory);
    await using var dataSource = dataSourceBuilder.Build();
    
    using ( MySqlConnection dbConnection = await dataSource.OpenConnectionAsync())
    {
        string updateQuery1 = "UPDATE test.testtable SET ModifiedOn = @modifyOn WHERE `Key` = @key1";
        await dbConnection.ExecuteAsync(updateQuery1, new { modifyOn = DateTime.UtcNow, key1 = "IdPrefix" });
    }
    
    using (MySqlConnection dbConnection = await dataSource.OpenConnectionAsync())
    {
        string updateQuery1 = "UPDATE test.testtable SET ModifiedOn = @modifyOn WHERE `Key` = @key1";
        await dbConnection.ExecuteAsync(updateQuery1, new { modifyOn = DateTime.UtcNow, key1 = "IdPrefix" });
    }
```

**Expected behavior**
It should not throw error on the 2nd query.

**Additional context**
N/A

**Comment by zh0u** [comment]
It's figured out a MySQL version issue. After upgrade to 8.0.32 (from 8.0.25), the issue is sloved.
