### ISSUE TITLE
ExecuteScalarAsync throw "MySqlSession is not connected." after the server has been idle for some time

### ISSUE THREAD

**Issue by alanprot** [mysql-net/MySqlConnector#142]
If i leave the servers without load for some time i get this exception for every request for mysql.

message: MySqlSession is not connected

	at MySql.Data.Serialization.MySqlSession.VerifyConnected()
	   at MySql.Data.Serialization.MySqlSession.TryAsync[TArg](Func`3 func, TArg arg, IOBehavior ioBehavior, CancellationToken cancellationToken)
	   at MySql.Data.Serialization.MySqlSession.SendAsync(PayloadData payload, IOBehavior ioBehavior, CancellationToken cancellationToken)
	   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteReaderAsync>d__3.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteScalarAsync>d__2.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at MySql.Data.MySqlClient.MySqlCommand.<ExecuteScalarAsync>d__48.MoveNext

**Comment by caleblloyd** [comment]
I wonder if this would be resolved by TCP KeepAlive in #132 

As a fix, you should use Connection Pooling and close your connections after they have performed a unit of work before they become idle for some time.  This way if the Pooled connection becomes disconnected while it is idle, it will be discarded when it is drawn from the pool.

**Comment by caleblloyd** [comment]
@alanprot KeepAlive was shipped in [0.8.0](https://www.nuget.org/packages/MySqlConnector/0.8.0).  Can you configure with KeepAlive and see if this fixes?  Please reopen the issue if it does not.
