### ISSUE TITLE
Question: Expected m_hasMoreResults to be false

### ISSUE THREAD

**Issue by justdoitang** [mysql-net/MySqlConnector#1422]
System.InvalidOperationException: Expected m_hasMoreResults to be false

   at MySqlConnector.MySqlDataReader.InitAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 463

   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 57

   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 358

   at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 350

   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 434

**Comment by justdoitang** [comment]
When I was using version 2.2.7, I didn't encounter this issue. However, when I upgraded to 2.3.1, the problem occasionally occurs. What could be the cause of this issue, and how should I handle it? Thank you.

**Comment by bgrainger** [comment]
It's possible this could be an underlying issue that's now being exposed as a side-effect of https://github.com/mysql-net/MySqlConnector/issues/1277.

What's your code that's being executed when this exception is thrown? Is it possible that you're reusing the same `MySqlConnection` on multiple threads at the same time? This is not permitted: https://mysqlconnector.net/troubleshooting/connection-reuse/.
