### ISSUE TITLE
System.InvalidProgramException in Container-Environment

### ISSUE THREAD

**Issue by usenff-cu** [mysql-net/MySqlConnector#1425]
**Software versions**
MySqlConnector version: 2.3.3
Server type and version: MySQL 8.0.32
.NET version: net8.0
ORM NuGet packages and versions: linq2db 5.3.2

**Describe the bug**
We get a _System.InvalidProgramException_ when querying the database. This only happens in our Docker-Container on our kubernetes-cluster. Host-Type: Linux; Base-Image (build): mcr.microsoft.com/dotnet/sdk:8.0; Base-Image (runtime): mcr.microsoft.com/dotnet/aspnet:8.0. The same container works fine on our developer machines. (Docker on Windows 10 with WSL)

When we switch fom MySqlConnector to MySql.Data everything works fine in all environments. 

**Exception**
```
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in /_/src/MySqlConnector/MySqlCommand.cs:line 290
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior)
   at LinqToDB.Data.DataConnection.ExecuteDataReader(CommandBehavior commandBehavior)
   at LinqToDB.Data.DataConnection.ExecuteReader()
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReader()
   at LinqToDB.Linq.QueryRunner.ExecuteElement[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles)
   at LinqToDB.Linq.QueryRunner.<>c__DisplayClass26_0`1.<SetRunQuery>b__0(IDataContext db, Expression expr, Object[] ps, Object[] preambles)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Any[TSource](IQueryable`1 source)
```

**Code sample**
Most likely irrelevant. Even a simple synchronous query triggers the exception.
```csharp
bool initialImportNeeded = !dataConnection.GetTable<Review>().Any();
```

**Expected behavior**
The query is executed without exception.

**Additional context**
We are currently updating our application from .net 5 to .net 8. We also tried the .net 7 Version and encountered the same problem. The only way to "fix" the problem so far is to switch to MySql.Data which is no real solution.

**Comment by bgrainger** [comment]
An `InalidProgramException` probably indicates something seriously wrong with the .NET Runtime and not MySqlConnector itself. This is an old comment but I think its troubleshooting steps are still a good idea: capture a crash dump and analyse that offline with debugging tools to see what is causing the exception. https://github.com/dotnet/runtime/issues/10459#issuecomment-439957539

Or we could go with the theory that some third-party DLL is modifying the IL and causing the exception. Do you have different APM software (e.g., Application Insights, New Relic, elastic APM, etc.) running in Production than locally? Can you disable that monitoring and see if the crash "goes away"?

**Comment by usenff-cu** [comment]
I didn't think about the APM software (in our case Dynatrace) but now it seems so obvious. If I disable monitoring for the container everything works fine.

Thank you very much!

**Comment by bgrainger** [comment]
Glad you figured it out! (You may wish to report this problem to Dynatrace support; their profiler should not be injecting invalid IL that causes an `InvalidProgramException`.)
