### ISSUE TITLE
EntityFramework with TransactionScope uses different connection for same DbContext object

### ISSUE THREAD

**Issue by dtkujawski** [mysql-net/MySqlConnector#1436]
Regardless of using XATransaction TRUE or FALSE, we have noticed that if you wrap multiple EF SaveChanges() calls in a TransactionScope, each SaveChanges() will be sent on a different connection.

For example, using a connection string:  **"Data Source=localhost;database=XXX;userid=XXX;password=XXX;GuidFormat=none;UseXATransactions=false;AutoEnlist=false"**
```
using (var transactionScope = new TransactionScope(TransactionScopeOption.Required, new TransactionOptions { IsolationLevel = IsolationLevel.RepeatableRead }, TransactionScopeAsyncFlowOption.Enabled))
{
    using (var dbContext = new SampleDbContext())
    {
        var person = ...
        dbContext.Add(person);
        dbContext.SaveChanges();

        var personContact = ...
        personContact.PersonID = person.PersonID;
        dbContext.Add(personContact);
        dbContext.SaveChanges();
    }
    transactionScope.Complete();
}
```
Results in:
```
2024-01-11T19:54:35.414293Z      3426 Connect   root@172.17.0.1 on XXX using SSL/TLS
2024-01-11T19:54:35.415105Z      3426 Query     SET NAMES utf8mb4
2024-01-11T19:54:35.441374Z      3426 Query     set session transaction isolation level repeatable read
2024-01-11T19:54:35.488832Z      3426 Query     start transaction
2024-01-11T19:54:35.587993Z      3426 Query     INSERT INTO `PERSON` ...
2024-01-11T19:54:35.588278Z      3426 Query     SELECT `PERSON_ID` FROM `PERSON` WHERE ROW_COUNT() = 1 AND `PERSON_ID` = LAST_INSERT_ID()
2024-01-11T19:54:35.676287Z      3427 Connect   root@172.17.0.1 on XXX using SSL/TLS
2024-01-11T19:54:35.676900Z      3427 Query     SET NAMES utf8mb4
2024-01-11T19:54:35.678839Z      3427 Query     INSERT INTO `PERSON_CONTACT` ...
```
Note that the initial SaveChanges was connection 3412 and the second query was 3413.

Same Code, but **without the TransactionScope** results in the DbContext SaveChanges going through the same connection.
```
2024-01-11T20:03:46.287371Z      3449 Connect   root@172.17.0.1 on DPAS_MIN using SSL/TLS
2024-01-11T20:03:46.287992Z      3449 Query     SET NAMES utf8mb4
2024-01-11T20:03:46.314975Z      3449 Query     set session transaction isolation level repeatable read
2024-01-11T20:03:46.361751Z      3449 Query     start transaction
2024-01-11T20:03:46.461935Z      3449 Query     INSERT INTO `PERSON` ...
2024-01-11T20:03:46.462296Z      3449 Query     SELECT `PERSON_ID` FROM `PERSON` WHERE ROW_COUNT() = 1 AND `PERSON_ID` = LAST_INSERT_ID()
2024-01-11T20:03:46.505226Z      3449 Query     commit
2024-01-11T20:03:46.569182Z      3449 Query     SET NAMES utf8mb4
2024-01-11T20:03:46.570601Z      3449 Query     set session transaction isolation level repeatable read
2024-01-11T20:03:46.571337Z      3449 Query     start transaction
2024-01-11T20:03:46.573166Z      3449 Query     INSERT INTO `PERSON_CONTACT` ...
2024-01-11T20:03:46.573390Z      3449 Query     SELECT `PERSON_CONTACT_ID` FROM `PERSON_CONTACT` WHERE ROW_COUNT() = 1 AND `PERSON_CONTACT_ID` = LAST_INSERT_ID()
2024-01-11T20:03:46.575962Z      3449 Query     commit
```

The problem we have is this, we don't want to use XATransactions due to downstream issues in AWS and another legacy provider.  But, if we turn off XATransactions and leave AutoEnlist=true then we get the error:
**Multiple simultaneous connections or connections with different connection strings inside the same transaction are not supported when UseXaTransactions=False.**

If we turn XATransactions=False and AutoEnlist=false, then we get the behavior were the 2nd SaveChanges call is on a separate connection and doesn't enlist in the XAtransaction correctly:
```
2024-01-11T19:50:49.376773Z      3412 Connect   root@172.17.0.1 on XXX using SSL/TLS
2024-01-11T19:50:49.377422Z      3412 Query     SET NAMES utf8mb4
2024-01-11T19:50:49.403437Z      3412 Query     XA START 'db021034-64e6-4bdd-a6bd-5acee7941b47:1', '1'
2024-01-11T19:50:49.545639Z      3412 Query     INSERT INTO `PERSON` ...
2024-01-11T19:50:49.545965Z      3412 Query     SELECT `PERSON_ID` FROM `PERSON` WHERE ROW_COUNT() = 1 AND `PERSON_ID` = LAST_INSERT_ID()
2024-01-11T19:50:49.636309Z      3413 Connect   root@172.17.0.1 on XXX using SSL/TLS
2024-01-11T19:50:49.637053Z      3413 Query     SET NAMES utf8mb4
2024-01-11T19:50:49.638809Z      3413 Query     INSERT INTO `PERSON_CONTACT` ...
```

So, the only way EntityFramework works is if XATransactions=true and AutoEnlist=true in this simple example.  Any ideas?

**Comment by bgrainger** [comment]
I don't know enough about when EF chooses to open a new or reuse an existing connection to diagnose this. Sounds like this could potentially be a https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/ issue and maybe should be opened on that repo. CC @lauxjpn

**Comment by dtkujawski** [comment]
@bgrainger Thank you for the direction, I'll post in that repo.  Would you happen to know a good way to diagnose the error in the above code when XATransactions=false and AutoEnlist=false?
**Multiple simultaneous connections or connections with different connection strings inside the same transaction are not supported when UseXaTransactions=False.**

In this example, we just have a single DbContext; so there isn't different connection strings.  But, Maybe EF is adding something to the connection string??  Any idea how we could get visibility into that error and see what the different connection strings are in this case to diagnose further?

Thank you so much for helping!

**Comment by bgrainger** [comment]
> the error in the above code when XATransactions=false and AutoEnlist=false?
> Multiple simultaneous connections or connections with different connection strings inside the same transaction are not supported when UseXaTransactions=False.

Did you mean when `AutoEnlist=true`? (That seems to be what was written in the OP.)

When `AutoEnlist=true` (the default), MySqlConnector detects if there is an active `TransactionScope` and attempts to enroll in it. If `UseXaTransactions=true` (also the default), then an XA transaction will be used, as `TransactionScope` is typically used in a distributed txn scenario. If `UseXaTransactions=false` then MySqlConnector will just use a regular DB transaction. If you attempt to use a second, separate connection then the error is raised because you have disabled the use of distributed transactions, but are _also_ trying to commit changes on multiple connections (which requires a distributed transaction in order to be ACID). In your scenario, you may not be actively trying to use multiple connections, but some piece of code is creating them, which causes the issue.

When `AutoEnlist=false`, MySqlConnector ignores `TransactionScope` objects. If you're trying to use them to enforce data integrity then Bad Things might happen if you do this. OTOH, if EF respects `TransactionScope` and uses DB transactions correctly inside it, then _maybe_ the right thing to do is disable MySqlConnector's `AutoEnlist` behaviour. However, I don't know if that is the case. If it were, then I would expect Pomelo to set MySqlConnector's behaviour correctly (e.g., by manipulating the connection string) so that the right thing happens by default. (If it doesn't, that would be a Pomelo bug.)

See also https://github.com/mysql-net/MySqlConnector/issues/1404#issuecomment-1832945660 and https://mysqlconnector.net/connection-options/#AutoEnlist.

**Comment by bgrainger** [comment]
A final alternative would be abandoning the use of `TransactionScope` and using `dbContext.Database.BeginTransaction()` as recommended by the [EF Core docs](https://learn.microsoft.com/en-us/ef/core/saving/transactions).

Is there a reason you need/choose to use `TransactionScope`?

**Comment by dtkujawski** [comment]
Apologies, as you suspected I meant XATransactions=false and AutoEnlist=true; that is the condition we get the error in the above code.  I completely understand your point regarding different connection strings, but the code fails on the first SaveChanges() call in a completely stripped-down project (as pure EF / Pomelo / MySqlConnector as I can make) (see below).

I was hoping there was some extra logging that I might be able to enable to see what connection strings the provider was comparing?

```
using (var transactionScope = new TransactionScope(TransactionScopeOption.Required, new TransactionOptions { IsolationLevel = IsolationLevel.RepeatableRead }, TransactionScopeAsyncFlowOption.Enabled))
{
    using (var dbContext = new SampleDbContext())
    {
        var person = ...
        dbContext.Add(person);
        **dbContext.SaveChanges();**
    }
}
```

**Comment by bgrainger** [comment]
The error is "Multiple simultaneous connections **or** connections with different connection strings" (emphasis added). The problem is multiple connections, not different connection strings.

**Comment by dtkujawski** [comment]
@bgrainger But, in the case of multiple connections, would I not see those in the logs?  With XATransactions=false and AutoEnlist=false, the log shows only a single connection (up until the exception is thrown):

```
2024-01-12T01:17:04.659259Z      4465 Connect   root@172.17.0.1 on  using SSL/TLS
2024-01-12T01:17:04.662553Z      4465 Query     SET NAMES utf8mb4
2024-01-12T01:17:04.686013Z      4465 Query     set session transaction isolation level repeatable read
2024-01-12T01:17:04.733441Z      4465 Query     start transaction
```

**Comment by bgrainger** [comment]
`FindExistingEnlistedTransaction` is called very early on by `OpenAsync`, possibly before anything has been logged: https://github.com/mysql-net/MySqlConnector/blob/8fffc068247dbc304a371b7531241bc900fbf3a3/src/MySqlConnector/MySqlConnection.cs#L406

If that finds an existing transaction, it will throw: https://github.com/mysql-net/MySqlConnector/blob/8fffc068247dbc304a371b7531241bc900fbf3a3/src/MySqlConnector/MySqlConnection.cs#L287-L290

So it seems quite likely to me that code is creating and opening a new `MySqlConnection` object (before the current one has been closed/disposed) and that's what's causing the exception. This may point to the need for more logging (even if it's at the Trace or Debug level, and has to be enabled explicitly) to help track down problems like this.

You could try putting a function breakpoint on `MySqlConnection.OpenAsync` and seeing if you can trace the logic from Pomelo or EF Core. (You haven't provided the full call stack from when the exception happens.)

**Comment by dtkujawski** [comment]
@bgrainger Yes, I think that's what I've settled on as well.  Likely TransactionScope is causing a connection to be open and then EF is trying to open another one causing the condition of multiple connections to be met.  This is probably related to the issue we talked about yesterday (added to the EF repo where EF was creating a new connection unnecessarily) instead of the EF DbContext using the same connection as the transaction (like what SQL Server and Oracle EF does).

**stack trace**
```
   at MySqlConnector.MySqlConnection.FindExistingEnlistedSession(Transaction transaction)
   at MySqlConnector.MySqlConnection.<OpenAsync>d__29.MoveNext()
   at MySqlConnector.MySqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at TestTransactions.Program.Main(String[] args) in C:\Users\dkujawski\Desktop\TestTransactions\Program.cs:line 18
```

**Comment by bgrainger** [comment]
Can you provide a minimal example that reproduces the problem? I took the sample app from https://learn.microsoft.com/en-us/ef/core/get-started/overview/first-app but changed it from `UseSqlite` to `UseMySql`.

Then I added `using (var transactionScope = new TransactionScope(TransactionScopeOption.Required, new TransactionOptions { IsolationLevel = IsolationLevel.RepeatableRead }, TransactionScopeAsyncFlowOption.Enabled))` around the first two `SaveChanges` calls in the example code in https://learn.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=netcore-cli#create-read-update--delete.

I set `UseXaTransactions=false` in my connection string.

Pomelo/EF created and reused the same connection twice to perform both inserts. Everything worked as I would expect it to.

**Comment by dtkujawski** [comment]
Here is a minimal example console app.  Just change the connection string and schema in the constants at the top of the DbContext class to point to your DB.  For me, regardless of UseXaTransactions setting, it uses different connections (as described above in MySql logs)

Perhaps it is a version issue with MySqlConnector, Pomelo, EF different from what you were trying?  We are on .NET 6 at the moment (since it is LTS) until NET 8 releases it's first major patch (that's what triggers us to update typically).

[StrippedTestTrans2.zip](https://github.com/mysql-net/MySqlConnector/files/13943567/StrippedTestTrans2.zip)

**Comment by bgrainger** [comment]
Thanks for the sample app. I found a problem. Replace

```csharp
optionsBuilder.UseMySql(ConnectionStringMySql, ServerVersion.AutoDetect(ConnectionStringMySql));
```

with

```csharp
optionsBuilder.UseMySql(ConnectionStringMySql, new MySqlServerVersion(new Version(8, 0, 0)));
```

and the program works without error.

Because `ServerVersion.AutoDetect(ConnectionStringMySql)` is within `OnConfiguring` and that's called from within a `TransactionScope`, the connection opened by Pomelo to automatically detect the server version enlists in the transaction, and causes the _next_ connection to throw this exception.

This feels like a Pomelo bug to me, so I'll edit the issue on that repo. Please use an explicit `MySqlServerVersion` or `MariaDbServerVersion` as a workaround.
