### ISSUE TITLE
MySqlConnector.Core.ConnectionPool threw an exception after install

### ISSUE THREAD

**Issue by JosephBaileyOcUK** [mysql-net/MySqlConnector#1440]
**Software versions**
MySqlConnector version: 2.3.4
Server type (MySQL, MariaDB, Aurora, etc.) and version: MySQL 5.0
.NET version: 4.7.2
(Optional) ORM NuGet packages and versions: System.Buffers 4.5.1

**Describe the bug**
The program runs fine in visual studio, however after creating an install and running I consistently run into an error related to system.buffers.

It seems related to the bit version, but I have tried building for both x64 and x86

**Exception**
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.TypeInitializationException: The type initializer for 'MySqlConnector.Core.ConnectionPool' threw an exception.
 ---> System.BadImageFormatException: Could not load file or assembly 'System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
 ---> System.BadImageFormatException: Cannot load a reference assembly for execution.
   --- End of inner exception stack trace ---
   at System.Text.ValueStringBuilder.Dispose()
   at System.Text.ValueStringBuilder.ToString()
   at Microsoft.Extensions.Logging.LogValuesFormatter..ctor(String format)
   at Microsoft.Extensions.Logging.LoggerMessage.CreateLogValuesFormatter(String formatString, Int32 expectedNamedParameterCount)
   at Microsoft.Extensions.Logging.LoggerMessage.Define[T1,T2](LogLevel logLevel, EventId eventId, String formatString, LogDefineOptions options)
   at Microsoft.Extensions.Logging.LoggerMessage.Define[T1,T2](LogLevel logLevel, EventId eventId, String formatString)
   at MySqlConnector.Core.ConnectionPool..cctor() in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 816
   --- End of inner exception stack trace ---
   at MySqlConnector.Core.ConnectionPool.GetPool(String connectionString, MySqlConnectorLoggingConfiguration loggingConfiguration, Boolean createIfNotFound)
   at MySqlConnector.MySqlConnection.<OpenAsync>d__28.MoveNext() in /_/src/MySqlConnector/MySqlConnection.cs:line 399
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 381
   at TestForMySQLConnector.Form1.button1_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9195.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
TestForMySQLConnector
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/OcUK/mysqlconnectortest/TestForMySQLConnector.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9195.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
MySqlConnector
    Assembly Version: 2.0.0.0
    Win32 Version: 2.3.4.0
    CodeBase: file:///C:/Program%20Files%20(x86)/OcUK/mysqlconnectortest/MySqlConnector.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly Version: 7.0.0.1
    Win32 Version: 7.0.723.27404
    CodeBase: file:///C:/Program%20Files%20(x86)/OcUK/mysqlconnectortest/Microsoft.Extensions.Logging.Abstractions.DLL
----------------------------------------
System.Threading.Tasks.Extensions
    Assembly Version: 4.2.0.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Program%20Files%20(x86)/OcUK/mysqlconnectortest/System.Threading.Tasks.Extensions.DLL
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.2
    Win32 Version: 4.6.31308.01
    CodeBase: file:///C:/Program%20Files%20(x86)/OcUK/mysqlconnectortest/System.Memory.DLL
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 7.0.0.2
    Win32 Version: 7.0.423.11508
    CodeBase: file:///C:/Program%20Files%20(x86)/OcUK/mysqlconnectortest/System.Diagnostics.DiagnosticSource.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///C:/Program%20Files%20(x86)/OcUK/mysqlconnectortest/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.



```

**Code sample**

```csharp
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace TestForMySQLConnector
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            MySqlConnector.MySqlConnection conn = new MySqlConnector.MySqlConnection(); 
            conn.ConnectionString = "server=localhost;user=root;database=world;port=3306;password=123456;";
            conn.Open();
            MySqlConnector.MySqlCommand cmd = new MySqlConnector.MySqlCommand("select * from city", conn);
        }
    }
}

```

**Expected behavior**
Doesn't throw this error

**Additional context**

I realise this seems to be an issue with System.Buffers but I have tried everything I can think of and nothing works, I created this solution merely as a test and was surprised when it still failed. I have tried many things to try and get it to work but nothing is, given how much this library is used I can't believe I am the only one running into the problem.

**Comment by bgrainger** [comment]
Looks like there's something wrong with the `System.Buffers.dll` file in your `bin` folder (or in `C:\Program Files (x86)\OcUK\mysqlconnectortest` if you're installing to there). It should be 20KB (20,856 bytes) if it's the `net461` version. If it's smaller, you've copied in the "reference assembly" by mistake, which can't be loaded.

I assume you've built an installer if your application is running from `C:\Program Files (x86)` so I suggest looking at the list of files that are getting installed to verify they're the right ones.

**Comment by JosephBaileyOcUK** [comment]
Yeh I found that the installer was picking up on the 32 bit version in a different folder from nuget, I found the correct version in a parent folder and replaced and it worked, sorry to bother you
