### ISSUE TITLE
WriteToServer throw Exception using a particular table name

### ISSUE THREAD

**Issue by WonderGnagno** [mysql-net/MySqlConnector#1458]
**Software versions**
MySqlConnector version: 2.3.5
Server type (MySQL, MariaDB, Aurora, etc.) and version: 
MariaDB-columnstore-cmapi.x86_64                   23.10.0-1                                                   @mariadb-main                            
MariaDB-columnstore-engine.x86_64                  11.2.3_23.10.0-1.el8                                        @mariadb-main  
.NET version: 6.0.x
(Optional) ORM NuGet packages and versions: 

**Describe the bug**
Using a tablename with char --- throw a MySqlConnector.MySqlException  (0x80004005)

**Exception**
MySqlConnector.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '------------' at line 1
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 894
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 37
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 130
   at MySqlConnector.MySqlDataReader.InitAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 483
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 357
   at MySqlConnector.MySqlBulkCopy.WriteToServerAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlBulkCopy.cs:line 266
   at MySqlConnector.MySqlBulkCopy.WriteToServer(DataTable dataTable) in /_/src/MySqlConnector/MySqlBulkCopy.cs:line 128
   at ConsoleApp1.WriteToServer.Test(String tableName) in F:\butta\MySqlIssue\MySqlIssue\WriteToServer.cs:line 48
   at ConsoleApp1.WriteToServer.Run() in F:\butta\MySqlIssue\MySqlIssue\WriteToServer.cs:line 61

**Code sample**

```csharp

using System.Data;
using MySqlConnector;


namespace ConsoleApp1;

public class WriteToServer
{
    public void Test(string tableName)
    {
        MySqlConnectionStringBuilder cm = new MySqlConnectionStringBuilder()
        {
            Server = "devel",
            UserID = "internal_dd",
            Password = "aaaaaa",
            Database = "INTERNAL_DD",
            AllowLoadLocalInfile = true
        };

        var connMy = new MySqlConnection(cm.ToString());
        connMy.Open();

        MySqlCommand cmd = connMy.CreateCommand();


        cmd.CommandText = $"DROP TABLE IF EXISTS  `{tableName}`";
        cmd.ExecuteNonQuery();
        cmd.CommandText = $"create table `{tableName}` (i int) ENGINE = ColumnStore;";
        cmd.ExecuteNonQuery();


        MySqlBulkCopy bulkCopy = new MySqlBulkCopy(connMy)
        {
            DestinationTableName = tableName
        };
        using MySqlDataAdapter dataAdapter = new MySqlDataAdapter($"select * from `{tableName}`", connMy);
        DataSet dataSet = new DataSet();
        dataAdapter.MissingSchemaAction = MissingSchemaAction.AddWithKey;
        dataAdapter.FillSchema(dataSet, SchemaType.Source);
        var dt = dataSet.Tables[0];

        var r = dt.NewRow();
        r[0] = 1;
        dt.Rows.Add(r);

        // Write from the source to the destination.
        var result = bulkCopy.WriteToServer(dt);
        if (result.Warnings.Count != 0)
        {
            /* handle potential data loss warnings */
        }
    }

    public void Run()
    {
        Test("normal");
        Console.WriteLine($"Table with ----- in the name create the issue");
        try
        {
            Test("normal------------");
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
        }
    }


}

```

**Expected behavior**

**Additional context**

**Comment by bgrainger** [comment]
This is covered in the documentation at https://mysqlconnector.net/api/mysqlconnector/mysqlbulkcopy/destinationtablename/:

> This name needs to be quoted if it contains special characters.

(This is due to backwards compatibility with MySql.Data.)

Use ```DestinationTableName = "`" + tableName.Replace("`", "``") + "`"``` or similar to perform the escaping.
