### ISSUE TITLE
MySqlConnector.MySqlProtocolException: Packet received out-of-order. Expected 2; got 1.

### ISSUE THREAD

**Issue by justdoitang** [mysql-net/MySqlConnector#1465]
**Software versions**
MySqlConnector version:2.2.7
Server type (MySQL, MariaDB, Aurora, etc.) and version: MySQL 8.0
.NET version: .net core 3.1
(Optional) ORM NuGet packages and versions: Dapper 2.1.35

**Describe the bug**
MySqlConnector.MySqlProtocolException: Packet received out-of-order. Expected 2; got 1.

**Exception**
 at MySqlConnector.Protocol.Serialization.ProtocolUtility.<DoReadPayloadAsync>g__AddContinuation|5_0(ValueTask`1 readPacketTask, BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ArraySegmentHolder`1 previousPayloads, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in /_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 498

   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 968

   at MySqlConnector.Core.ServerSession.TryResetConnectionAsync(ConnectionSettings cs, MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 700

   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Int32 timeoutMilliseconds, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 137

   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Int32 timeoutMilliseconds, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 137

   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 966

   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 457

   at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 382

**Code sample**
![image](https://github.com/mysql-net/MySqlConnector/assets/49199289/d0a83430-3b8e-4280-8779-9e915e440968)

**Comment by EmaX093** [comment]
Same problem here, had to revert to from 2.3.7 to 2.3.5 and the problem is gone. I tested 2.3.6 and problem occurs too. Something changed since 2.3.6.

My setup is: Linq2DB 5.4.1 + MySQL InnoDB Cluster 8.0.35 + ProxySQL version 2.5.5-10-g195bd70, codename Truls.

**Comment by Ekkeir** [comment]
We've also observed `Packet received out-of-order. Expected 2; got 1.` error with MySqlConnector versions 2.3.6, 2.3.7.
Adding `Pipelining = False;` to connection string (as mentioned in [Release notes](https://github.com/mysql-net/MySqlConnector/releases/tag/2.3.6)) resolved the issue, yet breaking changes like this in minor updates seem undesirable.

MariaDB (ver. 10.6.16-MariaDB-log)
MySqlConnector versions: 2.3.6, 2.3.7

**Comment by bgrainger** [comment]
Is this problem reproducible? Is it possible to provide a packet capture from when the problem occurs?

**Comment by wjl476146955** [comment]
Same problem happened. 2.3.7 or 2.3.6 and  mysql8.0.26 throw error "MySqlConnector.MySqlProtocolException: Packet received out-of-order. Expected 1; got 2." 2.3.5 is ok.

**Comment by EmaX093** [comment]
> Is this problem reproducible? Is it possible to provide a packet capture from when the problem occurs?

This is what you need ?
[ddd.txt](https://github.com/user-attachments/files/16664762/ddd.txt)

**Comment by EmaX093** [comment]
> We've also observed `Packet received out-of-order. Expected 2; got 1.` error with MySqlConnector versions 2.3.6, 2.3.7. Adding `Pipelining = False;` to connection string (as mentioned in [Release notes](https://github.com/mysql-net/MySqlConnector/releases/tag/2.3.6)) resolved the issue, yet breaking changes like this in minor updates seem undesirable.
> 
> MariaDB (ver. 10.6.16-MariaDB-log) MySqlConnector versions: 2.3.6, 2.3.7

This totally fix the problem for me! Thank you!

**Comment by bgrainger** [comment]
> This is what you need ?
> ddd.txt

That file shows:

```
-> Packet Number: 0, Statement: set session transaction isolation level repeatable read;
-> Packet Number: 0, Statement: start transaction;
<- Packet Number: 1, Response Code: OK Packet (0x00) 
<- Packet Number: 2, Response Code: OK Packet (0x00) 

This is an incorrect response from the MySQL Server and is causing the error.

> Adding `Pipelining = False;` to connection string

That is also what I would recommend given the observed behavior above.

**Comment by bgrainger** [comment]
@EmaX093 

You've mentioned both of these MySQL Servers in different comments:

> My setup is: Linq2DB 5.4.1 + MySQL InnoDB Cluster 8.0.35 + ProxySQL version 2.5.5-10-g195bd70, codename Truls.

> MariaDB (ver. 10.6.16-MariaDB-log)

Are you using both of them? Do both exhibit the "Packet received out-of-order" problem?

**Comment by EmaX093** [comment]
> @EmaX093
> 
> You've mentioned both of these MySQL Servers in different comments:
> 
> > My setup is: Linq2DB 5.4.1 + MySQL InnoDB Cluster 8.0.35 + ProxySQL version 2.5.5-10-g195bd70, codename Truls.
> 
> > MariaDB (ver. 10.6.16-MariaDB-log)
> 
> Are you using both of them? Do both exhibit the "Packet received out-of-order" problem?

Hello! That was the other guy, I only have MySQL InnoDB Cluster with a proxysql in front.

Anyway i just tried to connect directly to mysql without proxysql and it works just fine so is a problem related to proxysql.

Thank you for your time and I apologize for the inconveniences.

**Comment by completej** [comment]
> Just here to say that I'm having the exact same issue. Our MySql servers are in a cluster environment, for what it's worth. Adding Pipelining = False to connection string corrects the issue for me.

Adding to this.  Our DEV tier is a single node instance with no issues @ 2.3.7.  Our UAT and PRD tiers are 3-node Galera clusters that saw compatibility issues.  Adding Pipelining = False; also fixed this for us.

**Comment by W1zzardTPU** [comment]
Can confirm, Pipelining = False fixed "Packet received out-of-order" when connecting through ProxySQL. Zero issues with pipelining when connecting to the same database through Oracle's MySQL Router.

```
MySqlConnector.MySqlProtocolException: Packet received out-of-order. Expected 1; got 2.
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.ReadPayloadAsync(BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ArraySegmentHolder`1 previousPayloads, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in /_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 447
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 1070
   at MySqlConnector.MySqlConnection.BeginTransactionAsync(IsolationLevel isolationLevel, Nullable`1 isReadOnly, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 168
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
```

**Comment by bgrainger** [comment]
No, it won't cause performance issues. (It just disables an optimization that most--but not all--servers support.)

**Comment by W1zzardTPU** [comment]
So I've got some data, which definitely isn't perfect, but still useful to show that the difference isn't huge, at least in optimal conditions. All services on the same host, which means networking (which is the major reason for Pipelining in the first place) doesn't play much of a role. Enterprise hardware, modern kernel, bare-metal, just Docker.

MySQL Router + Pipelining:
11-28 06:13:17.222 [Info] EF query stats | avg 2.479 ms | p50 2.906 ms | p95 3.825 ms | p99 5.548 ms | count 161127                                                                                                            

ProxySQL + No Pipelining (incompatible with ProxySQL):
11-28 06:19:35.759 [Info] EF query stats | avg 2.627 ms | p50 3.105 ms | p95 3.831 ms | p99 5.576 ms | count 181300      
11-28 06:30:33.688 [Info] EF query stats | avg 2.568 ms | p50 3.092 ms | p95 3.835 ms | p99 5.336 ms | count 112694       
11-28 06:34:33.697 [Info] EF query stats | avg 2.620 ms | p50 3.117 ms | p95 3.877 ms | p99 5.737 ms | count 274089                                                                                                                                                                                                                11-28 07:14:33.800 [Info] EF query stats | avg 2.663 ms | p50 3.175 ms | p95 3.837 ms | p99 5.509 ms | count 2213992      
11-28 08:03:33.933 [Info] EF query stats | avg 2.666 ms | p50 3.178 ms | p95 3.827 ms | p99 5.461 ms | count 4593837  

So just a tiny bit slower, like 7% or so. p9x latencies unchanged.

and it seems that difference comes mostly from the MySQL Router -> ProxySQL switch, and not from pipelining, because when I switched another service from MySQL Router to ProxySQL, which works with Pipelining = on (because it doesn't run multiple queries in parallel), I also saw around +7% in latency.

For me this means I'll get rid of mysql-router and use ProxySQL instead (Group Replication). I've been seeing 1 or 2 daily segfaults of mysql-router and Oracle doesn't seem to care enough to fix it. So will happily trade +7% latency to get rid of 10-20 seconds of daily downtime

**Comment by MosheL** [comment]
I started to see  this error when upgrading my client to  2.5.0.  Tried both  MariaDB local and AWS. 
local version: `11.8.2-MariaDB-ubu2404`
AWS:  `10.5.29-MariaDB-log`.

The strage thing, I disabled pipelining via ConnString but the problem is still here. I need to better debug it.

**Comment by rogerfankhauser** [comment]
@MosheL Did you eventually find a solution to this? We have the same thing happening on version 2.2.7 and setting the pipelining to false didn't solve this issue.

**Comment by jangils** [comment]
We see the same issues in an Aurora MySQL database while using v2.5. Any more insights?

**Comment by bfren** [comment]
I spent a couple of hours yesterday trying to fix this with Claude - didn't get anywhere.  Pipelining=false didn't help - on v2.5 as well.  Tried disabling pooling, messing with timeouts, disabling connection reset, etc.

Stack trace shows the issue is coming from BeginTransactionAsync - Claude thinks 'MySqlConnector sends a SET TRANSACTION ISOLATION LEVEL or BEGIN command and ProxySQL is responding with an out-of-order packet.'

The issue is I don't know if this is an issue with MySqlConnector or ProxySQL!

**Comment by wwwu** [comment]
## Postmortem: Intermittent `MySqlProtocolException: Packet received out-of-order`

### Symptom

Under a message-consumer workload we saw sporadic failures:

```
MySqlConnector.MySqlProtocolException: Packet received out-of-order. Expected 1; got 2.
   at ...ServerSession.TryResetConnectionAsync(...)
   at ...ConnectionPool.GetSessionAsync(...)
   at ...MySqlConnection.OpenAsync(...)
   at ...RelationalConnection.BeginTransactionAsync(...)
```

The error surfaced at connection **open time** (`BeginTransactionAsync` → pool `TryResetConnectionAsync`), which is misleading: the connection being opened was *not* the culprit — it was picked up **already dirty** from the shared pool.

Changing the version of MySqlConnector or setting up Pipelining are both ineffective.


### Root Cause

A fire-and-forget call to a **Scoped** service that shares the same `DbContext`:

```csharp
// other logic

// inside a Scoped service method (the current request/message scope)
_ = _myService.MethodAsync();
```

`_myService` is resolved from the **same DI scope** as `_dbContext`, so both share **one** `AppDbContext` (one physical MySQL connection).

Because the call was **not awaited**:
1. The main flow kept using `_dbContext` (`SaveChangesAsync`, further queries) and the scope was eventually disposed.
2. The background `MethodAsync` was still writing via the **same** `_dbContext`.

→ Two operations interleaved writes on **one** socket → the connection was left with unread/mis-sequenced packets → returned to the pool **dirty** → the next unlucky `Open()` on that pooled connection hit `Packet received out-of-order`.

Key insight: the connection pool is process-wide, so **the code that corrupts a connection and the code that reports the error are usually different**.

### Fix

Give the background work its **own** DI scope and its own `DbContext` (matches an already-fixed sibling call in the same class):

```csharp
_ = Task.Run(async () =>
{
    using var scope = _scopeFactory.CreateScope();
    var myService = scope.ServiceProvider.GetRequiredService<IMyService>();
    await myService.MethodAsync();
});
```


### Takeaways / How to spot this

- **Never** fire-and-forget (`_ = service.XxxAsync()`) a call into a Scoped service that shares the request/message `DbContext`. The background task will outlive the scope and race the disposed context.
- A single `DbContext` (= single connection) is **not** thread-safe and must **never** be used concurrently (no un-awaited tasks, `Task.WhenAll`, or `Parallel.ForEachAsync` over the same context).
- For background/parallel work, always create a **new scope** (`IServiceScopeFactory.CreateScope()`) so each unit gets its own `DbContext`/connection.
- When you see `Packet received out-of-order` at connection open, don't trust the stack trace's location — hunt for **concurrent/abandoned DbContext usage elsewhere** in the app that shares the same pool.

**Comment by EmaX093** [comment]
> I spent a couple of hours yesterday trying to fix this with Claude - didn't get anywhere. Pipelining=false didn't help - on v2.5 as well. Tried disabling pooling, messing with timeouts, disabling connection reset, etc.
> 
> Stack trace shows the issue is coming from BeginTransactionAsync - Claude thinks 'MySqlConnector sends a SET TRANSACTION ISOLATION LEVEL or BEGIN command and ProxySQL is responding with an out-of-order packet.'
> 
> The issue is I don't know if this is an issue with MySqlConnector or ProxySQL!

Did you try to connect directly to one of the MySQL hosts to see if this is happening as well? I was having the same problem and the culprit was ProxySQL (in my case, i needed to disable pipelining to make it work): https://github.com/mysql-net/MySqlConnector/issues/1465#issuecomment-2299782175

**Comment by bfren** [comment]
I did - the clash was with ProxySQL - had to disable it in the end.
