### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by paulb2015** [mysql-net/MySqlConnector#1472]
**Software versions**
MySqlConnector version: 2.2.7 
Server type (MySQL, MariaDB, Aurora, etc.) and version: MySQL 5.7.41 & MySQL 8.0.36
.NET version: 4.8

**Describe the bug**
Our application is crashing with the following exception. This exception appears to be happening on a background thread within MySqlConnector which results in an application crash as we can't handle the exception. So far we are unable to replicate this issue as its quite rare. We are planning on upgrading the connector to the latest version, but we haven't noticed any particular fix for this issue.

**Exception**
System.NullReferenceException: Object reference not set to an instance of an object.
   at MySqlConnector.Core.ServerSession.<>c__DisplayClass99_0.<OpenTcpSocketAsync>b__0() in /_/src/MySqlConnector/Core/ServerSession.cs:line 1102
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationCallbackInfo.ExecuteCallback()
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)

**Comment by bgrainger** [comment]
https://github.com/mysql-net/MySqlConnector/blob/2.2.7/src/MySqlConnector/Core/ServerSession.cs#L1102

There may be a race condition in cancelling the `TcpClient` (in the background) and cancelling it on the main thread. Is anything being logged?

**Comment by feiazifeiazi** [comment]
me,too 
MySqlConnector version: 2.3.5

[TargetSite]=Void ExecuteCallbackHandlers(Boolean)
[Inner Error Message]=Object reference not set to an instance of an object.
[Inner Exception Type]=System.NullReferenceException
[Inner Source]=MySqlConnector
[Inner Stack Trace]=   at MySqlConnector.Core.ServerSession.<>c__DisplayClass111_0.<OpenTcpSocketAsync>b__0() in /_/src/MySqlConnector/Core/ServerSession.cs:line 1011
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
[Inner TargetSite]=Void <OpenTcpSocketAsync>b__0()

**Comment by bgrainger** [comment]
Same line: https://github.com/mysql-net/MySqlConnector/blob/2.3.5/src/MySqlConnector/Core/ServerSession.cs#L1011

(This code hasn't changed between 2.2.7 and 2.3.5.)

**Comment by bgrainger** [comment]
This is fixed in [2.3.7](https://github.com/mysql-net/MySqlConnector/releases/tag/2.3.7).
