### ISSUE TITLE
FormatException in TryPingAsync

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#162]
@ejball reported this exception. Need to check if this is a known failure response that should be handled accordingly.

```
System.FormatException: Expected to read 0x00 but got 0x01
   at MySql.Data.ByteArrayReader.ReadByte(Byte value)
   at MySql.Data.Serialization.OkPayload.Create(PayloadData payload)
   at MySql.Data.Serialization.MySqlSession.<TryPingAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.ConnectionPool.<GetSessionAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
```

**Comment by bgrainger** [comment]
Seems like it might be good (for diagnostics purposes) to log more of the incoming data.

**Comment by bgrainger** [comment]
More examples:

```
Exception: System.FormatException: Expected to read 0x00 but got 0x03
   at MySql.Data.ByteArrayReader.ReadByte(Byte value)
   at MySql.Data.Serialization.OkPayload.Create(PayloadData payload)
   at MySql.Data.Serialization.MySqlSession.<TryPingAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.ConnectionPool.<GetSessionAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
```

```
System.FormatException: Expected to read 0x00 but got 0x04
   at MySql.Data.ByteArrayReader.ReadByte(Byte value)
   at MySql.Data.Serialization.OkPayload.Create(PayloadData payload)
   at MySql.Data.Serialization.MySqlSession.<TryPingAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.ConnectionPool.<GetSessionAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
```

Call stack appears to always be the same, but the data being read can vary (seen values `0x01`, `0x03`, `0x04`).

**Comment by bgrainger** [comment]
I wrote some diagnostic code that dumped more of the unexpected data, and it was always a [result set](https://dev.mysql.com/doc/internals/en/com-query-response.html#packet-ProtocolText::Resultset). The "but got" value was the length-encoded number of columns (so the values 1, 3, and 4 were a function of the typical queries being run by the client).

This seems to indicate that an active session was somehow returned to the pool, possibly due to incomplete/incorrect cancellation support. We haven't reproduced this issue since 0.17.0 was released. Closing for now; will reopen if it reoccurs.

**Comment by ElderJames** [comment]
We got the same exception in version 2.2.5 and Pomelo EF Core 6.0.2.

```
System.FormatException: Expected to read 0x00 or 0xFE but got 0x01
   at MySqlConnector.Protocol.Payloads.OkPayload.Create(ReadOnlySpan`1 span, Boolean deprecateEof, Boolean clientSessionTrack) in /_/src/MySqlConnector/Protocol/Payloads/OkPayload.cs:line 33
   at MySqlConnector.Core.ServerSession.FinishQuerying() in /_/src/MySqlConnector/Core/ServerSession.cs:line 330
   at MySqlConnector.MySqlConnection.FinishQuerying(Boolean hasWarnings) in /_/src/MySqlConnector/MySqlConnection.cs:line 890
   at MySqlConnector.MySqlDataReader.DisposeAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 629
   at MySqlConnector.MySqlDataReader.Dispose(Boolean disposing) in /_/src/MySqlConnector/MySqlDataReader.cs:line 446
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 488
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 345
   at MySqlConnector.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in /_/src/MySqlConnector/MySqlCommand.cs:line 278
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)


```

**Comment by bgrainger** [comment]
Can you capture and post a packet capture?

**Comment by bgrainger** [comment]
In lieu of a packet capture, can you provide sample code that reproduces the problem?

**Comment by okramarenko** [comment]
Hi @bgrainger ! 

My name is Olha and I'm working on SingleStoreConnector that we adapted using your MySqlConnector and our customer faced pretty much the same issue as @ElderJames. 

`System.FormatException: Expected to read 0x00 or 0xFE but got 0x03`

When it happens they also see the following warning message logged by the client
`Session14.4 should have SessionStateExpected Connected but was SessionState ClearingPendingCancellation`

They have communicated they can’t repro the issue since they do not know the pattern of the issue occurrence, which appears to be random.

The full stack trace of the error is:
```
at SingleStoreConnector.Protocol.Payloads.OkPayload.Create(ReadOnlySpan`1 span, Boolean deprecateEof, Boolean clientSessionTrack) in C:\Users\circleci\project\src\SingleStoreConnector\Protocol\Payloads\OkPayload.cs:line 33
at SingleStoreConnector.Core.ServerSession.FinishQuerying() in C:\Users\circleci\project\src\SingleStoreConnector\Core\ServerSession.cs:line 342
at SingleStoreConnector.SingleStoreConnection.FinishQuerying(Boolean hasWarnings) in C:\Users\circleci\project\src\SingleStoreConnector\SingleStoreConnection.cs:line 892
at SingleStoreConnector.SingleStoreDataReader.DisposeAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Users\circleci\project\src\SingleStoreConnector\SingleStoreDataReader.cs:line 635
at SingleStoreConnector.SingleStoreDataReader.Dispose(Boolean disposing) in C:\Users\circleci\project\src\SingleStoreConnector\SingleStoreDataReader.cs:line 445
at SingleStoreConnector.SingleStoreCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Users\circleci\project\src\SingleStoreConnector\SingleStoreCommand.cs:line 302
at SingleStoreConnector.SingleStoreTransaction.CommitAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Users\circleci\project\src\SingleStoreConnector\SingleStoreTransaction.cs:line 40
```

Could you please recommend on what should I look for to try resolve this issue? Thanks in advance!

**Comment by bgrainger** [comment]
Capturing detailed logging (at Debug level, maybe at Trace) might help show what's going on.
