### ISSUE TITLE
Throwing InvalidOperationException on OpenAsync

### ISSUE THREAD

**Issue by alanprot** [mysql-net/MySqlConnector#210]
I don't know exactly the cause but sometimes i start to get InvalidOperationException on all mysql call and i have to restart the process...

```
message=Packet received out-of-order. Expected 1; got 2., stackTrace=   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at MySql.Data.ValueTaskExtensions.ContinueWith[T,TResult](ValueTask`1 valueTask, Func`2 continuation)
   at MySql.Data.Protocol.Serialization.ProtocolUtility.ReadPayloadAsync(BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ArraySegment`1 previousPayloads, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior)
   at MySql.Data.Protocol.Serialization.StandardPayloadHandler.ReadPayloadAsync(ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior)
   at MySql.Data.Serialization.MySqlSession.TryAsync(Func`3 func, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySql.Data.Serialization.MySqlSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySql.Data.Serialization.MySqlSession.<TryPingAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.ConnectionPool.<GetSessionAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>```

**Comment by caleblloyd** [comment]
What version of MySqlConnector and MySQL server? What is your connection string (without user/pass)

**Comment by alanprot** [comment]
Hi :D
MySql Connector: ```0.14.1```
MySql: ```MySQL 5.6.27 ```
ConnectionString: ```{HOST}; DATABASE={DB}; UID=******; Password=*******; MaximumPoolsize=200; SslMode=None```

Thanks

**Comment by bgrainger** [comment]
Seems similar to #162 (both have an exception ultimately coming from `TryPingAsync`).

We could just catch that exception, of course, but I'd like to really understand why it's happening. Pulling a connection off the pool should not should be throwing an exception about unexpected data, because that session should have been cleaned up before the connection was returned to the pool.

**Comment by caleblloyd** [comment]
The `Packet received out-of-order. Expected 1; got 2` portion of the message makes me wonder if there's still data in the read buffer of a previously pooled connection.

Disposing a reader when connection closed was fixed in #198 and shipped in `0.14.1`, so improper disposal should not be the issue here.  Maybe we need a better method for disposing a reader and ensuring that the underlying buffers have been reset.

**Comment by alanprot** [comment]
I noticed that the numbers of connections increase a lot (and still large until i restart the process) and the CPU has a huge spike when it occurs.

**Comment by bgrainger** [comment]
Similar to #162 this appears to be due to an active session being returned to the pool. @alanprot can you test with 0.17.0 (or later) and reopen this bug if you still experience the problem?
