### ISSUE TITLE
Fix spurious Appveyor build failures

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#246]
The Appveyor build is failing much more than it should. Some recent failures:

```
Executing tests with No Compression, No SSL
Test run for C:\projects\mysqlconnector\tests\SideBySide\bin\Release\net462\SideBySide.dll(.NETFramework,Version=v4.6.2)
Failed   SideBySide.ConnectionPool.ExhaustConnectionPoolWithTimeout
Error Message:
 Assert.InRange() Failure
Range:  (4500 - 5500)
Actual: 5811
Stack Trace:
   at SideBySide.ConnectionPool.<ExhaustConnectionPoolWithTimeout>d__2.MoveNext() in C:\projects\mysqlconnector\tests\SideBySide\ConnectionPool.cs:line 0
```

[build 1](https://ci.appveyor.com/project/mysqlnet/mysqlconnector/build/1.0.462), [build 2](https://ci.appveyor.com/project/mysqlnet/mysqlconnector/build/1.0.489), [build 3](https://ci.appveyor.com/project/mysqlnet/mysqlconnector/build/1.0.492), [build 4](https://ci.appveyor.com/project/mysqlnet/mysqlconnector/build/1.0.502)

```
Executing baseline tests with No Compression, No SSL
Test run for C:\projects\mysqlconnector\tests\SideBySide\bin\Baseline\net462\SideBySide.dll(.NETFramework,Version=v4.6.2)
Failed   SideBySide.BulkLoaderSync.BulkLoadCsvFileNotFound
Error Message:
 MySql.Data.MySqlClient.MySqlException : Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
---- System.TimeoutException : Timeout in IO operation
```

[build](https://ci.appveyor.com/project/mysqlnet/mysqlconnector/build/1.0.467)

```
Executing tests with Compression, No SSL
Test run for C:\projects\mysqlconnector\tests\SideBySide\bin\Release\net462\SideBySide.dll(.NETFramework,Version=v4.6.2)
Failed   SideBySide.ConnectSync.ConnectTimeout
Error Message:
 Assert.InRange() Failure
Range:  (2800 - 3500)
Actual: 3589
Stack Trace:
   at SideBySide.ConnectSync.ConnectTimeout() in C:\projects\mysqlconnector\tests\SideBySide\ConnectSync.cs:line 209
```

[build 1](https://ci.appveyor.com/project/mysqlnet/mysqlconnector/build/1.0.469), [build 2](https://ci.appveyor.com/project/mysqlnet/mysqlconnector/build/1.0.495), [build 3](https://ci.appveyor.com/project/mysqlnet/mysqlconnector/build/1.0.488)

```
Executing baseline tests with No Compression, No SSL
Test run for C:\projects\mysqlconnector\tests\SideBySide\bin\Baseline\net462\SideBySide.dll(.NETFramework,Version=v4.6.2)
Failed   SideBySide.DataTypes.InsertLargeBlobSync(column: "LongBlob", size: 67108864)
Error Message:
 MySql.Data.MySqlClient.MySqlException : Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
---- System.TimeoutException : Timeout in IO operation
```

[build](https://ci.appveyor.com/project/mysqlnet/mysqlconnector/build/1.0.473)

```
Executing tests with Compression, No SSL
Test run for C:\projects\mysqlconnector\tests\SideBySide\bin\Release\net462\SideBySide.dll(.NETFramework,Version=v4.6.2)
Failed   SideBySide.CancelTests.CancelSlowQueryWithTokenAfterNextResult
Error Message:
 Assert.InRange() Failure
Range:  (450 - 2250)
Actual: 4147

Test run for C:\projects\mysqlconnector\tests\SideBySide\bin\Release\netcoreapp1.1.1\SideBySide.dll(.NETCoreApp,Version=v1.1.1)
Failed   SideBySide.CancelTests.CancelSlowQueryWithTokenAfterExecuteReader
Error Message:
 Assert.InRange() Failure
Range:  (450 - 2250)
Actual: 2550
```

[build 1](https://ci.appveyor.com/project/mysqlnet/mysqlconnector/build/1.0.528), [build 2](https://ci.appveyor.com/project/mysqlnet/mysqlconnector/build/1.0.513), [build 3](https://ci.appveyor.com/project/mysqlnet/mysqlconnector/build/1.0.520), [build 4](https://ci.appveyor.com/project/mysqlnet/mysqlconnector/build/1.0.521), [build 5](https://ci.appveyor.com/project/mysqlnet/mysqlconnector/build/1.0.523)

```
Executing baseline tests with No Compression, No SSL
Test run for C:\projects\mysqlconnector\tests\SideBySide\bin\Baseline\net462\SideBySide.dll(.NETFramework,Version=v4.6.2)
Failed   SideBySide.CancelTests.CancelCommandBeforeRead
Error Message:
 Assert.InRange() Failure
Range:  (0 - 6000)
Actual: 13998
```

[build](https://ci.appveyor.com/project/mysqlnet/mysqlconnector/build/1.0.512)

**Comment by bgrainger** [comment]
Some recent increases to timeout values (e.g., 1f0215dbd98373735c8313b043ae2a4afaaf93dd) appear to have mitigated this problem sufficiently (for now...).
