### ISSUE TITLE
NotSupportedException calling AddWithValue with enum

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#255]
Calling `command.Parameters.AddWithValue("@name", SomeEnum.Value)` throws the following exception:

```
 System.NotSupportedException : Parameter type SomeEnum (DbType: AnsiString) not currently supported. Value: Value
Stack Trace:
   at MySql.Data.MySqlClient.MySqlParameter.AppendSqlString(BinaryWriter writer, StatementPreparerOptions options)
   at MySql.Data.MySqlClient.MySqlStatementPreparer.ParameterSqlParser.DoAppendParameter(Int32 parameterIndex, Int32 textIndex, Int32 textLength)
   at MySql.Data.MySqlClient.MySqlStatementPreparer.ParameterSqlParser.OnNamedParameter(Int32 index, Int32 length)
   at MySql.Data.MySqlClient.MySqlParser.Parse(String sql)
   at MySql.Data.MySqlClient.MySqlStatementPreparer.ParseAndBindParameters()
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteReaderAsync>d__3.MoveNext()
```

**Comment by bgrainger** [comment]
Fixed in [0.19.3](https://www.nuget.org/packages/MySqlConnector/0.19.3).
