### ISSUE TITLE
Connecting to Azure MySQL fails

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#259]
Create an Azure MySQL 5.7 instance and attempt to connect to it.

A `NullReferenceException` is thrown:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at MySql.Data.MySqlClient.MySqlConnection.CloseDatabase()
   at MySql.Data.MySqlClient.MySqlConnection.DoClose()
   at MySql.Data.MySqlClient.MySqlConnection.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at Program.<DoStuffAsync>d__1.MoveNext() in C:\Program.cs:line 10
```

After fixing this bug in `CloseDatabase`, we get the underlying exception:

```
Unhandled Exception: System.FormatException: Expected to read 0x00 but got 0xFE
   at MySql.Data.ByteArrayReader.ReadByte(Byte value)
   at MySql.Data.Serialization.OkPayload.Create(PayloadData payload)
   at MySql.Data.Serialization.MySqlSession.<ConnectAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at MySql.Data.MySqlClient.ConnectionPool.<GetSessionAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__66.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
```

When connecting, we are expecting to get an OK packet, but the server is sending a change authentication packet instead.

**Comment by bgrainger** [comment]
Fixed in [0.19.3](https://www.nuget.org/packages/MySqlConnector/0.19.3).

**Comment by Kagamine** [comment]
For networking issues, please feel free to contact with Xiangyu. He will help you to solve these.

**Comment by bgrainger** [comment]
This bug was due to Azure Database for MySQL not supporting "fast path" authentication; I've made a [suggestion on the MSDN forums](https://social.msdn.microsoft.com/Forums/en-US/7a6eac36-3e5d-4659-b522-9d6c2f93801a/fast-authentication-path-should-be-supported?forum=AzureDatabaseforMySQL).

**Comment by Kagamine** [comment]
Tracking in TFS #51448, If there are any news, I will post here.
