### ISSUE TITLE
NullReferenceException at MySqlClient/ConnectionPool.cs#L38, version 0.20.1

### ISSUE THREAD

**Issue by mzji** [mysql-net/MySqlConnector#274]
Full call stack:
```
[2017-06-18 02:41:59 821] Object reference not set to an instance of an object.
SQL statement:SELECT * FROM `person`

[2017-06-18 02:42:00 313] Exception happens at /test : System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.LinkedList`1.InternalRemoveNode(LinkedListNode`1 node)
   at System.Collections.Generic.LinkedList`1.RemoveFirst()
   at MySql.Data.MySqlClient.ConnectionPool.<GetSessionAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at SXLibraryCore.SXDbAppendable.Pre() in C:\PROJECT_PATH\SXLibraryCore\SXLibraryCore\DBHelper.cs:line 641
   at SXLibraryCore.SXDbAppendable.GetDataTable() in C:\PROJECT_PATH\SXLibraryCore\SXLibraryCore\DBHelper.cs:line 686
   at SXLibraryCore.DbConnectionHelper.GetDataTable(DbConnection conn, String sqlStr, CommandType cmdType, Dictionary`2 arguments) in C:\PROJECT_PATH\SXLibraryCore\SXLibraryCore\DBHelper.cs:line 324
   at LoggingTester.Controllers.TestController.Index() in C:\PROJECT_PATH\ClientDemo\ClientDemo\Controllers\TestController.cs:line 26
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Core.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Core.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Core.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Core.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Core.Internal.ResourceInvoker.<InvokeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
```
Envrionment: Windows Server 2012R2 x64 / IIS 8 / ASP.Net Core 2.0 Preview 1 / 0.20.1

**Comment by bgrainger** [comment]
The top of the callstack seems the most relevant:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.LinkedList`1.InternalRemoveNode(LinkedListNode`1 node)
   at System.Collections.Generic.LinkedList`1.RemoveFirst()
   at MySql.Data.MySqlClient.ConnectionPool.<GetSessionAsync>d__0.MoveNext()
```

And here's the corresponding code in MySqlConnector:

```
lock (m_sessions)
{
	if (m_sessions.Count > 0)
	{
		session = m_sessions.First.Value;
		m_sessions.RemoveFirst();
	}
}
```

It can't be the case that `m_sessions == null`, or else this code would have crashed on `m_sessions.Count` or `m_sessions.First`.

This looks like an error within `LinkedList` itself (as improbable as that sounds). Now, this could be caused by concurrent mutation of the object on multiple threads (putting it into an internal inconsistent state) but I don't see that happening in ConnectionPool.cs; every access to `m_sessions` is protected by a `lock`.

What's your repro for this problem? Does it happen consistently when opening a connection, or just intermittently?

**Comment by bgrainger** [comment]
I noticed you also filed dotnet/corefx#21166; is it at all possible that there's some external source of memory corruption in this process?

**Comment by mzji** [comment]
In the application, all database connections are used in this form:
```
using (var conn = new MysqlConnection(connStr)) {
    // Do something…
    // The connection is always closed before running out of the using block.
}
```
And the issue will occur after 10~18 hours normally running. So this issue happens intermittently, I think.
Actually IDK if there exists an external memory corruption or not; however since the call stack indicates that some code in MysqlConnector is involved before the exception is threw, I opened this issue and hopes that any one would find the culprit out.
BTW, the database is a MariaDb 10.1 instance, could this be the reason behind?

**Comment by bgrainger** [comment]
The problem appears to be in `LinkedList` (it's a `NullReferenceException` coming from its internal methods, not an `ArgumentException` from MySqlConnector using it improperly).

It feels very unlikely to me that there is actually a bug in `LinkedList`. I double-checked all usages of `m_sessions` in this code and all are protected by a lock, so it doesn't seem likely to be caused by incorrect concurrent usage. (Plus we have performance tests that operate at a very high concurrency level and haven't uncovered this bug.)

I suspect some external source of corruption of program state, but can't prove anything. If this were my crash, I would capture a full crash dump (using ProcDump or similar) then analyze it in WinDbg for further clues.
