### ISSUE TITLE
 Unable to connect to any of the specified MySQL hosts.

### ISSUE THREAD

**Issue by Kagamine** [mysql-net/MySqlConnector#298]
An error occurred using the connection to database 'joyoi_mgmtsvc' on server '127.0.0.1'.
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySql.Data.Serialization.MySqlSession.<ConnectAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.ConnectionPool.<GetSessionAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenAsync>d__34.MoveNext()

**Comment by Kagamine** [comment]
I am using pomelo and mysqlconnector to build a service, but it will always throw this exception when the service started a period

**Comment by caleblloyd** [comment]
Can you connect from the command line client? This usually just means there is no MySQL server on that host/port

**Comment by caleblloyd** [comment]
If the service is running at system start maybe it's trying to connect before MySQL is ready. You could put a simple try/catch that tries to connect for 60 seconds and sleeps 1 second if it catches MySqlException in your startup logic

**Comment by Kagamine** [comment]
workbench is ok, just the mysqlconnector cannot connect to the server

**Comment by Kagamine** [comment]
It will work about 2~3h and then throw the unable to connect mysql server exception

**Comment by Kagamine** [comment]
Closing this because we have also used the Docker.DotNet, They did not dispose http client and exhaust socket. (https://github.com/Microsoft/Docker.DotNet/pull/216)

**Comment by linehammer** [comment]
In some of the ways, spacing and the order of parameters in the MySql connection string does matters.

So stick to the standard format 

`MysqlConn.ConnectionString = "Server=yourServerAddress; Port=1234; Database=myourdb; Uid=uid; Pwd=pass;`

If the above connection string fails,  try update your [c# mysql](http://net-informations.com/q/faq/mysql.html) connection string as shown below (without port variable as well):

`MysqlConn.ConnectionString = "Server=127.0.0.1;Database=yourdb;Uid=uid;Pwd=pass;"`
