### ISSUE TITLE
MySqlConnection.Dispose() throwing System.InvalidOperationException: MySqlSession is not connected.?

### ISSUE THREAD

**Issue by jemiller0** [mysql-net/MySqlConnector#400]
I'm wondering if I'm running into an issue similar to #383 where an exception is being thrown when calling Dispose() on a connection. I think this is masking the original exception the occurred. I think it may be a timeout error. I'm having a hard time interpreting the following stack trace. I see that Dispose() is being called, but, the exception is happening in ReceiveReplyAsync(). I think maybe the connection is timing out, that throws an exception, then Dispose() is called on the connection. That tries to close an open DataReader on the connection, which throws the exception. I'm thinking maybe DataReader.Dispose() is trying to read any remaining data from the connection as part of the close process. It is just a theory. I'm having a hard time interpreting the stack trace, which may be in part due to the fact that the exception is happening in a parrallel for in my application.

```
OleConsoleApplication Critical: 0 : System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: MySqlSession is not connected.
   at MySql.Data.Serialization.MySqlSession.VerifyConnected()
   at MySql.Data.Serialization.MySqlSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.Serialization.MySqlSession.TryAsyncContinuation(Task`1 task)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.Results.ResultSet.<<ScanRowAsync>g__ScanRowAsyncAwaited9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at MySql.Data.MySqlClient.Results.ResultSet.<ReadAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.Results.ResultSet.<ReadEntireAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<NextResultAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.DoClose()
   at MySql.Data.MySqlClient.MySqlDataReader.Dispose(Boolean disposing)
   at MySql.Data.MySqlClient.MySqlConnection.CloseDatabase()
   at MySql.Data.MySqlClient.MySqlConnection.DoClose()
   at MySql.Data.MySqlClient.MySqlConnection.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at OleLibrary.OleDapperContext.Dispose() in C:\Users\jemiller\Documents\Visual Studio 2017\Projects\Ole2\OleLibrary\OleDapperContext.cs:line 2553
   at OleConsoleApplication.Program.LoadEditions(Boolean truncate, Boolean required, Boolean dependent, Boolean constraints, Boolean indexes) in C:\Users\jemiller\Documents\Visual Studio 2017\Projects\Ole2\OleConsoleApplication\Program.cs:line 36751
   at OleConsoleApplication.Program.<>c.<Load>b__4_0(Action`5 a) in C:\Users\jemiller\Documents\Visual Studio 2017\Projects\Ole2\OleConsoleApplication\Program.cs:line 4093
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at OleConsoleApplication.Program.Load(Boolean truncate, Nullable`1 threads) in C:\Users\jemiller\Documents\Visual Studio 2017\Projects\Ole2\OleConsoleApplication\Program.cs:line 4093
   at OleConsoleApplication.Program.Main(String[] args) in C:\Users\jemiller\Documents\Visual Studio 2017\Projects\Ole2\OleConsoleApplication\Program.cs:line 2448
---> (Inner Exception #0) System.InvalidOperationException: MySqlSession is not connected.
   at MySql.Data.Serialization.MySqlSession.VerifyConnected()
   at MySql.Data.Serialization.MySqlSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.Serialization.MySqlSession.TryAsyncContinuation(Task`1 task)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.Results.ResultSet.<<ScanRowAsync>g__ScanRowAsyncAwaited9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at MySql.Data.MySqlClient.Results.ResultSet.<ReadAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.Results.ResultSet.<ReadEntireAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<NextResultAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.DoClose()
   at MySql.Data.MySqlClient.MySqlDataReader.Dispose(Boolean disposing)
   at MySql.Data.MySqlClient.MySqlConnection.CloseDatabase()
   at MySql.Data.MySqlClient.MySqlConnection.DoClose()
   at MySql.Data.MySqlClient.MySqlConnection.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at OleLibrary.OleDapperContext.Dispose() in C:\Users\jemiller\Documents\Visual Studio 2017\Projects\Ole2\OleLibrary\OleDapperContext.cs:line 2553
   at OleConsoleApplication.Program.LoadEditions(Boolean truncate, Boolean required, Boolean dependent, Boolean constraints, Boolean indexes) in C:\Users\jemiller\Documents\Visual Studio 2017\Projects\Ole2\OleConsoleApplication\Program.cs:line 36751
   at OleConsoleApplication.Program.<>c.<Load>b__4_0(Action`5 a) in C:\Users\jemiller\Documents\Visual Studio 2017\Projects\Ole2\OleConsoleApplication\Program.cs:line 4093
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
```

**Comment by bgrainger** [comment]
Yes, this exception (from `Dispose`) is masking your original exception.

I've been reluctant to just throw the bodies of `Dispose` methods in a big `try`/`catch` block as that could mask legitimate bugs (that I would like to know about). 

I should be able to suppress this particular problem, but would be interested in knowing what original exception put you in this state (if you're able to determine that).

**Comment by jemiller0** [comment]
Thanks. The exception is occurring in an application that bulk loads data. The last time it ran, it failed after about 5 hours. I'm starting another test run now. I put a try/catch block inside the using statement that is calling Dispose. So, I hope to find out what the original exception is. My main guess is that it is a command or connection timeout. I'm loading multiple tables in parallel and dropping and recreating foreign key constraints and indexes. It's possible that it's getting into a dead lock and timing out. Will let you know once I find out more.

**Comment by jemiller0** [comment]
I ran the application again and was able to get the following more simplified stack trace. I'm doing a query using Dapper and iterating over the results. Not sure if the server is just closing the remote connection. I'm going to check the server log and see if I can see anything. And also, I'm going to try Oracle's driver and see if that works or if it throws an exception that might help troubleshooting the problem.

```
OleConsoleApplication Critical: 0 : System.InvalidOperationException: MySqlSession is not connected.
   at MySql.Data.Serialization.MySqlSession.VerifyConnected()
   at MySql.Data.Serialization.MySqlSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.Serialization.MySqlSession.TryAsyncContinuation(Task`1 task)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.Results.ResultSet.<<ScanRowAsync>g__ScanRowAsyncAwaited9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at MySql.Data.MySqlClient.Results.ResultSet.<ReadAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.Results.ResultSet.<ReadEntireAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<NextResultAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.DoClose()
   at MySql.Data.MySqlClient.MySqlDataReader.Dispose(Boolean disposing)
   at Dapper.SqlMapper.<QueryImpl>d__125`1.<>m__Finally1()
   at Dapper.SqlMapper.<QueryImpl>d__125`1.System.IDisposable.Dispose()
   at Dapper.SqlMapper.<QueryImpl>d__125`1.MoveNext()
   at OleConsoleApplication.Program.LoadLocalCode1s(Boolean truncate, Boolean required, Boolean dependent, Boolean constraints, Boolean indexes) in C:\Users\jemiller\Documents\Visual Studio 2017\Projects\Ole2\OleConsoleApplication\Program.cs:line 60616
    ThreadId=3
    DateTime=2017-11-21T03:08:19.7827882Z

```

**Comment by jemiller0** [comment]
I'm going to close this out. It looks like the connections are getting disconnected. It is a mystery as to why, but, doesn't seem to have to do with the Dispose() method. Also, I found that it happens with Oracle's driver as well. I have had intermittent problems like this for a while now and have yet to figure out what is going on. I see errors like the following in the server log. I have found that MySqlConnector, while it still has problems like this, is better than Oracle's driver. Also, I have had issues with slow bulk insert/update performance. I have code that works with MySQL, PostgreSQL, and SQL Server and MySQL is always like 4 times as slow as the others.

```
2017-11-21T12:29:05.286349Z 262 [Note] Aborted connection 262 to db: 'ole3' user: 'root' host: 'localhost' (Got an error reading communication packets)
2017-11-21T12:29:05.286349Z 258 [Note] Aborted connection 258 to db: 'ole3' user: 'root' host: 'localhost' (Got an error reading communication packets)
2017-11-21T12:29:05.755141Z 252 [Note] Aborted connection 252 to db: 'ole3' user: 'root' host: 'localhost' (Got an error writing communication packets)
2017-11-21T12:40:25.545389Z 10 [Note] Aborted connection 10 to db: 'ole' user: 'root' host: 'localhost' (Got timeout reading communication packets)
2017-11-21T13:06:36.734563Z 7 [Note] Aborted connection 7 to db: 'ole3' user: 'root' host: 'localhost' (Got timeout reading communication packets)


```
