### ISSUE TITLE
Exception when password contain ;

### ISSUE THREAD

**Issue by zokiad** [mysql-net/MySqlConnector#451]
Hi,

This connectionstring generate an exception:

```C#
Connection = new MySqlConnection("host=127.0.0.1;port=3306;user id=mysqltest;password=Password;123;database=mysqldb;");
```

```cpp
{System.ArgumentException: Option '123;database' not supported.
   at MySql.Data.MySqlClient.MySqlConnectionStringOption.GetOptionForKey(String key) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnectionStringBuilder.cs:line 298
   at MySql.Data.MySqlClient.MySqlConnectionStringBuilder.set_Item(String key, Object value) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnectionStringBuilder.cs:line 226
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at MySqlConnector.Core.ConnectionPool.GetPool(String connectionString) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 355
   at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__83.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 376
   at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__25.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 169
   at MySql.Data.MySqlClient.MySqlConnection.Open() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 155
....
```

Because it contain character ;
How to define a connection string with ; character ?

with mysql connector, same connection string work fine.

Regards

**Comment by zokiad** [comment]
I response to me.

with quote, it's work: password=';'

**Comment by bgrainger** [comment]
Don't build connection strings with string concatenation; use `MySqlConnectionStringBuilder`:

```
var connectionStringBuilder = new MySqlConnectionStringBuilder
{
    UserID = "mysqltest",
    Password = "Password;123",
    // etc.
};
```

**Comment by zokiad** [comment]
Ok thanks for your help
