### ISSUE TITLE
Exception InvalidOperationException with dapper and transaction

### ISSUE THREAD

**Issue by zokiad** [mysql-net/MySqlConnector#452]
Hi,

I try to execute a insert with dapper in a transaction:

```C#
            using (MySql.Data.MySqlClient.MySqlConnection conn = new MySql.Data.MySqlClient.MySqlConnection("server=XXX;user id=Test;password=Test;database=Test"))
            {
                conn.Open();

                using (MySqlTransaction trans = conn.BeginTransaction())
                {
                    string test = "";
 
                    conn.Execute(@"INSERT INTO Test(@test)", new { test = test });
                    trans.Commit();
                }
            }
```

On execute, i have this exception:

System.InvalidOperationException
  HResult=0x80131509
  Message=The transaction associated with this command is not the connection's active transaction.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 60
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in C:\projects\dapper\Dapper\SqlMapper.cs:line 2827
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in C:\projects\dapper\Dapper\SqlMapper.cs:line 570
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 443

Follow the test project:
[TestMysqlconnector.zip](https://github.com/mysql-net/MySqlConnector/files/1813219/TestMysqlconnector.zip)

I use:
- Visual studio 15.6.2
- MySqlConnector 0.36.1
- Dapper 1.50.4
- .NET Core v2.1.0-preview1-26216.03

This code work fine with mysql connector of Oracle.

Regards

**Comment by bgrainger** [comment]
MySqlConnector currently requires the active transaction to be specified (to catch programming errors); this is a known breaking change from Oracle's Connector/NET. To do this with Dapper, write:

    conn.Execute(@"INSERT INTO Test(@test)", new { test = test }, trans);

See this comment for the full explanation: https://github.com/mysql-net/MySqlConnector/issues/405#issuecomment-347018155

**Comment by zokiad** [comment]
Ok thanks. It is work fine with transaction parameter.

**Comment by bgrainger** [comment]
For future reference, you can also opt in to the Connector/NET behaviour by adding `IgnoreCommandTransaction=true` to your connection string (in 0.39.0 and later).

**Comment by zokiad** [comment]
Is there a difference in performance?

**Comment by bgrainger** [comment]
No, there is no difference in performance when setting that option.
