### ISSUE TITLE
Exception when use unbuffered dapper QueryAsync

### ISSUE THREAD

**Issue by zokiad** [mysql-net/MySqlConnector#523]
Hi,

I use .net core 2.1.1.

Follow a example test to read data with dapper without buffered data (simplify test):

```C#
using Dapper;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;


namespace ConsoleApp11
{
    class Program
    {
        public class SelectResult
        {
            public long Id { get; set; }
            public DateTime CreatedDate { get; set; }
        }

        static async Task Test()
        {
            using (MySqlConnection conn = new MySqlConnection("server=SERVER;user id=USERID;password=PASS;database=DATABASE;"))
            {
                await conn.OpenAsync();
                using (MySqlTransaction transaction = await conn.BeginTransactionAsync(IsolationLevel.RepeatableRead))
                {
                    Task<IEnumerable<SelectResult>> task = conn.QueryAsync<SelectResult, DateTime, SelectResult>(@"
SELECT Id, CreatedDate
FROM Photos
LIMIT 10;"
, (param1, param2) =>
{
    return param1;
}, null, transaction, false, "CreatedDate", 3600);

                    foreach (SelectResult id in await task)
                        Console.WriteLine(id.Id);
                }
            }
        }

        static void Main(string[] args)
        {
            Task t = Test();
            t.Wait();
        }
    }
}
```

Create database:

```SQL
CREATE TABLE `Photos` (
  `Id` bigint(20) NOT NULL AUTO_INCREMENT,
  `CreatedDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
) ;

```

Issue:

When execute code, exception is throwed:

System.InvalidOperationException: Can't call this method when MySqlDataReader is closed.
   at MySql.Data.MySqlClient.MySqlDataReader.VerifyNotDisposed() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 469
   at MySql.Data.MySqlClient.MySqlDataReader.GetResultSet() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 475
   at MySql.Data.MySqlClient.MySqlDataReader.get_FieldCount() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 167
   at Dapper.SqlMapper.GetColumnHash(IDataReader reader, Int32 startBound, Int32 length) in C:\projects\dapper\Dapper\SqlMapper.cs:line 41
   at Dapper.SqlMapper.MultiMapImpl[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, CommandDefinition command, Delegate map, String splitOn, IDataReader reader, Identity identity, Boolean finalize)+MoveNext() in C:\projects\dapper\Dapper\SqlMapper.cs:line 1426
   at ConsoleApp11.Program.Test() in c:\users\christophe\documents\visual studio 2017\Projects\ConsoleApp11\ConsoleApp11\Program.cs:line 34

Work fine with mysql connector of Oracle
Work fine if modify buffered to true.
Work fine if use Query (not async)

**Comment by bgrainger** [comment]
Thanks for the bug report; I can reproduce the exception with this code.

**Comment by bgrainger** [comment]
This is a bug in Dapper; unbuffered `QueryAsync` closes the `DbDataReader` before reading the results: StackExchange/Dapper#596

(The result it "Works fine with mysql connector of Oracle" is that Oracle's Connector/NET [isn't actually async](https://bugs.mysql.com/bug.php?id=70111). But other async connectors, such as `SqlConnection` also have the same problem.)

**Comment by zokiad** [comment]
Ok thanks.
