### ISSUE TITLE
Unable to connect to any of the specified MySQL hosts after alot of success connection

### ISSUE THREAD

**Issue by locskeleton** [mysql-net/MySqlConnector#539]
My service throw exception after huge numners of success connections query to db. It seem occur when high load. Is there any problems with ConnectionPool when running in case of high load connections?

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> MySql.Data.MySqlClient.MySqlException: Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.<ConnectAsync>d__56.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 259
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MySqlConnector.Core.ConnectionPool.<GetSessionAsync>d__10.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 111
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MySqlConnector.Core.ConnectionPool.<GetSessionAsync>d__10.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__91.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 400
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__25.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 179
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.Open() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 157
   at Micro.ORM.Dapper.Database`1.Open(IDbConnection connection, Nullable`1 commandTimeout)
   at LauncherService.LauncherServiceHandler.HierarchyTreeCategories(String gcId, Context context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Micro.Brokers.RedisBroker.HandleRequestMessage(Message`1 msg)
```

**Comment by bgrainger** [comment]
What version of MySqlConnector are you using? What variant of MySQL Server (MySQL, MariaDB, Amazon RDS, Azure, etc.) are you using, and what version?

It might help to enable logging; see https://mysql-net.github.io/MySqlConnector/overview/logging/ or use the following to log to the console:

```csharp
MySqlConnectorLogManager.Provider = new ConsoleLoggerProvider(MySqlConnectorLogLevel.Debug);
```

Can you provide a little more detail about how your code is actually structured, or (ideally) a small sample that reproduces the problem? Can you provide the source code of `LauncherService.LauncherServiceHandler.HierarchyTreeCategories`?

**Comment by locskeleton** [comment]
Thanks you,
I'm using MySQL server version 5.7.18, on centos machine. My services running on a windows server 2012 then connect to this database server. It running smooth except when my concurrent user increase on my app. This error occur about a few hours 1 time. Other connections connect to database seem still running ok, my service not crashed.

**Comment by locskeleton** [comment]
This is my HierarchyTreeCategories function. This function only open connection and query to db to get SaleItems. Other informations are getting from redis cache:

`public override void HierarchyTreeCategories(string gcId, Context context)
        {
            var result = new List<HierarchyTree>();
            var cache = Cache.GetDictCache<Category>(CacheKey.GCP_CATEGORIES).Values;
            if (cache != null)
            {
                var tree = new List<HierarchyTree>();
                var categories = cache.Where(m => m.Enable);
                using (IDbConnection cnn = GcPartyDbContext.NewConnection())
                {
                    var db = GcPartyDb.Init();
                    db.Open(cnn);

                    var saleItems = db.SaleItems.Where(m => m.GcId == gcId && m.Enable);
                    foreach (var category in categories)
                    {
                        if (saleItems.Any(m => m.Category == category.Id.ToString()))
                        {
                            if (category.Parent.HasValue)
                            {
                                if (!tree.Any(m => m.Id == category.Parent.Value))
                                {
                                    var parent = categories.FirstOrDefault(m => m.Id == category.Parent.Value);
                                    if (parent != null)
                                    {
                                        tree.Add(new HierarchyTree
                                        {
                                            Id = parent.Id,
                                            Name = parent.Name,
                                            Root = parent.Parent,
                                            Childrens = new List<HierarchyTree>()
                                        });
                                    }
                                }
                            }

                            if (!tree.Any(m => m.Id == category.Id))
                            {
                                tree.Add(new HierarchyTree
                                {
                                    Id = category.Id,
                                    Name = category.Name,
                                    Root = category.Parent,
                                    Childrens = new List<HierarchyTree>()
                                });
                            }
                        }
                    }
                }

                // build tree
                tree.ForEach(parent => parent.Childrens = tree.Where(child => child.Root.HasValue && child.Root.Value == parent.Id).ToList());

                result = tree.Where(item => !item.Root.HasValue || item.Root == item.Id).OrderBy(m => m.Id).ToList();
            }

            ResponseData(result, context);
        }`

**Comment by bgrainger** [comment]
> except when my concurrent user increase on my app

Does the concurrent user count exceed `MaximumPoolSize` (default = 100) in your connection string?

**Comment by locskeleton** [comment]
When my app running on high load mode, concurrent users may increase to 3k, should i increase MaximumPoolSize for adapt better?

**Comment by locskeleton** [comment]
Many Thanks @bgrainger,
I enabled log, edit my code, increase connection pool size and max_connections variable. I'm monitoring logs to check this error.

**Comment by bgrainger** [comment]
Appears to be working as designed.

**Comment by locskeleton** [comment]
Resolved problem. My application connect to database server via ip wan it seem occur DDoS attack to this network line. So network unstable. We fixed all issue and everything stabled. Thanks @bgrainger !
