### ISSUE TITLE
Intermittent SSL Authentication error  

### ISSUE THREAD

**Issue by RaidMax** [mysql-net/MySqlConnector#557]
I'm getting an intermittent SSL Authentication error. I can't really find a pattern for what causes it, but it happens for about 1% of my queries.

Error Message: 
```SSL Authentication Error```
Error Trace   
```at MySqlConnector.Core.ServerSession.InitSslAsync(ProtocolCapabilities serverCapabilities, ConnectionSettings cs, SslProtocols sslProtocols, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 1114
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 382
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 143
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 143
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 428
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 195
```
The MySqlConnector is being used as a dependency of [Pomelo.EntityFrameworkCore.MySql](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql)
Version is `0.44.1`

Let me know if I can provide any more information.

**Comment by bgrainger** [comment]
Please provide the full exception message and call stack, including the inner exceptions.

What client OS and .NET Framework/Core version are you using? What is the exact provider, edition, and version of the MySQL (or compatible) server you are connecting to? Are you using a client certificate?

**Comment by RaidMax** [comment]
Thanks for the reply @bgrainger. Here is the full callstack and inner exceptions

```
[09.11.2018 03:30:41.793] - Debug: Error Message: SSL Authentication Error
[09.11.2018 03:30:41.823] - Debug: Error Trace:    at MySqlConnector.Core.ServerSession.InitSslAsync(ProtocolCapabilities serverCapabilities, ConnectionSettings cs, SslProtocols sslProtocols, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 1114
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 382
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 143
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 143
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 428
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 195
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.BeginTransactionAsync(IsolationLevel isolationLevel, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Project.Plugins.Stats.Helpers.StatManager.AddScriptHit(HitInfo info)
   at Project.Plugins.Stats.Plugin.OnEventAsync(ProjectEvent E, Server S)
   at Project.Server.ExecuteEvent(GameEvent E)
[09.11.2018 03:30:41.824] - Debug: Inner exception: Authentication failed, see inner exception.
[09.11.2018 03:30:41.824] - Debug: Inner exception: The message or signature supplied for verification has been altered
```
OS: `Windows Server 2008 R2`
`.NET Core 2.1.0`
MySQL Version: `8.0.12 for Linux on x86_64 (MySQL Community Server - GPL)`
No client certificate that I'm aware of.

**Comment by bgrainger** [comment]
Looks like fundamental problem is the final inner exception: `The message or signature supplied for verification has been altered`.

I can't find out much about this error message. It's possible there may be further information in the Windows Event Viewer.

While they don't necessarily apply to Server 2008 R2, these articles ([1](https://social.msdn.microsoft.com/Forums/en-US/df043823-ffcf-46a4-9e47-1c4b8854ca13/troubleshooting-guide-for-visual-studio-test-controller-and-agent?forum=vststest), [2](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/f0d1611a-b52b-4891-a75a-8fb653785632/issue-with-sslstream-and-windows-2008?forum=csharpgeneral)) suggest that uninstalling KB968389 and changing some registry settings might help.

At this point, it looks like this is possibly a bug in the underlying .NET `SslStream` class; your best workaround might be to catch this exception and retry `MySqlConnection.Open` (since you know that this exception is spurious in your environment).

**Comment by RaidMax** [comment]
Thanks for checking it out, I'll see what I can remedy with the articles you provided. I'm going to go ahead and close it as it looks like it's a .NET bug.
