### ISSUE TITLE
When connection strings contains "Allow Zero Datetime=True" MySqlConnector fails to read dates from database

### ISSUE THREAD

**Issue by MiloszKrajewski** [mysql-net/MySqlConnector#597]
# Versions

Runtime: NET Framework 4.7.1
MySqlConnector: 0.48.1
MySQL: 5.7.21 (docker@ubuntu)

# Symptoms

When connection strings contains "Allow Zero Datetime=True" MySqlConnector fails to read dates from database, even something like `select now()`.

Throws:

```
Test method x.AdHocTests.TryWithAllowZeroDateTime threw exception: 
System.InvalidCastException: Specified cast is not valid.
    at MySql.Data.MySqlClient.MySqlDataReader.GetDateTime(Int32 ordinal) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 200
   at x.AdHocTests.TryWithAllowZeroDateTime(Boolean allowZeroDateTime)
```

# Code

```csharp
[TestClass]
public class AdHocTests
{
    [TestMethod]
    [DataRow(false)]
    [DataRow(true)]
    public void TryWithAllowZeroDateTime(bool allowZeroDateTime = false)
    {
        var connectionString =
            "server=localhost;port=3306;database=x;uid=x;password=x";
        if (allowZeroDateTime)
            connectionString += ";Allow Zero Datetime=True";
        var queryText = "select now()";

        using (var connection = new MySqlConnection(connectionString))
        using (var command = new MySqlCommand 
            { Connection = connection, CommandText = queryText })
        {
            connection.Open();
            using (var reader = command.ExecuteReader())
            {
                reader.Read();
                var _ = reader.GetDateTime(0);
            }
        }
    }
}
```

# Expected results

Test passes in both cases

# Actual results

Test passes for `false` (no "Allow Zero Datetime") but fails for `true` (with "Allow Zero Datetime").

**Comment by bgrainger** [comment]
This was a regression introduced in d35322f1670e9fee9f659c7ef3435b602e1f2f92.

**Comment by bgrainger** [comment]
Fixed in [0.48.2](https://github.com/mysql-net/MySqlConnector/releases/tag/0.48.2).

Note that calling `MySqlDataReader.GetDateTime()` when `AllowZeroDateTime=True` is potentially a bad idea anyway, as the column can contain values (such as `0000-00-00`) that aren't expressible as a `System.DateTime` value.

You may wish to write instead:

```csharp
var mySqlDateTime = reader.GetMySqlDateTime(0);
if (mySqlDateTime.IsValidDateTime)
{
    var dateTime = mySqlDateTime.GetDateTime();
    // use dateTime...
}
```

**Comment by MiloszKrajewski** [comment]
Thanks. Impressive timing!

**Comment by bgrainger** [comment]
Thanks for a well-written bug report!
