### ISSUE TITLE
SSL Authentication Error: The message or signature supplied for verification has been altered

### ISSUE THREAD

**Issue by kkla320** [mysql-net/MySqlConnector#621]
I am getting the following error for some of my queries. The database I am connecting to is an Amazon Aurora DB. The Hosting OS is Windows Server 2016. The MySqlConnector is being used as a dependency of Pomelo.EntityFrameworkCore.MySql 2.2.0. The Version of MySQLConnector is 0.49.2.

```
MySql.Data.MySqlClient.MySqlException (0x80004005): SSL Authentication Error ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The message or signature supplied for verification has been altered
--- End of inner exception stack trace ---
at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
at MySqlConnector.Core.ServerSession.<InitSslAsync>d__80.MoveNext()
at MySqlConnector.Core.ServerSession.<InitSslAsync>d__80.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at MySqlConnector.Core.ServerSession.<ConnectAsync>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at MySqlConnector.Core.ConnectionPool.<GetSessionAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at MySqlConnector.Core.ConnectionPool.<GetSessionAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__96.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at MySql.Data.MySqlClient.MySqlConnection.Open()
at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

**Comment by bgrainger** [comment]
This is a slightly different inner exception (`Win32Exception: The message or signature supplied for verification has been altered`) than #576 (`Win32Exception: The message received was unexpected or badly formatted`) but the common factor appears to be Amazon Aurora (see comments in that case).

For now, I'm considering this a duplicate.

It _may_ help to get a packet capture of the failed connection, but this probably ultimately needs to be addressed by Amazon support: it appears to be a failure of the Windows TLS libraries to communicate with Amazon's service (not with MySqlConnector per se).

**Comment by kkla320** [comment]
Thanks for the reply. I will try to contact the amazon support.

**Comment by magnusfox** [comment]
> 
> 
> Thanks for the reply. I will try to contact the amazon support.

We're also experiencing this with Amazon Aurora, did you ever get any feedback from the Amazon support?

**Comment by magnusfox** [comment]
> 
> 
> Thanks for the reply. I will try to contact the amazon support.

Trying again, as I'm really struggling with this. Did you ever get any response from Amazon?

**Comment by kkla320** [comment]
Sorry for the long wait. I contacted the support. They weren't able to identify any problem and told me to implement a retry strategy, so I used the default implementation from EntityFramework and MySqlConnector. 

Sorry for the disappointment but I couldn't get any more informations.

**Comment by magnusfox** [comment]
> 
> 
> Sorry for the long wait. I contacted the support. They weren't able to identify any problem and told me to implement a retry strategy, so I used the default implementation from EntityFramework and MySqlConnector.
> 
> Sorry for the disappointment but I couldn't get any more informations.

Thanks for letting me know. If you've any pointers as to where to start implementing such a retry strategy, that'd be much appreciated!

**Comment by bgrainger** [comment]
You may want to investigate using Polly to wrap your EFCore/MySQL logic in a retry policy (examples on this page): https://github.com/App-vNext/Polly#polly

**Comment by magnusfox** [comment]
> 
> 
> You may want to investigate using Polly to wrap your EFCore/MySQL logic in a retry policy (examples on this page): https://github.com/App-vNext/Polly#polly

Great, I'm checking it out now. While doing so, however, I stumbled upon the `MySqlDbContextOptionsBuilder.EnableRetryOnFailure` method, which enables retrying of failed DB commands. Do you have any experience in using that as a mean of solving the SSL issue?

**Comment by bgrainger** [comment]
No, I wasn't aware of that class. (I'm not very familiar with the Pomelo library overall.)

If you're using Pomelo.EFCore, it might make sense to start with that built-in feature first, before adding Polly.

**Comment by kkla320** [comment]
@magnusfox 
We implemented our retry strategy with the `MySqlDbContextOptionsBuilder.EnableRetryOnFailure` Method. Using this method did not help resolving the issue. I will reopen the correponding AWS Case. I will let you know if there are any new infos regarding this issue.

**Comment by bgrainger** [comment]
Thanks for letting me know. For now you may have to retry using Polly, but I'll look into implementing `ConnectRetryCount` (#596) as a retry strategy.

**Comment by kkla320** [comment]
@bgrainger 
Sounds very good to me 👍 Thanks for your support by implementing the retry strategy. 
I will look forward to implement a simple retry strategy with polly.

**Comment by magnusfox** [comment]
Same for us. I added 0 as a custom error code for it, as it seems those SSL errors are not being sent back as anything other than 0 (if I'm reading it correctly). However, that didn't seem to do any good either.

Error codes 1040,1205,1213 and1614 seem to be the only ones handled by the default implementation.

**Comment by kkla320** [comment]
> Same for us. I added 0 as a custom error code for it, as it seems those SSL errors are not being sent back as anything other than 0 (if I'm reading it correctly). However, that didn't seem to do any good either.
> 
> Error codes 1040,1205,1213 and1614 seem to be the only ones handled by the default implementation.

How did you added 0 as a custom error code? Do you have a link for an example?

**Comment by magnusfox** [comment]
> How did you added 0 as a custom error code? Do you have a link for an example?

I just used the overload of `EnableRetryOnFailure `that accepts a retry count, a time between attempts and an additional collection of error numbers.

**Comment by ajaysuwalka** [comment]
Changing FROM `mcr.microsoft.com/dotnet/aspnet:5.0.10-focal` to `FROM mcr.microsoft.com/dotnet/aspnet:5.0` Helped me

Basically focal images have this issue hence use non focal images
