### ISSUE TITLE
Implement new async methods coming in .NET Core 3.0

### ISSUE THREAD

**Issue by roji** [mysql-net/MySqlConnector#642]
.NET Core 3.0 (and hopefully .NET Standard 2.1) will fill in some missing async APIs (e.g. transaction management), these should be implemented in MySqlConnector at some point.

dotnet/corefx#35012

**Comment by bgrainger** [comment]
* Add `override ValueTask<DbTransaction> BeginDbTransactionAsync`
* Add `MySqlConnection.CloseAsync` (#467), `MySqlConnection.DisposeAsync`
* Add `MySqlTransaction.DisposeAsync`
* Add `MySqlCommand.DisposeAsync`
* Add `MySqlDataReader.CloseAsync`, `MySqlDataReader.DisposeAsync`

Open questions:

* Should `new MySqlConnection.BeginTransactionAsync` change to return `ValueTask<MySqlTransaction>`, or keep the return type as `Task<MySqlTransaction>`? It will always perform I/O.

**Comment by roji** [comment]
> Should new MySqlConnection.BeginTransactionAsync change to return ValueTask<MySqlTransaction>, or keep the return type as Task<MySqlTransaction>? It will always perform I/O.

Since this is a provider-specific method, it ultimately depends on you.

First, are you sure the roundtrip-reducing optimization I described [here](https://github.com/dotnet/corefx/issues/35012#issuecomment-495006807) is absolutely impossible with MySQL, and will never be possible? Because if the possibility exists it's definitely better to choose ValueTask now to avoid a breaking change later.

Even without this optimization, I'd lean towards leaving it to return ValueTask for consistency with the ADO.NET API. I suspect the extra overhead from ValueTask is going to be quite negligible for this specific method, which does a roundtrip - it may be best to simply benchmark this.

**Comment by bgrainger** [comment]
The (unstated) compatibility concern is with Connector/NET, which has exposed a (sync) `Task<MySqlTransaction> MySqlConnection.BeginTransactionAsync()` method for years, and which MySqlConnector currently clones.

The optimisation you mention may be possible by implicitly batching the `START TRANSACTION;` statement with the next statement the client executes. There would be some amount of complexity with doing that so I'm not planning to implement it soon.

**Comment by roji** [comment]
> The (unstated) compatibility concern is with Connector/NET, which has exposed a (sync) Task<MySqlTransaction> MySqlConnection.BeginTransactionAsync() method for years, and which MySqlConnector currently clones.

Oh, I see, that makes some sense. If you're doing a major release and are willing to break this, it may be worth it - I'm not sure how important it is for you to be totally compatible with the Oracle provider. In any case the ValueTask/Task difference isn't huge for more scenarios - unless users are doing something more than awaiting (which may be rare with BeginTransactionAsync() specifically) there's no real difference - just a binary break that requires a recompile.

But if you really don't think you'll be doing the optimization it's just as well to leave it as is, I guess.

**Comment by bgrainger** [comment]
> I'm not sure how important it is for you to be totally compatible with the Oracle provider. 

Porting any code from Connector/NET to MySqlConnector requires (at minimum) a recompile, so a binary-breaking but source-compatible change is fine. After more thought, it seems best to align with ADO.NET here (even if it's not technically an `override` on most frameworks).

**Comment by bgrainger** [comment]
After all that, I didn't actually change the return type of `BeginTransactionAsync` (or add the necessary `override`).

**Comment by bgrainger** [comment]
> The (unstated) compatibility concern is with Connector/NET, which has exposed a (sync) `Task<MySqlTransaction> MySqlConnection.BeginTransactionAsync()` method for years, and which MySqlConnector currently clones.

However, Connector/NET does not provide `MySqlTransaction.CommitAsync` or `MySqlTransaction.RollbackAsync` (not even with synchronous implementations), so continuing to be API-compatible with Connector/NET seems much less important.

**Comment by JoJo2406** [comment]
Just as a heads up the changes breaks compatibility with Pomelo.EntityFrameworkCore.MySql and will throw a runtime exception when SaveAsync is called on the ef core context.

MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<MySql.Data.MySqlClient.MySqlTransaction> MySql.Data.MySqlClient.MySqlConnection.BeginTransactionAsync(System.Data.IsolationLevel, System.Threading.CancellationToken)'.

**Comment by bgrainger** [comment]
I knew this would probably happen, since it is a binary breaking change. However, I hadn't coordinated with Pomelo yet. Just opened https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/794 to track it.

**Comment by bgrainger** [comment]
@JoJo2406 I've pushed a [preview release of Pomelo.EFCore](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/2.2.1-preview1-final) that's compatible with the 0.57.0-beta series.

**Comment by JoJo2406** [comment]
Thanks Bradley,

I will test and let you know if I come across any issues.

**Comment by SeriaWei** [comment]
@bgrainger I get the exception with version `2.2.1-preview1-final` when call `DbContextOptionsBuilder.UseMySql(string connectionString)`
```
System.TypeLoadException: Method 'get_Info' in type 'Pomelo.EntityFrameworkCore.MySql.Infrastructure.Internal.MySqlOptionsExtension' from assembly 'Pomelo.EntityFrameworkCore.MySql, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Microsoft.EntityFrameworkCore.MySqlDbContextOptionsExtensions.UseMySql
   at ZKEACMS.EntityFrameWorkConfigure.OnConfiguring(DbContextOptionsBuilder optionsBuilder, DbConnection dbConnectionForReusing) in E:\GitHub\ZKEACMS.Core\src\ZKEACMS\EntityFrameWorkConfigure.cs:line 57
   at ZKEACMS.ServiceCollectionExtend.<>c__0`1.<AddDbContextOptions>b__0_0(IServiceProvider sp) in E:\GitHub\ZKEACMS.Core\src\ZKEACMS\Extend\ServiceCollectionExtend.cs:line 22
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at ZKEACMS.Redirection.RedirectRouteConstraint.Match(HttpContext httpContext, IRouter route, String routeKey, RouteValueDictionary values, RouteDirection routeDirection) in E:\GitHub\ZKEACMS.Core\src\ZKEACMS.Redirection\RedirectRouteConstraint.cs:line 27
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.ProcessConstraints(Endpoint endpoint, KeyValuePair`2[] constraints, HttpContext httpContext, RouteValueDictionary values)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```
My application is run on .net core 3.0 preview 7

**Comment by bgrainger** [comment]
Added in [0.57.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.57.0).
