### ISSUE TITLE
Connection closed exceptions after migration from mysql.data to mysql connector

### ISSUE THREAD

**Issue by tomekpr** [mysql-net/MySqlConnector#661]
Hi,

I hope someone can advise on the following problem. I have a windows service that I'm trying to migrate from Mysql.Data to mysqlconnector-net. With other services the process was fairly smooth but the target databases arent under high load.

After the upgrade, I've started to notice exceptions like the following one: 'System.InvalidOperationException: Connection must be Open; current state is Closed'

The database server is quite busy, a lot of connections open and I can see that some insert operations take 20s. This is expected. This is our test environment and the RDS instance is quite small. I'm guessing that the sql-related operations just take a lot of time, connections are closed in the meantime and I end up with this problem.
   
What I don't understand is why am I seeing these exceptions after upgrade ? Connection count hasn't really changed and default values for command timeouts and connection timeouts seem to be the same when I compare mysql.data and mysqlconnector.

   Thanks,
   TP

**Comment by tomekpr** [comment]
Hi,

Just an update to the above case. I've just noticed that on upper environments I also saw similar errors with mysql.data so I wouldn't attribute this problem to the mysql-connector. It's time for some additional code-review.

**Comment by bgrainger** [comment]
If you're using async code (e.g., `ExecuteReaderAsync`), MySqlConnector can expose a new class of errors, because it actually implements these methods with real async I/O. (MySql.Data just fakes it.)

It would be helpful to see the full exception call stack, but I'm guessing it's possible a `MySqlConnection` object is getting shared between two threads, and getting closed on one while another is still using it. This is not allowed by the API.

It may help to enable debug-level logging and see if that provides any clues: https://mysqlconnector.net/overview/logging/

**Comment by tomekpr** [comment]
The timeouts are happening when the connection (session) is reset between uses, one option is to disable the connection reset its just a connection string change add ConnectionReset=false

**Comment by bgrainger** [comment]
The error message is the same as #667. Can you post the full call stack from when this happens, so I can see if it's the same bug?

**Comment by tomekpr** [comment]
Sure,

`2019-06-27 10:03:16,080|ERROR|Betgenius.InRunning.GameServer.Host.Adaptors.Persistence.MySql.ReadSide.MySqlGameEventReadSidePersistor|12| Error when attempting to persist event Betgenius.InRunning.Common.DomainModel.Events.MarketSetOnlineEvent to MySqlReadSide :server=test;uid=testuser;pwd=testpass;database=GameState;SslMode=none;UseCompression=False;maxpoolsize=15 Connection state: Closed System.InvalidOperationException: Connection must be Open; current state is Closed
   at MySql.Data.MySqlClient.MySqlConnection.get_Session() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 422
   at MySql.Data.MySqlClient.MySqlCommand.ResetCommandTimeout() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 389
   at MySql.Data.MySqlClient.MySqlCommand.<ExecuteNonQueryAsync>d__61.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 276
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 77
   at Betgenius.InRunning.GameServer.Host.Adaptors.Persistence.MySql.ReadSide.MySqlGameEventReadSidePersistor.SaveIndividualEvent(GameKey gameKey, IGameEvent gameEvent, MySqlConnection connection, Guid correlationId, OperationTimingContext operationTimingContext)`
