### ISSUE TITLE
"Invalid cast from 'System.String' to 'System.TimeSpan'." is thrown when getting value of output parameter which its type is TIME

### ISSUE THREAD

**Issue by nhathongly** [mysql-net/MySqlConnector#680]
I got this exception when trying get the output value of TIME

```
System.InvalidCastException : Invalid cast from 'System.String' to 'System.TimeSpan'.
 StackTrace:
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at MySqlConnector.Core.DbTypeMapping.DoConversion(Object obj) in C:\projects\mysqlconnector\src\MySqlConnector\Core\DbTypeMapping.cs:line 22
   at MySqlConnector.Core.StoredProcedureCommandExecutor.SetParams() in C:\projects\mysqlconnector\src\MySqlConnector\Core\StoredProcedureCommandExecutor.cs:line 108
   at MySql.Data.MySqlClient.MySqlCommand.ReaderClosed() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 452
   at MySql.Data.MySqlClient.MySqlDataReader.DoClose() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 445
   at MySql.Data.MySqlClient.MySqlDataReader.Dispose(Boolean disposing) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 282
```

**Comment by bgrainger** [comment]
It looks like you might be using a stored procedure with an `OUT` parameter. Can you provide more details on how to reproduce this, e.g., table definition, stored procedure definition, sample code?

**Comment by nhathongly** [comment]
My stored procedure is simply like this

```sql
CREATE DEFINER=`root`@`%` PROCEDURE `GetTime`(OUT OutTime TIME)
BEGIN
	SET OutTime = CURTIME();
END
```
I'm totally new to MySql, so I don't know if I get any mistake

**Comment by nhathongly** [comment]
Hi there,

I experienced the same issue when the data type of OUTPUT parameter is BOOL. The exception said that "Object of type 'System.SByte' cannot be converted to type 'System.Boolean'." when I tried to map the OUTPUT to a `bool` variable.
Could you have a check?

Thanks

**Comment by nhathongly** [comment]
When I executed the following script, I saw that the DTD_IDENTIFIER value in `information_schema.parameters` of a BOOL parameter was TINYINT(1)

```sql
SELECT ORDINAL_POSITION, PARAMETER_MODE, PARAMETER_NAME, DTD_IDENTIFIER
FROM information_schema.parameters
WHERE SPECIFIC_SCHEMA = 'DB Name' AND SPECIFIC_NAME = 'Routine Name'
ORDER BY ORDINAL_POSITION;
```

ORDINAL_POSITION| PARAMETER_MODE| PARAMETER_NAME| DTD_IDENTIFIER
-- | -- | -- | --
1 | IN | js | json
2 | OUT | b | tinyint(1)

**Comment by nhathongly** [comment]
Seem it will be fixed when https://github.com/mysql-net/MySqlConnector/commit/782a765daabfea2cd7ffb5df98c146fc370b9beb is released

**Comment by bgrainger** [comment]
I'll release 0.57.0-beta9 with this fix soon. The beta versions are tested and reliable enough to run in production; they just haven't shipped as a "stable" release yet due to breaking API changes in this series.

**Comment by bgrainger** [comment]
[0.57.0-beta9](https://www.nuget.org/packages/MySqlConnector/0.57.0-beta9) is available with this fix.
