### ISSUE TITLE
SSL Authentication Error

### ISSUE THREAD

**Issue by Caskia** [mysql-net/MySqlConnector#685]
**Version Used**: 
mysqlconnector version: 0.56.0 
net core sdk version: 3.0.100-preview8-013656
os version: ubuntu 16.04.4 LTS x64

**Exception**

```
ERROR 2019-08-30 14:32:36,330 [45   ] ing.Impl.DefaultProcessingCommandHandler -  MySqlException raised when RoasterCommandHandler handling RoasterAcceptSocializerFollow. commandId:5d6933833cf7ac0001cff78e_RoasterAcceptSocializerFollow, aggregateRootId:190759290141679616
MySql.Data.MySqlClient.MySqlException (0x80004005): SSL Authentication Error
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:1425F102:SSL routines: ssl_choose_client_version:unsupported protocol
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, ArraySegment`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__64_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at MySqlConnector.Core.ServerSession.InitSslAsync(ProtocolCapabilities serverCapabilities, ConnectionSettings cs, SslProtocols sslProtocols, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 1170
   at MySqlConnector.Core.ServerSession.InitSslAsync(ProtocolCapabilities server
Capabilities, ConnectionSettings cs, SslProtocols sslProtocols, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 1197
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 
335
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 112
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line
 585
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 306
```

**Comment by bgrainger** [comment]
Is this happening consistently when opening a connection, or just intermittently?

The actual error appears to be coming from OpenSSL, so if you have a consistent repro it might be a bug to raise with the dotnet/corefx team.

**Comment by bgrainger** [comment]
What's your MySQL Server variant (MySQL, MariaDB, Aurora, etc.), version, and underlying OS?

**Comment by Caskia** [comment]
It's happening consistently. The database is mysql on Ubuntu 16.04. When netcore sdk is 2.0, it's running normally.

**Comment by Caskia** [comment]
May be related to [this](https://github.com/dotnet/corefx/issues/40538)

**Comment by bgrainger** [comment]
That does seem very similar (although not exactly the same). It does seem very much like this is an underlying corefx (or OpenSSL) problem; I would recommend opening an issue on that repo if the workarounds in dotnet/corefx#40538 don't solve your problem.

I don't think there's anything MySqlConnector can change to resolve this.

**Comment by ajaysuwalka** [comment]
Changing FROM `mcr.microsoft.com/dotnet/aspnet:5.0.10-focal` to `FROM mcr.microsoft.com/dotnet/aspnet:5.0` Helped me

Basically focal images have this issue hence use non focal images
