### ISSUE TITLE
Exception occurred when cancelling a command

### ISSUE THREAD

**Issue by tohghua** [mysql-net/MySqlConnector#693]
```csharp
using (var conn = new MySqlConnection("..."))
{
    conn.Open();
    var cmd = new MySqlCommand("select sql_no_cache count(*) from a_big_table a, a_big_table b", conn);
    var src = new CancellationTokenSource();
    var tsk = cmd.ExecuteNonQueryAsync(src.Token);
    if (!tsk.Wait(1000)) src.Cancel();
}
```

**Above code will generate this exception on connection dispose:**

```
MySql.Data.MySqlClient.MySqlProtocolException
  HResult=0x80131509
  Message=Packet received out-of-order. Expected 1; got 3.
  Source=mscorlib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.DoReadPayloadAsync(BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ArraySegmentHolder`1 previousPayloads, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in D:\temp\MySqlConnector-0.56.0\src\MySqlConnector\Protocol\Serialization\ProtocolUtility.cs:line 463
```

**Comment by bgrainger** [comment]
You're misusing the library by disposing the connection before `await`ing the `Task` that was created on it. Add a call to `await tsk;` (or `tsk.GetAwaiter().GetResult();`) before the end of the `using` block.

It would also be a lot more idiomatic to use a `CancellationTokenSource` with a built-in timeout:

```csharp
using (var conn = new MySqlConnection("..."))
{
	conn.Open();
	var cmd = new MySqlCommand("select sql_no_cache count(*) from a_big_table a, a_big_table b", conn);
	using (var src = new CancellationTokenSource(TimeSpan.FromSeconds(1)))
	{
		try
		{
			await cmd.ExecuteNonQueryAsync(src.Token);
		}
		catch (OperationCanceledException ex)
		{
			Console.WriteLine("tsk was canceled");
		}
	}
}
```

**Comment by tohghua** [comment]
It works. 
Thanks a lot!
