### ISSUE TITLE
 Connect Timeout expired. All pooled connections are in use.

### ISSUE THREAD

**Issue by carlos-ferreira** [mysql-net/MySqlConnector#740]
After updating to the latest release started to find on the logs the following error:

Exception 1: 
 `Connect Timeout expired. All pooled connections are in use. `

Exception 2:
 ` The operation was canceled.
   at System.Threading.SemaphoreSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MySqlConnector.Core.ConnectionPool.<GetSessionAsync>d__10.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__109.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 645`

Can you give me some details on how can i overcome this issue ?
If it helps to know , we're using sync operations , or no async.

**Comment by bgrainger** [comment]
As the first exception message implies, you're calling `MySqlConnection.Open` but there are no free connections in the pool. (This defaults to 100 but is controlled by `MaximumPoolSize` in the connection string.)

The most common cause is a connection leak, i.e., a `MySqlConnection` or `MySqlDataReader` that's not being closed/disposed correctly. Running `SHOW PROCESSLIST;` on the server may provide clues as to the client/clients that are leaking connections. 

MySqlConnector does try to automatically clean leaked connections up, but it requires them not to be GC-rooted and for a GC to have happened. It's possible this isn't running correctly (although there are integration tests to verify that it does work in a simple scenario).

Another cause can be that there are no free connections on the server. You can compare `SHOW STATUS LIKE 'Threads_connected';` to `SELECT @@max_connections;` to see if you're reaching your connection limit with open connections.

Enabling logging at the default level may provide additional information helpful for tracking this problem down: https://mysqlconnector.net/overview/logging/

**Comment by carlos-ferreira** [comment]
Thank you for your explanation.

The issue happened because some connection strings had MaximumPoolSize=4, we removed that and the issue was gone.

You can closed this with the tag #needsmorecoffee  :)
