### ISSUE TITLE
Incorrect datetime value exception

### ISSUE THREAD

**Issue by CrossBound** [mysql-net/MySqlConnector#766]
Hello, I am getting an exception when trying to write a particular date using the MySqlConnector. What's strange is that it seems to be tied to a specific date/time value, other date/time values are working fine, this particular record seems to be failing though. 

Here's my code.
``` csharp
Command.Parameters.Add("@last_successful_login_time", MySqlDbType.Timestamp).Value =
	User.LastSuccessfulLoginTime.HasValue ? (object)User.LastSuccessfulLoginTime.Value : DBNull.Value;
```
User.LastSuccessfulLoginTime is of type `DateTimeOffset?`

Here is the exception being thrown. Notice how the date doesn't seem to be invalid in any way. 
``` 
MySql.Data.MySqlClient.MySqlException (0x80004005): Incorrect datetime value: '2019-03-10 02:00:53' for column `benchmarks`.`users`.`last_login_success_time` at row 1
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Incorrect datetime value: '2019-03-10 02:00:53' for column `benchmarks`.`users`.`last_login_success_time` at row 1
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 49
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 116
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 391
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\CommandExecutor.cs:line 62
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 226
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 74
   at EmbeddedDatabaseBenchmarks.MariaDBUserStore.addUser(MySqlCommand Command, User User) in D:\Projects\ProtoTypes\EmbeddedDatabaseBenchmarks\EmbeddedDatabaseBenchmarks\MariaDBUserStore.cs:line 138
   at EmbeddedDatabaseBenchmarks.MariaDBUserStore.InsertNewRecord(User User) in D:\Projects\ProtoTypes\EmbeddedDatabaseBenchmarks\EmbeddedDatabaseBenchmarks\MariaDBUserStore.cs:line 286
   at EmbeddedDatabaseBenchmarks.Program.Main(String[] args) in D:\Projects\ProtoTypes\EmbeddedDatabaseBenchmarks\EmbeddedDatabaseBenchmarks\Program.cs:line 32
```

If I change the date/time value to something different it works fine.

Here is my table definition: 
``` sql
CREATE TABLE users (
	id CHAR(16) NOT NULL PRIMARY KEY
	, username VARCHAR(50) NOT NULL UNIQUE
	, email TEXT NULL
	, email_confirmed BOOLEAN NOT NULL
	, phone TEXT NULL
	, phone_confirmed BOOLEAN NOT NULL
	, security_stamp TEXT NOT NULL
	, hide_save_page BOOLEAN NOT NULL
	, hide_deposit_instructions BOOLEAN NOT NULL
	, biometric_auth_enabled BOOLEAN NOT NULL
	, bypass_device_auth BOOLEAN NOT NULL
	, lockout_enabled BOOLEAN NOT NULL
	, lockout_end_time TIMESTAMP NULL
	, failed_login_count INT NOT NULL
	, last_login_fail_time TIMESTAMP NULL
	, last_login_success_time TIMESTAMP NULL
	, last_rateapp_display_time TIMESTAMP NULL
	, password_expiration_time TIMESTAMP NOT NULL
	, password TEXT NOT NULL
);
```

**Comment by CrossBound** [comment]
This is so strange... It specifically seems to only be a problem with any time between `2019-03-10 02:00:00` and `2019-03-10 02:59:59`. Values of `2019-03-10 03:00:00` and `2019-03-11 02:00:00` both work without any issue.

**Comment by bgrainger** [comment]
I’m guessing MySQL Server is treating the values as local time, and that hour did not exist as local time in that time zone (because the clock is set forward for Daylight Saving Time).

I think you may need to set your server’s time zone to UTC, or make sure you only store DateTimeKind.Local DateTime values in that column.

**Comment by CrossBound** [comment]
You would be correct, DST began 03-10-2019 2:00 AM... sorry for the false alarm.

https://jira.mariadb.org/browse/MDEV-13062

**Comment by bgrainger** [comment]
Note that because MySQL can't store date+timezone in a single column, `DateTimeOffset` values will be converted to UTC for storage: https://github.com/mysql-net/MySqlConnector/issues/172#issuecomment-277178444

To avoid that, use a `DateTime` value.
