### ISSUE TITLE
System.IO.IOException: Unable to write data to the transport connection: Broken pipe(net core 3.0+mysql server 8.0)

### ISSUE THREAD

**Issue by mfjiang** [mysql-net/MySqlConnector#776]
my .net core 3.0 app run on cent os 7+mysql 8.0

my connection string:
`server=1xx.xx.xxx.xxx;database=db1;user=***;password=***;charset=utf8;pooling=true;min pool size =10;max pool size=1024;default command timeout=120;`

error log here:

```
System.IO.IOException: Unable to write data to the transport connection: Broken pipe.

System.IO.IOException: Unable to write data to the transport connection: Broken pipe.
---> System.Net.Sockets.SocketException (32): Broken pipe
at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
--- End of inner exception stack trace ---
at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
at System.Net.Security.SslStream.WriteSingleChunk[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
at System.Net.Security.SslStream.WriteAsyncInternal[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
at System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)
at MySql.Data.MySqlClient.TimedStream.Write(Byte[] buffer, Int32 offset, Int32 count)
at MySql.Data.MySqlClient.MySqlStream.SendPacket(MySqlPacket packet)
at MySql.Data.MySqlClient.NativeDriver.ExecutePacket(MySqlPacket packetToExecute)
at MySql.Data.MySqlClient.NativeDriver.Close(Boolean isOpen)
```

**Comment by bgrainger** [comment]
Your exception is coming from Oracle MySQL Connector/NET (aka `MySql.Data`).

This repository is for https://www.nuget.org/packages/MySqlConnector/

I have two suggestions:

1. Uninstall MySql.Data and install MySqlConnector to see if it fixes the problem.
2. Report this problem at https://bugs.mysql.com if you want to keep using MySql.Data.

**Comment by mfjiang** [comment]
sorry,thanks.

**Comment by reinaldocoelho** [comment]
@mfjiang , your problem was solved?
We are having the same error here and not understand whats happening. If the driver is the problem we can try to change them.

Thanks.

**Comment by Palindromer** [comment]
@mfjiang @reinaldocoelho, do you find a solution? I have the same problem.((

**Comment by reinaldocoelho** [comment]
@Palindromer , we change the driver to MySqlConnector and its Ok until now.
