### ISSUE TITLE
GetSchema("Columns") throws "Unknown column 'SRS_ID' in 'field list'"

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#805]
Using MySQL Server 5.7, the following code throws an exception:

```csharp
using var connection = new MySqlConnection(connectionString);
connection.Open();
connection.GetSchema("Columns");
```

```
MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown column 'SRS_ID' in 'field list'
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown column 'SRS_ID' in 'field list'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\Code\MySql\MySqlConnector\src\MySqlConnector\Core\ResultSet.cs:line 51
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in C:\Code\MySql\MySqlConnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 130
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Code\MySql\MySqlConnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 390
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Code\MySql\MySqlConnector\src\MySqlConnector\Core\CommandExecutor.cs:line 62
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\Code\MySql\MySqlConnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 211
   at System.Data.Common.DbCommand.ExecuteReader()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader() in C:\Code\MySql\MySqlConnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 71
   at MySqlConnector.Core.SchemaProvider.FillDataTable(DataTable dataTable, String tableName) in C:\Code\MySql\MySqlConnector\src\MySqlConnector\Core\SchemaProvider.cs:line 984
   at MySqlConnector.Core.SchemaProvider.FillColumns(DataTable dataTable) in C:\Code\MySql\MySqlConnector\src\MySqlConnector\Core\SchemaProvider.cs:line 192
   at MySqlConnector.Core.SchemaProvider.GetSchema(String collectionName) in C:\Code\MySql\MySqlConnector\src\MySqlConnector\Core\SchemaProvider.cs:line 59
   at MySql.Data.MySqlClient.MySqlConnection.GetSchema(String collectionName) in C:\Code\MySql\MySqlConnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 395
```

**Comment by bgrainger** [comment]
Caused by #724. Fixed in [0.64.1](https://github.com/mysql-net/MySqlConnector/releases/tag/0.64.1).
