### ISSUE TITLE
Socket Exception on dataReader.Read()

### ISSUE THREAD

**Issue by swjain23** [mysql-net/MySqlConnector#894]
Hi,

We have a multi threaded application which is reading a lot of rows from a MySQL database. After executing a query we return dataReader and go through each row to create a dataset. 

```
using (dataRangeResultDbReader)
{
    while (!dataRangeResultDbReader.IsClosed
        && dataRangeResultDbReader.Read())
    {
        cancelToken.ThrowIfCancellationRequested();
        ++readRowCount;

        if (rowValues == null)
        {
            rowValues = new object[dataRangeResultDbReader.FieldCount];
        }

        dataRangeResultDbReader.GetValues(rowValues);
    }

    dataRangeResultDbReader.Close();
}
```

After some reads, it gets stuck on dataRangeResultDbReader.Read() and eventually fails with below error. The command timeout is set to 2 hours and wait_timeout is set to 3600 sec.

I looked at the stack trace and it was stuck on Socket.Pool():

![image](https://user-images.githubusercontent.com/36710109/95515133-f9b0cc80-0971-11eb-9646-d4ef33380cdb.png)

```
Inner exception type: MySqlConnector.MySqlException
            Message: 
                The Command Timeout expired before the operation completed.
            HResult : 0x80004005
                FacilityCode : 0 (000)
                ErrorCode : 16389 (4005)
            Data: 
                Server Error Code = -1
            Stack: 
                at MySqlConnector.Protocol.Serialization.SocketByteHandler.<DoReadBytesAsync>d__8.MoveNext() in /_/src/MySqlConnector/Protocol/Serialization/SocketByteHandler.cs:line 97
                --- End of stack trace from previous location where exception was thrown ---
                at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
                at MySqlConnector.Protocol.Serialization.BufferedByteReader.<ReadBytesAsync>d__2.MoveNext() in /_/src/MySqlConnector/Protocol/Serialization/BufferedByteReader.cs:line 36
                --- End of stack trace from previous location where exception was thrown ---
                at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
                at MySqlConnector.Protocol.Serialization.ProtocolUtility.<<ReadPacketAsync>g__AddContinuation|1_0>d.MoveNext() in /_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 412
                --- End of stack trace from previous location where exception was thrown ---
                at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
                at MySqlConnector.Protocol.Serialization.ProtocolUtility.<<DoReadPayloadAsync>g__AddContinuation|5_0>d.MoveNext() in /_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 479
                --- End of stack trace from previous location where exception was thrown ---
                at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
                at MySqlConnector.Core.ServerSession.<ReceiveReplyAsyncAwaited>d__82.MoveNext() in /_/src/MySqlConnector/Core/ServerSession.cs:line 801
                --- End of stack trace from previous location where exception was thrown ---
                at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
                at MySqlConnector.Core.ResultSet.<ReadResultSetHeaderAsync>d__2.MoveNext() in /_/src/MySqlConnector/Core/ResultSet.cs:line 49
            Inner exception type: System.Net.Sockets.SocketException
                Message: 
                    The I/O operation has been aborted because of either a thread exit or an application request
                HResult : 0x80004005
                    FacilityCode : 0 (000)
                    ErrorCode : 16389 (4005)
                Error : 995                Stack: 
                    at MySqlConnector.Utilities.SocketAwaitable.GetResult() in /_/src/MySqlConnector/Utilities/SocketAwaitable.cs:line 32
                    at MySqlConnector.Protocol.Serialization.SocketByteHandler.<DoReadBytesAsync>d__8.MoveNext() in /_/src/MySqlConnector/Protocol/Serialization/SocketByteHandler.cs:line 84
```

**Comment by bgrainger** [comment]
Is this the same problem you posted here? https://bugs.mysql.com/bug.php?id=101000

If it's occurring with two different ADO.NET libraries, it seems likely that the problem is with the MySQL Server or the network.

Based on the evidence you've provided, it appears that the server stops responding. MySqlConnector is handling this as expected by throwing a `MySqlException` with a "Command Timeout expired" error when `MySqlCommand.CommandTimeout` expires; that is the purpose of that property.

**Comment by bgrainger** [comment]
`wait_timeout` is a server-side timeout. If the server isn't sending a `RST` packet (or that's not making it to the client) then the client side timeout (`CommandTimeout`) will be the one that ends up getting enforced.

I suggest using Wireshark (or a similar packet capture tool) to troubleshoot your network when this is happening. If you can find a reproducible testcase for MySqlConnector, please reopen this issue.
