### ISSUE TITLE
Connecting to ProxySQL?

### ISSUE THREAD

**Issue by nbon12** [mysql-net/MySqlConnector#934]
Hi, I seem to be having an issue when connecting to ProxySQL,
I'm using MySqlConnector version 1.2.1:
Here's my breakpoint:
<img width="267" alt="openconn" src="https://user-images.githubusercontent.com/17408265/105720065-00e3f200-5ef1-11eb-8c4d-4aee6e1d1826.png">
Then when I "Step Over"
I get this error: 
<img width="691" alt="stackexception" src="https://user-images.githubusercontent.com/17408265/105720089-093c2d00-5ef1-11eb-8219-fbe65e401436.png">
"Index was outside the bounds of the array."

**Comment by bgrainger** [comment]
What's [`mysql-server_version`](https://proxysql.com/documentation/global-variables/#mysql-server_version) set to in your ProxySQL configuration?

**Comment by nbon12** [comment]
It was set to 8.0. After updating the version in ProxySQL to 8.0.19-10, it now works! The MySQL instances were already 8.0.19-10.

FYI, I briefly tried to do this same thing with the Mysql.Data Nuget Package, I got a similar error message over there too, but their error message was more clear:

```C#
MySql.Data.MySqlClient.MySqlException (0x80004005): Version string not in acceptable format
   at MySql.Data.Common.DBVersion.Parse(String versionString)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at Api.Rest.IoC.ApiDefaultRegsitry.GetDapperConnection[T](String connectionString, Boolean profileConnection) in C:\Users\user1\source\Api.Rest\IoC\ApiDefaultRegistry.cs:line 170
   at Api.Rest.IoC.ApiDefaultRegsitry.Load(ContainerBuilder builder) in C:\Users\user1\source\Api.Rest\IoC\ApiDefaultRegistry.cs:line 83
   at Autofac.Module.Configure(IComponentRegistryBuilder componentRegistry)
   at Autofac.ContainerBuilder.Build(IComponentRegistryBuilder componentRegistry, Boolean excludeDefaultModules)
   at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProviderFactory.CreateServiceProvider(ContainerBuilder containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Api.Rest.Program.Main(String[] args) in C:\Users\user1\source\Api.Rest\Program.cs:line 13
```

**Comment by bgrainger** [comment]
The ServerVersion-parsing code was unnecessarily strict; I've fixed it now: 25ce4d0e62aeeaf885eaa864e5decb8fd356eeba.

Your change to the ProxySQL version will still be necessary until that fix ships..

**Comment by bgrainger** [comment]
Fixed in [1.3.0](https://github.com/mysql-net/MySqlConnector/releases/tag/1.3.0).

**Comment by rajivsaxena** [comment]
i am using mysql version 8.0.32, my Proxysql configmap file also has the same version. I am able to connect the mysql instance from proxysql in workbench but not through code, its throwing the error : "Version string is not in acceptable string format". Any suggestion would highly appriciable

**Comment by bgrainger** [comment]
`Version string is not in acceptable string format` is an error message from MySql.Data. This is the repository for MySqlConnector.

Instructions for migrating from MySql.Data to MySqlConnector are here: https://mysqlconnector.net/tutorials/migrating-from-connector-net/.
