### ISSUE TITLE
Doesn't catch error

### ISSUE THREAD

**Issue by jh0ng** [mysql-net/MySqlConnector#950]
MySqlBulkLoader.Load(); -> MySqlException
The above function doesn't catch the error if a duplicate row/entry was inserted in the primary key.
Unlike in MySql.Data.MySqlClient.Load() function, which catches the error.

**Comment by bgrainger** [comment]
Please provide an example that reproduces the error.

**Comment by jh0ng** [comment]
`foreach(FileInfo file in files) {
	try {
		MySqlConnection con = new MySqlConnection("Server...")
		MySqlBulkLoader blk= new MySqlBulkLoader(conn) {
			TableName = "table_name",
			FieldTerminator = ",",
			...
		}
		int count = blk.Loader();
	}
	catch(MySqlException ex) {
		Console.WriteLine(ex.ToString());
	}
}`

Ex. 2 CSV files will be inserted in DB
1.csv contains a primary value that also exists in 2.csv

count in the first file (loop) is correct
but in the second file (loop) count inserted is 0, 
and there is no error caught in the try-catch section for duplicate entry of primary key

Whereas, using MySql.Data.MySqlClient, duplicate error is caught

**Comment by bgrainger** [comment]
I can't reproduce an exception with MySql.Data, nor failure to insert rows with MySqlConnector.

I need a more detailed example with table schema, complete code, and sample files.

**Comment by bgrainger** [comment]
> If you do not specify either modifier, the behavior depends on whether the LOCAL modifier is specified. Without LOCAL, an error occurs when a duplicate key value is found, and the rest of the text file is ignored. With LOCAL, the default behavior is the same as if IGNORE is specified; this is because the server has no way to stop transmission of the file in the middle of the operation.

I assume you're not using `Local = true`; in that case, I can reproduce an exception with both drivers, e.g.,

```
MySqlConnector.MySqlException (0x80004005): Duplicate entry '1' for key 'bulk_load.PRIMARY'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\Code\MySql\MySqlConnector\src\MySqlConnector\Core\ResultSet.cs:line 50
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in C:\Code\MySql\MySqlConnector\src\MySqlConnector\MySqlDataReader.cs:line 135
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Code\MySql\MySqlConnector\src\MySqlConnector\MySqlDataReader.cs:line 444
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Code\MySql\MySqlConnector\src\MySqlConnector\Core\CommandExecutor.cs:line 60
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Code\MySql\MySqlConnector\src\MySqlConnector\MySqlCommand.cs:line 264
   at MySqlConnector.MySqlBulkLoader.LoadAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\Code\MySql\MySqlConnector\src\MySqlConnector\MySqlBulkLoader.cs:line 219
   at MySqlConnector.MySqlBulkLoader.Load() in C:\Code\MySql\MySqlConnector\src\MySqlConnector\MySqlBulkLoader.cs:line 153
```

**Comment by jh0ng** [comment]
> I assume you're not using `Local = true`; in that case, I can reproduce an exception with both drivers, e.g.,

Right, I did not use the `MySqlBulkLoader.Local`
using `Local = true` doesn't throw an exception, but setting it to `false` does.
