### ISSUE TITLE
NullReferenceException is thrown instead of ObjectDisposedException

### ISSUE THREAD

**Issue by hankovich** [mysql-net/MySqlConnector#986]
The following code throws `NullReferenceException`.

```csharp
var connection = new MySqlConnection("Server=localhost; Port=3306; User=root; Database=test; Allow User Variables=true");
connection.Open();

var task = connection.ExecuteAsync("SELECT SLEEP(1)"); // <- extension from Dapper

connection.Dispose();

await task; // thrown here
```

Excepted behavior: `ObjectDisposedException` is thrown instead of `NullReferenceException`.
Version of library being used: 1.2.1.

Stack Trace:
```csharp
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 118
   at MySqlConnector.MySqlDataReader.<CreateAsync>d__97.MoveNext() in /_/src/MySqlConnector/MySqlDataReader.cs:line 436
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySqlConnector.Core.CommandExecutor.<ExecuteReaderAsync>d__0.MoveNext() in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySqlConnector.MySqlCommand.<ExecuteNonQueryAsync>d__69.MoveNext() in /_/src/MySqlConnector/MySqlCommand.cs:line 264
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<ExecuteImplAsync>d__39.MoveNext() in /_/Dapper/SqlMapper.Async.cs:line 646
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

**Comment by bgrainger** [comment]
Misuse of the library (disposing a `MySqlConnection` while it's in use) doesn't have well-defined semantics. (You could accomplish the same thing by executing synchronous methods on one thread and calling `Dispose` on a second thread.)

To get "correct" `ObjectDisposedException`s, there would have to be extensive synchronisation of internal state; this would very likely reduce performance.

I'd almost be inclined to make `Dispose` throw an `InvalidOperationException` ("The connection is in use") but throwing from `Dispose` is a bad idea for many reasons.

The example code is invalid; MySqlConnector makes no guarantees about the exception type that will be thrown under these circumstances. (The closest documentation is https://mysqlconnector.net/troubleshooting/connection-reuse/; that could be updated to note that this style of usage is invalid.)
